### DISCUSSION TITLE
Extensions to the spack containerize command

### DISCUSSION THREAD

**Discussion by alalazo** [spack/spack#20442] [Ideas]
[spack containerize](https://spack.readthedocs.io/en/latest/containers.html) is a command to generate recipes to build container images using Spack. It has been extended in #15028 with the possibility to use custom base images prepared by users, and permit them to go  beyond the capabilities provided by the images published in the Spack organization repository on Dockerhub.

Some workflows though still require more boilerplate than it feels necessary, or are hard to reproduce. Below I'll try to outline  two of them and propose extensions to simplify their management.

## Use a specific git-hash of Spack to build a container image

Currently when using the:
```yaml
images:
  os: ubuntu18.04
  spack: 0.16.0
```
stanza to specify which OS and version of Spack to use for the container images, a user is restricted to combinations that match the images published on [Dockerhub](https://hub.docker.com/r/spack/centos7). All cases that go beyond that must be dealt with custom base images.

A necessity that may arise frequently for reproducibility, in particular when using a non-tagged version of Spack, is that of fixing the git-hash being used for Spack in the generated `Dockerfile`. Asking a user to build its own Docker base image for just that seems really suboptimal. To fix this  we can extend the YAML schema to also accept the following:
```yaml
images:
  os: ubuntu18.04
  spack:
    url: <to-use-a-fork>
    ref: <sha/tag/branch>
    enforce-sha: <true/false>
```
The `enforce-sha` Boolean option, if true, will turn any branch or tag into the corresponding git sha at the moment of recipe generation.

### Example use cases
To use a specific git hash, explicitly given by a user:
```yaml
images:
  os: ubuntu18.04
  spack:
    ref: abcdef
```
the cases for a branch or a tag would be similar. To specify a tag or branch and turn it into the current commit hash at the time of emitting the recipe:
```yaml
images:
  os: ubuntu18.04
  spack:
    enforcs-sha: true
    ref: v0.16.0
```
To use a custom fork of Spack:
```yaml
images:
  os: ubuntu18.04
  spack:
    url: https://github.com/alalazo/spack.git
    ref: features/myfeature
```

## Use custom repositories or mirrors during the image build

At the moment [spack containerize](https://spack.readthedocs.io/en/latest/containers.html) doesn't perform any action in the presence of custom mirrors or custom repositories within the `spack.yaml` file. If they are needed, it's responsibility of the user to create a proper custom base image with all the right pieces in place. The command:
```console
$ spack containerize
```
will just output to `stdout` a Dockerfile assuming that any preliminary setup is already taken care of.

To improve user experience a possible extension would be, in the presence of a `repos` or `mirrors` stanza:
```yaml
spack:
  repos:
  - <repo1>
  - <repo2>
  mirrors:
    <name>: <url>
```
to **produce a proper context directory for Docker instead of just printing the `Dockerfile`**. The repositories and the mirrors mentioned in the `spack.yaml` file will be copied in the context directory, which will contain also the corresponding Dockerfile. The resources will then be copied in the container image at fixed locations and hooked in automatically for the build. This permits e.g. to reproduce the build of an image on another platform by simply tarring the context and rebuilding there.

### Example use cases

If a `spack.yaml` with a `repos` of `mirrors` section is given, the user is requested to specify and additional option:
```console
$ spack containerize --output-dir=<context-directory>
```
The resulting directory will have a structure similar to:
```console
$ tree context/
context/
├── Dockerfile
├── mirrors (directory)
└── repos (directory)

2 directories, 1 file
```
and will contain copies of the custom mirrors and repositories. The corresponding `Dockerfile` will copy them from the context and use them at build time.

**Comment by alalazo** [comment]
@victorusu @tgamblin

**Comment by haampie** [comment]
I don't know the exact terminology, but `branch` and `tag` are both `ref`s in git, I don't think a commit sha is a ref, but in any case, can't it all be condensed in a single keyword `ref: <branch/tag/sha>`? And for repository you can only use a URL, since you can't use SSH inside the container without giving it a key, so maybe `url` and `ref` are short and descriptive ways to set the spack instance?

**Reply by alalazo** [reply]
Fixed the repository, which now uses `https`. For the single `ref` how would you propose to deal with the use case:
```yaml
images:
  os: ubuntu18.04
  spack:
    commit-hash: true
    tag: v0.16.0
```
i.e. use a tag (or a branch) but turn it into a sha when generating the Dockerfile?

**Reply by alalazo** [reply]
Maybe something like this:
```yaml
images:
  os: ubuntu18.04
  spack:
    url: <to-use-a-fork>
    ref: <sha/branch/tag>
    enforce-sha: true
```
?

**Reply by haampie** [reply]
Yeah, that seems sensible :) you can just as well generate a human readable comment above the `git checkout [sha]` command to say what the original ref was, and maybe default `enforce-sha` to `true` or drop the option entirely? Or a docker label or something.

**Comment by bollig** [comment]
Current schema limits os options to Ubuntu and Centos. Also, spack version only applies to os images, NOT build:/final: images. We either need to specify spack version on build/final, or relax the os schema to allow other images (e.g., amazonlinux)

**Reply by alalazo** [reply]
In #21910 I added the possibility to specify more operating systems than just the four we currently have in our Dockerhub repository. I'm also trying to make it such that expanding the list of operating systems further would be a simple operation (adding some metadata to a JSON file and possibly bits of a Dockerfile that are specific to the added OS)

**Comment by bollig** [comment]
Another piece of feedback: containerize needs an option to specify bootstrap specs a la [bootstrap section in Pipelines](https://spack.readthedocs.io/en/latest/pipelines.html). Should result in a separate RUN block to produce intermediate container layer during build allowing for reduced build time.

**Comment by vsoch** [comment]
Related to this issue, if we have a spack.yaml that is going to want to use clingo as the concretizer:

```yaml
spack:
  specs: ["trinity"]
  view: true
  config:
    concretizer: clingo
```

It would make sense to have a container base selected that has dependencies for that, as it is now, the build will fail because Python is missing for the clingo-bootsrap:

```
 1 error found in build log:
     9     -- Detecting C compile features - done
     10    -- Detecting CXX compiler ABI info
     11    -- Detecting CXX compiler ABI info - done
     12    -- Check for working CXX compiler: /opt/spack/lib/spack/env/gcc/g++ 
           - skipped
     13    -- Detecting CXX compile features
     14    -- Detecting CXX compile features - done
  >> 15    CMake Error at /root/.spack/bootstrap/store/linux-ubuntu18.04-x86_64
           /gcc-7.5.0/cmake-3.19.5-exzydea56ecf7rfwcgmkcbezhydvtnlf/share/cmake
           -3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
     16      Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARI
```
See full output in https://github.com/autamus/registry/pull/4/checks?check_run_id=2088604337 and ping @alecbcs

**Reply by alalazo** [reply]
I'm kind of undecided on this. I see your point, but I think you can already solve this by adding:
```yaml
container:
  os_packages:
    build:
    - python-dev
```
(or something similar) to your `spack.yaml`. If we could get bootstrapping from binaries quick enough maybe the current state would be preferable to a bigger base image.
