### DISCUSSION TITLE
Externals with dependencies

### DISCUSSION THREAD

**Discussion by scheibelp** [spack/spack#21636] [Ideas]
## Summary

External entries in `packages.yaml` currently do not allow specifying dependencies. This may lead to inconsistencies. This discussion proposes how to update `packages.yaml` to record this information. This will also require some edits to the concretizer, but currently the focus is on how to update the configuration schema to record the necessary information.

## The Problem

Right now, if you have a spec DAG like

```
W->Y->Z
```

And your `packages.yaml` file includes an external entry for `Y`, and the concretization chooses this instance of `Y`, then constructed spec DAG would in many cases look like

```
W->Y
```

That is, Spack will truncate all dependencies of chosen externals. Often times this is not a problem, but it could result in consistency issues, for example:

```
  W
 / \
X.  Y
 \./
  Z
```

If the external `Y` was built with a specific instance of `Z`, and Spack builds `X` with a separate instance of `Z`, there may be linking issues.

Generally, this can be avoided if

* (EDIT: clarity) For each package marked as external, all dependencies of that package are also recorded as externals
* Each external package is marked as `buildable: false`

(in that case, packages depending on Z will always use the Z that Y used)

Even with those constraints, if you have multiple instances of Y installed, e.g. `Y+foo` and `Y~foo`, and each has their own instance of Z, then setting `buildable: False` would not be sufficient (I have never seen a report of an issue like this, but it's worth noting that the above suggestion does not guarantee consistency).

## Proposed Solution

Right now `packages.yaml` externals looks like:

```
packages:
  Y:
    externals:
    - spec: Y@1.0
      prefix: /path/to/Y1/
```

If we updated it as follows it would contain sufficient information to construct a DAG:

```
packages:
  Y:
    externals:
    - spec: Y@1.0
      prefix: /path/to/pkg1/
      depends_on: [z1]
  Z:
    externals:
    - spec: Z@1.0
      prefix: /path/to/Z1/
      id: z1
```

in other words, a user can attach an arbitrary (but unique) ID to any external spec entry, and other external specs can claim to depend on it. Specifying ID's and dependencies is not required (in which case Spack behaves as before).

Potential issues:

* ID name collisions (particularly across scopes): Spack should prefer dependencies in the same scope
* Old concretizer runs into more constraint issues: generally externals are chosen as soon as possible, but conditional dependencies can delay this
