### DISCUSSION TITLE
Improving spack develop: develop specs not packages

### DISCUSSION THREAD

**Discussion by haampie** [spack/spack#24966] [Ideas]
`spack develop` is great but it has limitations that block it from being useful for some of my use cases.

(See https://github.com/spack/spack/pull/22087 for an implementation of this idea)

## Current limitations / problems

1. You can't work with both a develop and a non-develop instance of a package in one environment; this makes it difficult to build an environment where you compare your development version with an older release.
2. You can't work with different versions of the same package you are developing
3. Also, there's redundancy in having to repeat the package name in the `develop:[pkg name]:spec:[pkg name]@x.y.z syntax.

## Proposed solution (develop specs, not packages)

1. `develop:pkg:spec` should NOT influence concretization, rather it should act as a filter/selector for specs to be marked as develop after concretization
2. Instead of a key-value map from package to spec, we should just have a list of develop specs
3. If a develop spec does not match a concrete environment spec, we should NOT error out, but simply keep these concrete environment specs as non-develop specs.
4. Drop the currently required version `pkg@x.y.z` in `develop:pkg:spec`, also allow one to drop the version when doing `spack develop --path path/ spec` and `spack develop --no-clone spec`

## Discussion

Another thing I've been thinking about: running `spack develop mypkg` inside an already concretized environment could simply pick the version from a concrete matching spec, since that's likely what the user wants anyways. This is useful for situations where you're developing your own package, but there is some issue with a dependency, so at a later stage you change that spec from standard install to a develop spec too. If `mypkg` occurs multiple times in the environment with different versions, I'm not sure what the behavior should be.

## Example

Instead of writing

```yaml
spack:
  specs: [sirius]
  develop:
    spfft:
      spec: spfft@1.0.4
      path: path/to/sources
```

adopt this syntax:

```yaml
spack:
  specs: [sirius]
  develop:
  - spec: spfft # or spfft@1.0.4
    path: path/to/sources
```

## User experience

1. When `develop[].spec` acts as a selector, it may happen that it doesn't match any concrete spec, and spack install ends up building from downloaded sources. To improve this, we can simply issue a warning after concretization that a particular develop spec was unused.
2. When a concrete spec matches multiple `develop[].spec`'s, we should just map it to the first develop spec entry. For instance:
   ```yaml
   spack:
     specs: [zlib@1.2.11]
     develop:
     - spec: zlib
       path: path/to/zlib
     - spec: zlib@1.2
       path: different/path
   ```
   should concretize to zlib@1.2.11 as develop spec with path `path/to/zlib`. There is no way to find the "best match" because the set of specs with `in` as a comparison operator don't form a total order. The other option would be to error out, but I don't think that's great. In fact in this particular example, there would be a warning that `zlib@1.2` was not used as a develop spec given the previous point.

**Comment by haampie** [comment]
Curious to think what @tgamblin thinks about this. In particular in this commit https://github.com/spack/spack/pull/20423/commits/36ab4cb4309c59fe0962ef51e4e87fc2a4e9fe7b some develop-logic was moved to the fact-collecting-phase before concretization. I kinda get that, but it has no effect when you're developing a dependency that does not occur as a root spec in the environment, like in:

```
spack:
  specs: [sirius]
  develop:
    spfft:
      spec: spfft@1.0.4
      path: path/to/sources
```

(spfft will only occur as a dependency after concretization)

With my suggestion above we can just delete that logic, concretize first, and apply develop-changes afterwards for matching specs.

**Comment by psakievich** [comment]
@haampie how would this work in a `spack.stack`? One thing I'd like to add is to be able to build multiple develop builds of different variants.  The prime example would be `+/~cuda` builds off the same set of changes in a single set of sources.

I like the idea of testing against the current release and the develop changes at the same time.  I see a lot of value in that for my workflow. Out of curiosity, what would that look like in an environment?  If the develop is applied to the spec how do you signal that you want the spec built twice: one with develop, one without?

**Reply by psakievich** [reply]
ah wait you answer my first question in the PR description 😄

**Reply by psakievich** [reply]
just for documentation purposes this is what I want to run (or some other variant)
```yaml
spack:
  include:
  - machine_config.yaml
  - machine_packages.yaml
  - machine_compilers.yaml
  - general_packages.yaml
  - general_config.yaml
  - general_repos.yaml
  concretization: separately
  view: false
  specs:
  - matrix:
    - [nalu-wind+hypre+tioga]
    - [~cuda, +cuda]
  develop:
    nalu-wind:
      - spec: nalu-wind@master+cuda
      - spec: nalu-wind@master~cuda
 ```
 and have them both build out of the same source directory.  From a concretization perspective this should be fine since they will have different hashes and the build directories inside the source directory follow the naming convention `spack-build-[hash]`
