### DISCUSSION TITLE
how to set external slurm env for spack

### DISCUSSION THREAD

**Discussion by davinwei** [spack/spack#26050] [General]
if i install slurm by sudo yum install slurm, how to set external env for spack .

~/.spack/packages.yaml

```yaml
packages:
  slurm:
    paths:
      slurm@20.11.8: /usr
    buildable: False
```

is it right ? thanks

**Comment by ghost** [comment]
Hi! I found the same 'tutorial' online, which also didn't work for me...

First I tried writing my own packages.yaml file (based on [this page](https://spack.readthedocs.io/en/stable/build_settings.html)), which ended up looking like:

```yaml
packages:
  slurm:
    externals:
    - spec: slurm@21.08.8-2
      prefix: ~/slurm_hub/
    buildable: false
```

The slurm hub was an idea proposed by [this page](https://gchp.readthedocs.io/en/13.1.0/supplement/spack.html). This also didn't work for me...

Then I tried the following (which worked):

```console
$ spack external find slurm
==> The following specs have been detected on this system and added to /home/fsmit/.spack/packages.yaml
slurm@21.08.8
```

I then deleted the external that I added manually before and now my packages.yaml looks like:

```yaml
packages:
  slurm:
    externals:
    - spec: slurm@21.08.8
      prefix: /usr
   buildable: false
```

Now when I build something I get the following output:

```console
spack install gromacs@2021.4+mpi+openmp+cuda+plumed %intel ^plumed@2.8 ^cuda@11.4 ^openblas@0.3.12 ^glib@2.72 ^openmpi@4.1.0 +pmi schedulers=slurm target=skylake_avx512
(...)
[+] /home/fsmit/spack/opt/spack/linux-centos7-skylake_avx512/intel-2021.5.0/numactl-2.0.14-rbl5sfo5qsvumisdakg3exsz3gwwfx6b
[+] /usr (external slurm-21.08.8-iysuagutpqxzbd5wmm2erno5iwljz4of)
[+] /home/fsmit/spack/opt/spack/linux-centos7-skylake_avx512/intel-2021.5.0/gsl-2.7-yhtgzxl2kfltk7pwinfxz7ymy7q7rfph
```
