### DISCUSSION TITLE
How to configure system-wide lmod modules?

### DISCUSSION THREAD

**Discussion by luraess** [spack/spack#28176] [Q&A]
Hi,

we are working on a system-wide Spack deploy to expose installed software to all users using hierarchical modules `lmod`. reason using `lmod` and not `tcl` is that `lmod` recognises external packages (in our case, the CUDA install).

We have our Spack install rooted in `/opt/spack` and placed `compilers.yaml` and `packages.yaml` in `/etc/spack` as this location is suggested for system-wide settings.

The`packages.yaml` file contains infos about external package (CUDA):
```yaml
packages:
  cuda:
    externals:
    - spec: "cuda@11.4.152"
      prefix: "/usr/local/cuda-11.4"
    buildable: False
```
which is recognised and exposed as a module.

The issue is when trying to format the `module av` output in order to show custom package names and ideally, "blacklist implicit" packages, i.e., not show packages used to build the actual software we want to finally expose in modules. We added a `modules.yaml` file in `/etc/spack` containing:
```yaml
modules:
  enable::
    - lmod
  lmod:
    core_compilers:
      - 'gcc@9.3.0'
    hierarchy:
      - mpi
      - cuda
    hash_length: 0
    whitelist:
      - gcc
    blacklist:
      - '%gcc@9.3.0'
    projections:
      all: '{name}/{version}'
    all:
      filter:
        environment_blacklist:
          - "C_INCLUDE_PATH"
          - "CPLUS_INCLUDE_PATH"
          - "LIBRARY_PATH"
      environment:
        set:
          '{name}_ROOT': '{prefix}'
```
but any modifications to this file (or even temporarily removing it) does not seem to affect the module rebuild done as:
```sh
spack -d module lmod refresh --delete-tree -y
```
In particular, adding the `blacklist_implicit: true` or explicitly blacklisting packages does not seem to have any effect. Output of `module av` is and remains
```sh
------------------------------------------------------------- /opt/spack/share/spack/lmod/linux-ubuntu20.04-x86_64/Core -------------------------------------------------------------
   berkeley-db/18.1.40-saforst    hwloc/2.6.0-x3qfpaz             libpciaccess/0.16-kdl2y3q            ncurses/6.2-s76nhbf       readline/8.1-a2i6r6b
   bzip2/1.0.8-gk3mz66            julia/1.7.0-u3lrrwa             libsigsegv/2.13-26tzm7q              numactl/2.0.14-oauffcg    sqlite/3.36.0-l6mwa33
   cmake/3.22.1-75fscco           libbsd/0.11.3-2m2xjhv           libxml2/2.9.12-pahfvvc               openmpi/4.1.2-em6kfum     tar/1.34-2thrjwr
   cuda/11.4.152-qzsttjc          libedit/3.1-20210216-cd43bw5    lmod/8.5.27-6xw6aw6                  openssh/8.7p1-dni3qxf     tcl/8.6.11-6peag35
   diffutils/3.8-vtnqdp4          libevent/2.1.12-gvkrk7f         lua-luafilesystem/1_7_0_2-yfs4rig    openssl/1.1.1l-pfqf5i5    unzip/6.0-opxhfrk
   expat/2.4.1-r3qdptx            libffi/3.3-aw6hgeu              lua-luaposix/35.0-txbajf6            perl/5.34.0-pc3phvp       util-linux-uuid/2.36.2-24qrees
   gdbm/1.19-ha5rdny              libiconv/1.16-6cvwkby           lua/5.3.5-6hb4lq6                    pkgconf/1.8.0-izybkdn     xz/5.2.5-74ydxri
   gettext/0.21-a7jjris           libmd/1.0.3-fz6desq             m4/1.4.19-jjj5iyn                    python/3.9.9-26vqr2n      zlib/1.2.11-whj3n7m
```

We are pretty "new" to Spack so any help or suggestions would be warmly welcome, as it may well be that we miss the obvious.

Note that following is in `.profile`:
```sh
# set spack env
SPACK_ROOT="/opt/spack"
source "$SPACK_ROOT/share/spack/setup-env.sh"

# lmod setup
source $(spack location -i lmod)/lmod/lmod/init/bash
export MODULEPATH=$SPACK_ROOT/share/spack/lmod/linux-ubuntu20.04-x86_64/Core
```

Thanks a lot for help 🙂
