### DISCUSSION TITLE
How to get trilinos to use LLVM's clang?

### DISCUSSION THREAD

**Discussion by jrobcary** [spack/spack#28203] [Q&A]
I am trying to build Trilinos using the LLVM compilers, which have openmp built in.  So my compilers section in my environment is

```
  compilers:
  - compiler:
      spec: clang@13.0.0
      paths:
        cc: /usr/local/homebrew/opt/llvm/bin/clang
        cxx: /usr/local/homebrew/opt/llvm/bin/clang++
        f77: /usr/local/homebrew/bin/gfortran
        fc: /usr/local/homebrew/bin/gfortran
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

and I specify that I want to build trilinos@13.2.0+hdf5~mpi+openmp.

This fails with

```
     355    -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
             (found version "4.5")
  >> 356    CMake Error at cmake/tribits/core/package_arch/TribitsGlobalMacros.
            cmake:1834 (message):
     357      Could not find OpenMP, try setting OpenMP_C_FLAGS and OpenMP_CXX_
            FLAGS
```

An examination of the configuration args shows that the CMAKE_CXX_COMPILER is not being set.  How is this set in general?

Thx.

@sethrj
