### DISCUSSION TITLE
PermissionError when setting up spack for multiple users of a group in a root directory

### DISCUSSION THREAD

**Discussion by dmentock** [spack/spack#29885] [Q&A]
I am currently using spack to manage software packages for multiple users on my system. All of those users are part of the group `my_group`. The steps I follow are:

1. Clone the spack repository into the `/opt` directory
2. Modify the `packages.yaml` file as following:
```
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
    providers:
        ...
    permissions:
      read: world
      write: group
      group: my_group
```
3. Set group permissions to rwx for all folders in the spack directory
4. Install a package as a user that is part of `my_group`

For packages that are not compilers, this setup works fine if the write permissions in `packages.yaml` are set to `user` instead of `group`. However, this causes the owner of those directories to always be assigned to the ones installing the package, which isn't always desirable. 
Following the steps I just described, installing a package as the root user in step 3. results in the following error:

`InvalidPermissionsError: Attempting to set suid with group writable`

When trying to install a package as a user who is part of the group, you get a permission error since the permissions for the `spack/opt` folder are not set and the folder doesn't exist yet. Temporarily setting the `spack` folder permissions to group `rwx` causes the same abovementioned `InvalidPermissionsError` to be raised. In my particular case, this error occurs during the `install` phase of the package `ssh`.
How can I set up spack so multiple users of a group can freely install and remove packages?
