### DISCUSSION TITLE
Container build: compiler '%clang@10.0.0' incompatible with 'os=ubuntu20.04'

### DISCUSSION THREAD

**Discussion by climbfuji** [spack/spack#32424] [General]
I am trying to build a container based on ubuntu20.04 using clang as compiler, and that doesn’t go so well. The docker build step fails in spack install with
```
spack.solver.asp.UnsatisfiableSpecError: nco compiler '%clang@10.0.0' incompatible with 'os=ubuntu20.04'
```
which is weird, because I can easily build with clang on a Ubuntu 20.04 machine (just confirmed using an AWS instance). And the spack install step itself doesn’t know anything about being run in a container (I think).

Below is my spack.yaml - any ideas where this restriction comes from? I was looking through the lib directory but couldn’t find anything obvious. Thanks a lot in advance!
```
spack:
  concretizer:
    unify: true
  view: false

  config:
    build_jobs: 2
    connect_timeout: 60

  compilers:
  - compiler:
      spec: clang@10.0.0
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: any
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  # Basic package config from configs/common/packages.yaml
  # Additional package config for container
  packages:
    all:
      providers:
        mpi: [mpich@4.0.2]
        blas: [openblas]
        fftw-api: [fftw]
        gl: [opengl]
        glu: [openglu]
        jpeg: [libjpeg-turbo]
        lapack: [openblas]
        yacc: [bison]
      compiler: [clang@10.0.0]
    gcc:
      buildable: false
      externals:
      - spec: gcc@9.4.0
        prefix: /usr
    git:
      buildable: false
      externals:
      - spec: git@2.25.1~tcltk
        prefix: /usr
    git-lfs:
      buildable: false
      externals:
      - spec: git-lfs@2.9.2
        prefix: /usr
    llvm:
      buildable: false
      externals:
      - spec: llvm@10.0.0 +clang
        prefix: /usr
    qt:
      buildable: false
      externals:
      - spec: qt@5.12.8
        prefix: /usr
      version: [5.15.3]
    wget:
      buildable: false
      externals:
      - spec: wget@1.20.3
        prefix: /usr
      version: [1.21.2]

  specs: [nco@5.0.6%clang]

  container:
    format: docker

    # Sets the base images for the stages where Spack builds the
    # software or where the software gets installed after being built..
    images:
      os: ubuntu:20.04
      spack:
        url: https://github.com/climbfuji/spack
        ref: feature/container_prebuild_docker_and_singularity
        resolve_sha: false

    # Whether or not to strip binaries
    strip: true

    ## Additional system packages that are needed at runtime
    os_packages:
      build:
      - clang-10
      - libclang-10-dev
      - cpp
      - g++
      - gcc
      - gfortran
      - git
      - git-lfs
      - make
      - qt5-default
      - libqt5svg5-dev
      - wget

      final:
      - clang-10
      - libclang-10-dev
      - cpp
      - g++
      - gcc
      - gfortran
      - git
      - git-lfs
      - make
      - qt5-default
      - libqt5svg5-dev
      - wget
      
      # Implicitly included in build step
      - build-essential
      - ca-certificates
      - curl
      - file
      - gnupg2
      - iproute2
      - locales
      - python3
      - python3-pip
      - python3-setuptools
      - unzip
      - vim

    labels:
      app: empty
      mpi: mpich

  include: []
  ```

**Comment by alalazo** [comment]
The error message leaves a good hint:
```yaml
- compiler:
      spec: clang@10.0.0
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: any
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```
as it seems your operating system is called "any"? I assume this was added manually. Do we have docs somewhere says that `any` is a valid configuration there?
