### DISCUSSION TITLE
Environment with a specific compiler

### DISCUSSION THREAD

**Discussion by timocafe** [spack/spack#32508] [Q&A]
Hello,
I am new with spack but not in packet manager world (I used nix during years). I am currently trying to setup a spack environment where I could have packages (previously installed) and the corresponding compiler (equivalent of a nix-shell), where I will able to work.

On my cluster compilers are already managed by module.

I did many many tentative with my spack.yaml but as soons as I activate the env, the compiler is the default one of the machine not the one I specified.

So a basic solution will be to load the module by hand but doing that I will loose all the interest of the packet manager.

The current spack file of my Environment is the following.

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  compilers:
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /nfs/home/tools/gcc/11.2.0/bin/gcc
        cxx: /nfs/home/tools/gcc/11.2.0/bin/g++
        f77: /nfs/home/tools/gcc/11.2.0/bin/gfortran
        fc: /nfs/home/tools/gcc/11.2.0/bin/gfortran
      flags: {}
      operating_system: rocky8
      target: x86_64
      modules: [gcc/11.2.0]
      environment: {}
      extra_rpaths: []
  # add package specs to the `specs` list
  specs: [eigen%gcc@11.2.0]
  packages:
    all:
      compiler: [gcc@11.2.0]
  view: false
  concretizer:
    unify: true
```

I get:

```
[tewart~]$ spack env activate -p test2
[test2] [tewart~]$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
It is not gcc 11.2.0. I am certainly doing a mistake but I do find the solution in the doc, so if somebody could help me, appreciated.

Cheers
