### DISCUSSION TITLE
Module file directory generated for an installed external component have a hash 'attached'

### DISCUSSION THREAD

**Discussion by rickgrubin** [spack/spack#32686] [General]
Creating an environment that utilizes system-provided _compiler / mpi_ modules eventually yields a module subdirectory with the _mpi_ component having a hash in its dir name, e.g. `2018.3-5hsyjcv` rather than `2018.3`. Steps to get there:

Definitions in common files:

_config.yaml_
```
config:
  install_hash_length: 7  <-- desired for installed components
```

_modules.yaml_
```
  default:
    roots:
      lmod: $env/install/modulefiles
    enable::
      - lmod
    arch_folder: false
    lmod:
      exclude:
      [... cmake / curl / git / m4 / python / wget / perl / pkg-config all excluded from module creation ...]
      - intel-mpi
      hash_length: 0
      all:
        autoload: direct
      hierarchy:
        - mpi
```

Definitions in site-specific files:

_packages.yaml_
```
packages:
  all:
    compiler:: [intel@18.0.3]
    providers:
      mpi:: [intel-mpi@2018.3]
  mpi:
    buildable: false
  intel-mpi:
    buildable: false
    externals:
    - spec: intel-mpi@2018.3
      prefix: /opt/intel/compilers_and_libraries_2018.3.222/linux/mpi
      modules:
      - intelmpi/2018.3
      [... cmake / curl / git / m4 / python / wget / perl / pkg-config all defined as externals ...]
[...]
```

Environment:

_spack.yaml_
```
spack:
  repos:
    - $spack/var/spack/repos/[redacted]-bundles
    - $spack/var/spack/repos/[redacted]
  concretizer:
    unify: when_possible
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
  view: false
  include: []
  specs:
    # Virtual environment packages
    - base-env
    # Individual packages that will be built; see the bundles repo
     # - eccodes
     # - hdf5
     # - libpng
     # - netcdf-c
     # - netcdf-fortran
     # - parallel-netcdf
     # - zlib

```

After creating and activating the environment, concretization yields:
```
==> [2022-09-15-14:52:20.180100] build(base-env)
==> [2022-09-15-14:52:20.180354] build(cmake)
==> [2022-09-15-14:52:20.180395] build(curl)
==> [2022-09-15-14:52:20.180426] build(eccodes)
==> [2022-09-15-14:52:20.180452] build(git)
==> [2022-09-15-14:52:20.180476] build(hdf5)
==> [2022-09-15-14:52:20.180503] build(netcdf-c)
==> [2022-09-15-14:52:20.180530] build(netcdf-fortran)
==> [2022-09-15-14:52:20.180556] build(parallel-netcdf)
==> [2022-09-15-14:52:20.180582] build(python)
==> [2022-09-15-14:52:20.180608] build(wget)
==> [2022-09-15-14:52:20.180632] build(zlib)
==> [2022-09-15-14:52:20.180656] build(m4)
==> [2022-09-15-14:52:20.180681] build(perl)
==> [2022-09-15-14:52:20.180706] build(openjpeg)
==> [2022-09-15-14:52:20.180731] build(intel-mpi)
==> [2022-09-15-14:52:20.180757] build(pkg-config)
```

`cmake / curl / git / m4 / python / wget / perl / pkg-config` are all defined in the site-specific _packages.yaml_ file as _externals_, and modules noted where appropriate; this eventually yields:

```
==> [2022-09-15-14:52:23.250145] Concretized base-env
 -   eanh67f  base-env@0.0.1%intel@18.0.3 arch=linux-rhel7-broadwell
 -   tzsj7as      ^cmake@3.17.2%intel@18.0.3~doc+ncurses+ownlibs~qt build_type=Release patches=1c54004,bf695e3,e51119d arch=linux-rhel7-broadwell
 -   eptxunj      ^curl@7.29.0%intel@18.0.3~gssapi~ldap~libidn2~librtmp~libssh2~nghttp2 libs=shared,static tls=openssl arch=linux-rhel7-broadwell
 -   ghj37p4      ^eccodes@2.25.0%intel@18.0.3~aec~fortran~ipo~memfs~netcdf~openmp~png~pthreads~python+shared~tools build_type=RelWithDebInfo definitions=auto jp2k=openjpeg samples=auto arch=linux-rhel7-broadwell
 -   pljiupu          ^openjpeg@2.3.1%intel@18.0.3~codec~ipo build_type=RelWithDebInfo arch=linux-rhel7-broadwell
 -   kq7kgvd      ^git@2.27.1%intel@18.0.3+man+nls+perl+subtree~svn+tcltk arch=linux-rhel7-broadwell
 -   foxfgpz      ^hdf5@1.10.6%intel@18.0.3~cxx+fortran+hl~ipo~java+mpi+shared~szip+threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-rhel7-broadwell
 -   5hsyjcv          ^intel-mpi@2018.3%intel@18.0.3~external-libfabric arch=linux-rhel7-broadwell
 -   n3jw2bm          ^pkg-config@0.27.1%intel@18.0.3+internal_glib patches=49ffcd6 arch=linux-rhel7-broadwell
 -   7r25htk          ^zlib@1.2.12%intel@18.0.3+optimize+pic+shared patches=0d38234 arch=linux-rhel7-broadwell
 -   ds37hzk      ^netcdf-c@4.7.4%intel@18.0.3+dap~fsync~hdf4~jna+mpi+parallel-netcdf+pic+shared patches=2c88dfb arch=linux-rhel7-broadwell
 -   rgj7g54          ^m4@1.4.16%intel@18.0.3+sigsegv arch=linux-rhel7-broadwell
 -   jqwfyl3          ^parallel-netcdf@1.12.2%intel@18.0.3~burstbuffer+cxx+fortran+pic+shared arch=linux-rhel7-broadwell
 -   nufusct              ^perl@5.26.1%intel@18.0.3+cpanm+shared+threads patches=0eac10e,8cf4302 arch=linux-rhel7-broadwell
 -   xzqnlgs      ^netcdf-fortran@4.5.3%intel@18.0.3~doc+pic+shared arch=linux-rhel7-broadwell
 -   sudj5np      ^python@3.9.13%intel@18.0.3+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-rhel7-broadwell
 -   u6z3a25      ^wget@1.14%intel@18.0.3~libpsl~pcre~python+zlib ssl=openssl arch=linux-rhel7-broadwell
```

The environment is created as expected:

```
% spack find
==> In environment /path/to/envs/base
==> Root specs
base-env

==> 17 installed packages
-- linux-rhel7-broadwell / intel@18.0.3 -------------------------
base-env@0.0.1  eccodes@2.25.0  intel-mpi@2018.3  netcdf-fortran@4.5.3    perl@5.26.1        wget@1.14
cmake@3.17.2    git@2.27.1      m4@1.4.16         openjpeg@2.3.1          pkg-config@0.27.1  zlib@1.2.12
curl@7.29.0     hdf5@1.10.6     netcdf-c@4.7.4    parallel-netcdf@1.12.2  python@3.9.13
```

After running `spack module lmod refresh` to create `lua` files, I find (as expected) no module files for the externals noted but `$env/modulefiles/intel-mpi` contains the subdirectory `2018.3-5hsyjcv` for mpi-related module files.

I do not want the _mpi_ version subdirectory to have a hash as part of its name, and would appreciate pointers as to why this occurs, and how to prevent it. Thanks.
