### DISCUSSION TITLE
wgrib2 support netcdf

### DISCUSSION THREAD

**Discussion by aveleda** [spack/spack#32709] [Q&A]
Hi,

I have created an environment to install wgrib2. The spack have installed all dependencies, include netcdf-c and netcdf-fortran, but when you check the configuration the wgrib2 haven't built with netcdf support.
```
Singularity> wgrib2 -config
wgrib2 v0.2.0.8 2/2019  Wesley Ebisuzaki, Reinoud Bokhorst, John Howard, Jaakko Hyvätti, Dusan Jovic, Daniel Lee, Kristian Nilssen, 
Karl Pfeiffer, Pablo Romero, Manfred Schwarb, Gregor Schee, Arlindo da Silva, Niklas Sondell, Sam Trahan, Sergey Varlamov
 
Compiled on 08:31:13 Sep 19 2022

Netcdf package is not installed      <=====#
Jasper 2.0.32 is installed
mysql package is not installed
regex package is installed
tigge package is not installed
IPOLATES ipolates_lib (option 3) is installed with spectral interpolation, default vectors:
UGRD/VGRD VUCSH/VVCSH UFLX/VFLX UGUST/VGUST USTM/VSTM VDFUA/VDFVA MAXUW/MAXVW
    UOGRD/VOGRD UICE/VICE U-GWD/V-GWD USSD/VSSD
Geolocation library status (by search order)
  gctpc geolocation is enabled
  spherical geolocation is enabled
UDF package is not installed
version ftime=2
maximum number of arguments on command line: 10000
maximum number of -match,-not,-if, and -not_if options: 2000
maximum number of -match_fs,-not_fs,-if_fs, and -not_if_fs options: 2000
maximum number of -fgrep, -egrep, -fgrep_v, -egrep_v options: 200
RPN registers: 0..19
memory files: @mem:0, @mem:1 .. @mem:29
stdout buffer length: 30000
default decoding: g2clib emulation
g2clib decoders are not installed
Supported decoding: simple, complex, rle, ieee, png, jpeg2000
user gribtable: (none)
OpenMP: not used
INT_MAX:   2147483647
ULONG_MAX: 18446744073709551615
```

spack.yaml

```
spack:
  specs:
  - openmpi
  - netcdf-fortran
  - wgrib2
  concretizer:
    unify: true
  config:
    install_tree:
      root: /opt/sw
  view: /opt/view
  compilers:
  - compiler:
      spec: gcc@11.2.1
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: rhel9
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

```

How do I fix this problem?

Regards

**Comment by climbfuji** [comment]
Tagging @Hang-Lei-NOAA @edwardhartnett @kgerheiser

You may want to check for differences between the wgrib2 spack recipe in the authoritative repository and https://github.com/noaa-emc/spack (https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/builtin/packages/wgrib2/package.py)

**Reply by aveleda** [reply]
I have tried to add +netcdf4 and -netcdf3 variants,

```
spack:
  specs:
  - openmpi
  - netcdf-fortran
  - wgrib2 +netcdf4-netcdf3
  concretizer:
    unify: true
 ...
```

But I have received the error below.

```
Singularity> spack install
==> Error: trying to set variant "netcdf4" in package "wgrib2", but the package has no such variant [happened during concretization of wgrib2+netcdf4]

```
There isn't any netcdf variants wih **spack info wgrib2**, 

```
Singularity> spack info wgrib2
CMakePackage:   wgrib2

Description:
    The wgrib2 package functionality for interacting with, reading, writing,
    and manipulating GRIB2 files.

Homepage: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2

Preferred version:
    2.0.8-cmake-v6    https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/archive/refs/tags/v2.0.8-cmake-v6.tar.gz
Safe versions:
    2.0.8-cmake-v6    https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/archive/refs/tags/v2.0.8-cmake-v6.tar.gz
Deprecated versions:
    None

Variants:
    Name [Default]                 When    Allowed values          Description
    ===========================    ====    ====================    ==================================

    build_type [RelWithDebInfo]    --      Debug, Release,         CMake build type
                                           RelWithDebInfo,
                                           MinSizeRel
    ipo [off]                      --      on, off                 CMake interprocedural optimization

Build Dependencies:
    cmake  ip2  jasper  libpng  netcdf-c  netcdf-fortran  sp

Link Dependencies:
    ip2  jasper  libpng  netcdf-c  netcdf-fortran  sp

Run Dependencies:
    None

```

Regards,
