### DISCUSSION TITLE
How to define subpackages for subpackages when specifying a particular build?

### DISCUSSION THREAD

**Discussion by dmentock** [spack/spack#33488] [Q&A] [answered]
For example, if I want to install `hdf5 `with `mpich `instead of `openmpi`, and I want set a particular version of `libfabric `as a dependency for `mpich`, how can I specify this build so the `^` sign relates to the subpackages of `mpich`, and not for `hdf5`?

`spack install hdf5 ^mpich@4.0.2 ^libfabric@1.14.0`

**Comment by haampie** [comment, marked as answer]
When you write `^pkg` you mean that `pkg` must be a dependency _somewhere_. There's no difference between `x ^a ^b` and `x ^b ^a`.

If you want explicitly that `mpich` depends on `libfabric`, you have to check the variant that does this, which is `mpich netmod=ofi`, and then setting `^libfabric@1.14.0` will set the version to that.

Alternatively, in an environment I believe you can do this:

```yaml
spack:
  specs:
  - hdf5
  packages:
    mpi:
      require: 'mpich@4.0.2 netmod=ofi'
    libfabric:
      require: '@1.14.0'
```
