### DISCUSSION TITLE
Spack under GitHub Action and stable cache

### DISCUSSION THREAD

**Discussion by uturuncoglu** [spack/spack#34366] [Q&A]
I am trying to fix the target in my spack environment since GitHub Actions uses different runners and spack uses different targets for them. To have consistent cache, fixing target is required. I used following `spack.yaml` file to do that

```
spack:
  concretizer:
    unify: when_possible
  specs:
  - fms@2022.04 target=x86_64_v4
  - esmf@8.4.0b15+parallelio target=x86_64_v4
  - parallelio@2.5.8+pnetcdf target=x86_64_v4
  - zlib@1.2.12 target=x86_64_v4
  packages:
    all:
      # following is required to build same optimized spack for different github action runners
      # spack arch --known-targets command can be used to list known targets
      target: ['x86_64_v4']
      # following fixes compiler version
      compiler: [gcc@11.3.0]
  view: /home/runner/work/noahmp/.spack-ci/view
  config:
    source_cache: /home/runner/work/noahmp/.spack-ci/source_cache
    misc_cache: /home/runner/work/noahmp/.spack-ci/misc_cache
    test_cache: /home/runner/work/noahmp/.spack-ci/test_cache
    install_tree:
      root: /home/runner/work/noahmp/.spack-ci/opt
```

but I am still getting following error sometimes from my action,

```
. $GITHUB_WORKSPACE/spack/share/spack/setup-env.sh
[3](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:3)
  spack --color always -e /home/runner/work/noahmp/noahmp/.github/workflows/spack concretize -f
[4](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:4)
  echo "SPACK_ARCH=$(spack arch)" >> $GITHUB_OUTPUT
[5](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:5)
  shell: /usr/bin/bash -e {0}
[6](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:6)
  env:
[7](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:7)
    INSTALL_DIR: /home/runner/work/noahmp/noahmp/install
[8](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:8)
    ARTIFACTS_RETENTION_PERIOD: 2
[9](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:10)
==> Error: Cannot concretize 'zlib' with multiple targets
[10](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:11)
==> Bootstrapping clingo from pre-built binaries
[11](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:12)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spec.json
[12](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:13)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spack
[13](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:14)
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
[14](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:15)
    Requested 'target=broadwell' and 'target=x86_64_v4'. Consider setting `concretizer:unify` to `when_possible` or `false` to relax the concretizer strictness.
[15](https://github.com/esmf-org/noahmp/actions/runs/3636040749/jobs/6135668177#step:5:16)
Error: Process completed with exit code 1.
```

Any suggestion?

**Comment by climbfuji** [comment]
Just a thought, have you tried `target::` with double colons? That should set `target` to just this value, nothing else.

**Reply by climbfuji** [reply]
In our container builds, I couldn't use a generic `target` with the intel compiler, so I went for something Intel-specific but ancient that probably every processor on this planet understands (`core2`).

**Reply by uturuncoglu** [reply]
@climbfuji I could also try changing target to `core2` rather than using `x86_64_v4`. I was thinking `x86_64_v4` is generic and supported by all the CPUs but maybe I was wrong. This change also requires to install all the spack dependencies (takes more than a hour under action) and cache them again with action. BTW, which `target` need to have `::`?

**Reply by climbfuji** [reply]
I was thinking to try
```
target:: ['x86_64_v4']
```
instead of 
```
target: ['x86_64_v4']
```
but not sure if it helps. Would be easy and quick to try, though. The reason I am suggesting this is that the error reads
```
Requested 'target=broadwell' and 'target=x86_64_v4'. 
```
which suggests to me that the notation
```
target: ['x86_64_v4']
```
is used like a suggestion and appended to what spack determined from the CPU info. Using two colons in principle should override `target` entirely.

**Reply by uturuncoglu** [reply]
@climbfuji using `::` is also not worked. I got following error one of the run

```
Cache not found for input keys: spack-linux-ubuntu22.04-broadwell-5b47a5411c00cdfa1a3939c49a8a8889dd6895e9c9d5b14208622ed61aa9901c, spack-linux-ubuntu22.04-broadwell
```

So, spack is trying to build dependencies for `broadwell` rather than `x86_64_v4` which is defined in the `spack.yaml`. So, maybe I could test to change `x86_64_v4` to `core2 ` and keep looking to the results since it is not reproducible all the time and based on the runner that GitHub assigns to the action.

**Comment by alalazo** [comment]
I would add:
```yaml
spack:
  concretizer:
    targets:
      granularity: generic
      host_compatible: false
    unify: when_possible
```
The issue might be that you have the default `host_compatible: true` and you land on a uarch which is not compatible with `x86_64_v4` (in this case `broadwell`).
