### DISCUSSION TITLE
How to rebuild old spack env?

### DISCUSSION THREAD

**Discussion by mankoff** [spack/spack#35821] [Q&A] [answered]
Hello,

I have a complete and functioning spack env, but I do not have a `~/.spack/linux/compilers.yaml`. I think I have everything else, including
+  `spack/var/spack/environments/${SPENV}/spack.lock` file.
+ 196 packages in `spack/var/spack/cache`

 I'm trying to rebuild/recreate this env 1:1.

I can get fairly far into it if I use what I think is an *incorrect* `compilers.yaml`, namely

```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /usr/bin/gcc-4.8
      cxx: /usr/bin/g++-4.8
      f77: /usr/bin/gfortran-4.8
      fc: /usr/bin/gfortran-4.8
    spec: gcc@4.8
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/icc
      cxx: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc
      f77: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
      fc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
    spec: intel@19.1.2.254
    target: x86_64
```

And I say this is *incorrect* because looking in the existing (old) env, I see

```bash
$ nth opt/spack/linux-sles12-x86_64/
total 65K
drwxr--r--   3 kmankoff 512 Feb 13 11:16 gcc-9.2.0/
drwxrwxr-- 165 eafisch2 32K Mar 26  2020 intel-20.0.166/
```

That is, the old env was compiled with `intel-20.0.166`, but my `compilers.yaml` points to `intel-2020.2.254`. So, I've created what i think is a better `compilers.yaml` based on the folders under `opt/spack/*/`. I'm using this:

```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/icc
      cxx: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/icpc
      f77: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
      fc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
    spec: intel@20.0.166
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gcc
      cxx: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/g++
      f77: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gfortran
      fc: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gfortran
    spec: gcc@9.2.0
    target: x86_64
```

My current steps are then,

```bash
# clone the specific spack branch used for the old env
git clone git@github.com:NASA-GISS/spack.git -b efischer/giss2 $(basename $SPACK)

# don't worry about reported error here for missing "loads"
source $SPACK/var/spack/environments/$SPENV/loads-x

# Donwload some packages
cd $SPACK/var/spack/environments/$SPENV
git clone git@github.com:NASA-GISS/modele-control.git
git clone git@github.com:NASA-GISS/pygiss.git
cd ${SPACK}


### 
### HACK: use cache
###
cp -R /path/to/old/spack/var/spack/cache /path/to/new/spack/var/spack

$SPACK/bin/spack -e $SPENV concretize -f

###
### HACK: Overwrite concretized lockfile with old lock file?
###
cp /path/to/old/spack/var/spack/environments/${SPENV}/spack.lock /path/to/new/spack/var/spack/environments/${SPENV}/spack.lock 

# Install
$SPACK/bin/spack -e $SPENV install
```

As I said, when I use the wrong compiler, I get pretty far in the build process. But when I use (what I think is) the right compiler, it fails at the 2nd package. `pkgconf` installs, and then `ncurses` fails with

```
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j48' 'install'

3 errors found in build log:
     4393    	These are extended terminal capabilities which are compiled
     4394    	using
     4395    		tic -x
     4396    	If you have ncurses 4.2 applications, you should read the INSTALL
     4397    	document, and install the terminfo without the -x option.
     4398    
  >> 4399    tic: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
     4400    ? tic could not build /gpfsm/dnb53/kmankoff/spack/opt/spack/linux-sles12-x86_64/intel-20.0.166/ncurses-6.2-7yza2x7d2vg2iolcfno7gxe6vf6bhwhb/share/terminfo
     4401    Makefile:93: recipe for target 'install.data' failed
  >> 4402    make[1]: *** [install.data] Error 1
     4403    make[1]: Leaving directory '/gpfsm/dnb53/tdirs/login/discover11.14700.kmankoff/spack-stage/spack-stage-uk6g8Q/ncurses-6.2/build_ncurses/misc'
     4404    Makefile:118: recipe for target 'install' failed
  >> 4405    make: *** [install] Error 2

See build log for details:
  /gpfsm/dnb53/kmankoff/spack/var/spack/stage/ncurses-6.2-7yza2x7d2vg2iolcfno7gxe6vf6bhwhb/ncurses-6.2/spack-build.out
```

The only thing I can find when searching for `tic: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory` is to `source /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpivars.sh` but that does not seem to have any impact. 

I'd be grateful for any suggestions.

**Comment by mankoff** [comment]
It may be related to https://github.com/spack/spack/pull/35356 (the only other mention I can find of "spack" and "terminfo") but seems unlikely because that's a new issue and everything I'm using should be old.

**Comment by mankoff** [comment, marked as answer]
From https://mixable.blog/spack-and-intel-parallel-studio-error-while-loading-shared-libraries-libimf-so/ I needed to add an `extra_rpaths` to `compilers.yaml`:

```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: [/gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64/]
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/icc
      cxx: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/icpc
      f77: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
      fc: /gpfsm/dulocal/sles12/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
    spec: intel@20.0.166
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gcc
      cxx: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/g++
      f77: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gfortran
      fc: /gpfsm/dulocal/sles12/other/gcc/9.2.0/bin/gfortran
    spec: gcc@9.2.0
    target: x86_64
```
