### DISCUSSION TITLE
How to show module to users if I customize module.yaml with `arch_folder: false`

### DISCUSSION THREAD

**Discussion by luweizheng** [spack/spack#37585] [Q&A]
Hi,

I customize `module.yaml`:

```
modules:
  default:
    arch_folder: false
    tcl:
      hash_length: 0
      projections:
        all: '{name}/{version}-{compiler.name}-{hash:4}'
```

Here is the problem:

If I enable `arch_folder`, `module avail` will show the installed modulefiles in `spack/share/spack/modules/linux-centos7-haswell`. The file tree is like:

```
spack/share/spack/modules -- linux-centos7-haswell
                    |- linux-centos7-icelake
```

If I disable `arch_folder`, modulefiles will be installed at `spack/share/spack/modules` like this:

```
spack/share/spack/modules -- gcc
                    |- zlib
                    |-...
```

 However, when I use `module avail`, `module` does not show the modulefiles (gcc or zlib in this example) in `spack/share/spack/modules`.

I disable `arch_folder` because most users do not have any knowledge about micro-architectures and I concern that too much software on different `arch_folder` may make users confused.

I have different micro-architectures on my site, including haswell, cascadelake, and sapphire rapids. Currently I am planning to use a higher version of GCC to compile all the software. Higher version of GCC may be compatible with older processors like haswell.

Any suggestions on how to set the modulefiles? Or if `arch_folder` is really necessary?
