### DISCUSSION TITLE
openssh is being built despite openssh being an external with buildable: false

### DISCUSSION THREAD

**Discussion by pbisbal1** [spack/spack#40620] [Q&A]
I have the following in my ~/.spack/packages.yaml file: 

```
  openssh:
    externals:
    - spec: openssh@8.7p1
      prefix: /usr
    buildable: false
```

But when install applications, openssh@8.7 is still being built as a dependency for the different compilers I have installed (gcc@11.3.1 the core_compiler provided by OS)

```
# spack find openssh
-- linux-rhel9-zen2 / aocc@4.1.0 --------------------------------
openssh@8.7p1

-- linux-rhel9-zen2 / gcc@13.2.0 --------------------------------
openssh@8.7p1

-- linux-rhel9-zen2 / oneapi@2023.2.0 ---------------------------
openssh@8.7p1
```

I'm new to Spack administation... Does "buildable" only apply to a specific compiler? I figured it wouldn't build it for any compiler in this case. 

Thanks,
Prentice

**Comment by pbisbal1** [comment]
Additional question - is this a scoping issue? When I ran 'spack exernal find', I didn't provide a scope, so it updated ~/.spack/packages.yaml instead of spack/etc/spack/packages.yaml, so externals are only defined in my ~/.spack/packages.yaml file.

**Comment by legooolas** [comment]
This is from long ago but I found this because I was trying to do the very same thing!  I have this in my `~/.spack/packages.yaml` file and it works OK:

```
packages:
  openssh:
    externals:
    - spec: openssh@9.6p1
      prefix: /usr
```

..so you may just be missing the `packages:` part.  Or this may have changed in the past 2 years  :laughing:
