### DISCUSSION TITLE
Having trouble getting spack to use openjdk instead of jdk

### DISCUSSION THREAD

**Discussion by pbisbal1** [spack/spack#40960] [Q&A]
Hi. I'm having issues insisting that packages use openjdk as their java provider instead of jdk (for licensing reasons). In my packages.yaml, I have the following:

```
packages:
  all:
    providers:
      java: [openjdk]
```

I'm currently installing something that relies on icedtea, which relies on having icedtea or a jdk already installed on your system. I have openjdk installed as part of the OS and have it defined as an external:

```
  openjdk:
    externals:
    - spec: openjdk@11.0.21.0.9
      prefix: /usr
```
But when I do spack spec icedtea, I see that jdk is one of the dependencies, instead of openjdk:

`  ^jdk@14_36%gcc@13.2.0 build_system=generic arch=linux-rhel9-zen2`

I tried specifying openjdk as a dependency on icedtea, but that fails:
```
# spack spec icedtea ^openjdk
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "icedtea"
```

I believe this is because this is leading to a loop in the dependencies, preventing the concretizer from creating a DAG.What am I doing wrong? How do I get around this problem?
