### DISCUSSION TITLE
lmod modules: how to hide implicits

### DISCUSSION THREAD

**Discussion by cr-wilson** [spack/spack#42910] [Q&A]
Hello. 

I'm trying to use lmod environment variables to load packages built via spack. I'm trying to follow the instructions in https://spack.readthedocs.io/en/latest/module_file_support.html#autoloading-and-hiding-dependencies 

``` 
    # Default configurations if lmod is enabled
    lmod:
      hide_implicits: true
      all:
        autoload: direct
      hierarchy:
        - mpi
```

however when running module avail it still shows everything that spack has built rather than just the explicitly installed packages. Have I missed something?

Environment is RHEL8.6 and Modules based on Lua: Version 8.7.19
