### DISCUSSION TITLE
Use spack to load a manualy compiled program that doesn't exist in repo

### DISCUSSION THREAD

**Discussion by Rehvaro** [spack/spack#46887] [Q&A]
Hello,

On our system most of the users will manage and compile their one software using spack.

But there will be exceptions. As admin-sys of the cluster we will have to compile some software that doesn't exists in the spack repo. 

Unfortunately we will not have the time to make and maintain a clean spack package for each of this software that we compile for them.

We could use environment-module for this but we would like to keep only one command to learn for our users. 
So we were wondering if there was a solution to tell spack that a program it doesn't know, named 'something', is available in a specific version in a specific directory and that it can load it with some env variables.

I have searched the documentation without success. And even tried to add a program like this to the packages.yaml like this : 

```
packages:
  something:
    buildable: false
    externals:
    - prefix: /apps/2025/something
      spec: blabla@4.0.
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /apps/2025/something/lib
            PATH: /apps/2025/something/bin
```

But as Spack doesn't know any 'something' package, it refuse to use it.

Is it possible to do something like this ?
If not, would you have any recommendation ?

Thank you
