### DISCUSSION TITLE
Best practice for using PBSPro with Spack

### DISCUSSION THREAD

**Discussion by dithwick** [spack/spack#49461] [Q&A]
Hi,

I'm trying to use PBS Pro with Spack so I can build OpenMPI with PBS/tm scheduler support. I think I've got it working but I wanted to check if I've done this the right way as PBSPro doesn't exist as a package in Spack and I couldn't get it to use PBSPro as a PBS provider until I created a basic PBSPro package. 

I've got the following in my packages.yaml file:

```
packages:
    openmpi:
        variants: schedulers=tm
    pbspro:
        externals:
        - spec: pbspro@2024.1.1
          prefix: /opt/pbs
        buildable: False
    all:
        compiler:
        - gcc@13.3.0
        providers:
            pbs: [pbspro, openpbs, torque]
            mpi: [openmpi, mpich]
```

I then had to use `spack create pbspro` to create a basic template package, adding the following in the 

```
    provides("pbs")
```

When I then built OpenMPI with 

```
spack install openmpi
```

It seemed to build OpenMPI correctly with 

```
--with-tm=/opt/pbs
```

showing on the configure line from ompi_info.

So my question is then, is this the correct way (best practice) of adding PBSPro to Spack? Or is the better way that doesn't involve adding a sort of dummy package (I've only ever used spack with builtin packages)?

Many thanks for the help.
