### DISCUSSION TITLE
Hip support update

### DISCUSSION THREAD

**Discussion by adrienbernede** [spack/spack#49820] [Ideas]
Here is a list of key points from our experience working with HIP on RADIUSS software stack at LLNL.

# hipcc
Hipcc is a wrapper, it builds all the source with a hip compatible compiler.
It can be justified as an early helper tool, but with maturity of the rocm software stack, we think that users are supposed to move to amdclang.

Note: there is a comparison page here but no recommendation.
https://rocm.docs.amd.com/en/docs-6.1.5/reference/rocmcc.html

# mixing compilers
Our opinion is that it does not make sense to mix compilers as it is only opening the door to problems.
As such, a spec like `package@version +rocm %gcc` is only asking for troubles.

# defining targets
When using amdgpu, some projects (lbann, raja) have found (at some point in time) that setting the target required several similar variables to be set:
In addition to `CMAKE_HIP_ARCHITECTURE`, they would also set `GPU_TARGET` as well as `AMDGPU_TARGET`.
Discussing about which should be set and why is recurring and still open: it is safer to keep all three, but we forgot exactly why, and today it is hard to prove anything…
https://github.com/spack/spack/pull/49635#discussion_r2012430917

# dropping support of older versions
The question of backward compatibility should also be officially answered:
The rocm stack, because it is recent, has been changing rapidly with many versions.

As a reference, LLNL recently removed anything older than 5.7.1 from all the machines.
Officially dropping support for older version would help: some issues we’ve had in the past
may be solved for good as long as we use a recent version.

# hip compiler location.
In my work environment, I noticed at least three different llvm-amdgpu installation layouts:

spack installation
LLNL LC “native” installation (/opt/rocm-6.3.1)
LLNL LC “wrapper” installation (/usr/tce/packages/rocmcc/rocmcc-6.3.1-magic)
As commented in CachedCMakePackage, when looking for “clang++”, the location varies, and <root>/bin is not always enough.

However, be it done artificially or not, _in practice_ amdclang++ is found in <root>/bin in all three cases.
Actually, a better statement on the situation can be found here:
https://spackpm.slack.com/archives/C01UZDL35C4/p1743096176747609?thread_ts=1743069416.276089&cid=C01UZDL35C4

# value of ROCM_PATH:
In LLNL LC installations, it’s is pretty straightforward since everything ends up under <path>/rocm-<version>
Not with spack, so what do we do ?
What should we do to define an external installation of rocm in spack packages.yaml ? currently, (see bellow) we set llvm-amdgpu prefix to <path>/rocm-<version>/llvm, but that’s inconsistent with spack installation layout.

# compiler coherency across the stack
Building with the rocm compilers is not just about a compiler, it’s about a software stack that is fairly large.
It is important to keep the stack coherent, which we do by describing it the following way in the packages.yaml:

```yaml
  hip:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: hip@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1/hip
    - spec: hip@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: hip@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: hip@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  hipsparse:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: hipsparse@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: hipsparse@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: hipsparse@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: hipsparse@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  hipblas:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: hipblas@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: hipblas@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: hipblas@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: hipblas@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  hipsolver:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: hipsolver@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: hipsolver@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: hipsolver@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: hipsolver@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  llvm-amdgpu:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: llvm-amdgpu@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1/llvm
    - spec: llvm-amdgpu@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2/llvm
    - spec: llvm-amdgpu@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4/llvm
    - spec: llvm-amdgpu@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1/llvm
  hsa-rocr-dev:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: hsa-rocr-dev@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: hsa-rocr-dev@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: hsa-rocr-dev@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: hsa-rocr-dev@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocminfo:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocminfo@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocminfo@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocminfo@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocminfo@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocm-device-libs:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocm-device-libs@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocm-device-libs@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocm-device-libs@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocm-device-libs@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocprim:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocprim@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocprim@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocprim@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocprim@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocthrust:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocthrust@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocthrust@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocthrust@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocthrust@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocsparse:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocsparse@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocsparse@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocsparse@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocsparse@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocrand:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocrand@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocrand@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocrand@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocrand@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocblas:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocblas@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocblas@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocblas@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocblas@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocsolver:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocsolver@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocsolver@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocsolver@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocsolver@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
  rocm-core:
    version: [5.7.1, 6.1.2, 6.2.4, 6.3.1]
    buildable: false
    externals:
    - spec: rocm-core@5.7.1%rocmcc@5.7.1
      prefix: /opt/rocm-5.7.1
    - spec: rocm-core@6.1.2%rocmcc@6.1.2
      prefix: /opt/rocm-6.1.2
    - spec: rocm-core@6.2.4%rocmcc@6.2.4
      prefix: /opt/rocm-6.2.4
    - spec: rocm-core@6.3.1%rocmcc@6.3.1
      prefix: /opt/rocm-6.3.1
```

That’s a lot… and that’s not enough:
With this, we ensure that running `spack install umpire@develop +rocm %rocmcc@6.1.2` will result in a software stack only involving 6.1.2 software and compilers.
However, this is not enough when running `spack install umpire@develop +rocm %gcc` where spack will “feel” free to release the constraint on the compiler and will end up mixing toolchains…

# Final notes
Having rocmcc / amdclang as a "real compiler" in spack (and hip a variation of c,cxx,fortran,(cuda?)), combined with the proposed "toolchain feature" (https://github.com/spack/spack/issues/49732) looks very promising.
