### ISSUE TITLE
RegCM recipe does not list mpi as a 'run' dependency

### ISSUE THREAD

**Issue by willfurnass** [spack/spack#10163]
I built RegCM with OpenMPI then loaded RegCM: 

```sh
spack load regcm
```

I then expected `mpirun` to be on my `$PATH` but it wasn't.

I think this is because within [the RegCM recipe](var/spack/repos/builtin/packages/regcm/package.py)) `mpi` is only listed as a `build` and `link` dependency.  

Spack version: 9a7a532084356a473a282b0443da40f05961327f

**Comment by healther** [comment]
you should do `spack load -r regcm`, spack, at least by default, does not deal with dependencies. I'm not sure how this will work out in this case here though.

**Comment by bebosudo** [comment]
Hi, I'm the author of the regcm spack package.
I've found your issue only now, and I'm going to update the package soon.

**Comment by bebosudo** [comment]
Seems spack doesn't use the 'run' type of dependency at all, see Adam's comment: https://github.com/spack/spack/pull/10863#issuecomment-472236545 and discussion #8639.

The best thing to do for the moment is to set your `modules.yaml` to:
```yaml
modules:
  tcl:
    all:
      # autoload: 'all' will automatically load ALL the dependencies;
      # 'direct' only the children; default is 'none'.
      autoload: 'all'
```
