### ISSUE TITLE
theta: wrong compiler version used for some packages in build.

### ISSUE THREAD

**Issue by balay** [spack/spack#10184]
On ALCF/Theta - I'm using the default compiler - and specifying it via packages.yaml
```
  all:
    providers:
      mpi: [mpich]
      blas: [intel-mkl]
      lapack: [intel-mkl]
    compiler: [intel@18.0.0.128]
```
With some packages - this specified compiler gets used:

```
balay@thetalogin6:~/spack> spack build_env mfem bash
balay@thetalogin6:~/spack> which icc
/gpfs/mira-home/balay/spack/lib/spack/env/intel/icc
balay@thetalogin6:~/spack> icc --version
icc (ICC) 18.0.0 20170811
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
```
But with other packages - a different version of compiler gets used

```
balay@thetalogin6:~/spack> spack build_env hypre bash
balay@thetalogin6:~/spack> which icc
/gpfs/mira-home/balay/spack/lib/spack/env/intel/icc
balay@thetalogin6:~/spack> icc --version
icc (ICC) 18.0.2 20180210
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
```
The compilers are specified in compilers.yaml via modules. 

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - intel/18.0.0.128
    operating_system: cnl6
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@18.0.0.128
    target: any
```
And this module should set the PATH to:

```
balay@thetalogin6:~/spack> which icc
/opt/intel/compilers_and_libraries_2018.0.128/linux/bin/intel64/icc
```

And I noticed for some reason - /opt/intel/bin gets added to PATH in the second case - which I think is the reason for the wrong compiler being used.

```
balay@thetalogin6:~/spack> echo $PATH
/gpfs/mira-home/balay/spack/lib/spack/env/cray:/gpfs/mira-home/balay/spack/lib/spack/env:/gpfs/mira-home/balay/spack/lib/spack/env/case-insensitive:/gpfs/mira-home/balay/spack/lib/spack/env/intel:/opt/intel/bin:/opt/intel/bin:/opt/cray/pe/mpt/7.7.3/gni/bin:/opt/intel/compilers_and_libraries_2018.0.128/linux/bin/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/bin:/opt/intel/debugger_2017/gdb/intel64_mic/bin:/opt/cray/pe/cce/8.7.6/binutils/x86_64/x86_64-pc-linux-gnu/bin:/opt/cray/pe/cce/8.7.6/binutils/cross/x86_64-aarch64/aarch64-linux-gnu/../bin:/opt/cray/pe/cce/8.7.6/utils/x86_64/bin:/opt/cray/pe/perftools/7.0.4/bin:/opt/cray/pe/papi/5.6.0.4/bin:/opt/cray/rca/2.2.18-6.0.6.0_19.14__g2aa4f39.ari/bin:/opt/cray/alps/6.6.1-6.0.6.1_4.1__ga6396bb.ari/sbin:/opt/cray/job/2.2.3-6.0.6.0_9.47__g6c4e934.ari/bin:/opt/cray/pe/craype/2.5.15/bin:/home/balay/spack/bin:/opt/xalt/bin:/soft/buildtools/trackdeps/bin:/opt/modulefiles/nompirun/bin:/opt/cray/pe/modules/3.2.11.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/dbhome/db2cat/sqllib/bin:/dbhome/db2cat/sqllib/adm:/dbhome/db2cat/sqllib/misc:/usr/lib/mit/bin:/usr/lib/mit/sbin:/home/balay/bin:/opt/cray/pe/bin
balay@thetalogin6:~/spack> /opt/intel/bin/icc --version
icc (ICC) 18.0.2 20180210
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.

````

Any idea how I can debug this? Or prevert spack from picking up /opt/intel/bin/icc?
