### ISSUE TITLE
Can't override environment blacklist in modules.yaml

### ISSUE THREAD

**Issue by alalazo** [spack/spack#10245]
The usual overriding syntax doesn't work for the `environment_blacklist` property of `modules.yaml`.

### Steps to reproduce the issue
The error can be reproduced using this simple configuration file for `modules.yaml`:
```yaml
modules:
  tcl:
    all:
      filter:
        environment_blacklist: ['CPATH', 'LIBRARY_PATH', 'LD_LIBRARY_PATH']
    zlib:
      filter:
        environment_blacklist:: ['CPATH', 'LIBRARY_PATH']
```
and installing `libszip` and `zlib`:
```console
$ spack install libszip
...

$ spack install zlib
...
```

### Error Message

There's no error message, but one would expect to see a module file for `zlib` with `LD_LIBRARY_PATH` set. What happens instead is that the generic settings are used and the property is not overridden. The generated module file looks like:
```tcl
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-01-03 13:18:21.684554
##
## zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 /ivqu252
##


module-whatis "A free, general-purpose, legally unencumbered lossless data-compression library."

proc ModulesHelp { } {
puts stderr "A free, general-purpose, legally unencumbered lossless data-compression"
puts stderr "library."
}


prepend-path MANPATH "/home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-8.2.0/zlib-1.2.11-ivqu252fvh7r5iar6zwx4fmeoxiykln7/share/man"
prepend-path PKG_CONFIG_PATH "/home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-8.2.0/zlib-1.2.11-ivqu252fvh7r5iar6zwx4fmeoxiykln7/lib/pkgconfig"
prepend-path CMAKE_PREFIX_PATH "/home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-8.2.0/zlib-1.2.11-ivqu252fvh7r5iar6zwx4fmeoxiykln7/"
```

### Information on your system

This bug seems not to be tied to a particular system.

**Comment by alalazo** [comment]
@hartzell @adamjstewart

**Comment by hartzell** [comment]
I think that it's probably something like the second, since this example that does not involve the `::` syntax also fails to override the *all* setting.

```yaml
    # [...]
    all:
      suffixes:
        '+jit': jit
        '^python@2.7': 'py2.7'
        '^python@3.6': 'py3.6'
      filter:
        environment_blacklist: ['CPATH', 'CMAKE_PREFIX_PATH', 'LIBRARY_PATH', 'LD_LIBRARY_PATH']
    # WE DO NOT SET PACKAGE ROOT, it upsets GCC
    ^python:
      autoload:  'direct'
      # environment_whiteless doesn't exist (did it ever?)
      # filter:
      #   environment_whitelist: ['LD_LIBRARY_PATH']
      # This doesn't work, though alalazo thinks it should
      # filter:
      #   # NOTE THE :: (Spack extention to yaml...)
      #   environment_blacklist:: ['CPATH', 'LIBRARY_PATH']
      # This doesn't work, POODLE gets set, but LD_LIBRARY_PATH does not.
      # Seems like `environment_blacklist` is winning.
      environment:
        prepend_path:
          LD_LIBRARY_PATH: '$prefix/lib'
          POODLE: '${PREFIX}/lib'
```
