### ISSUE TITLE
Using spack.yaml for building a fully standalone environment (including compiler)

### ISSUE THREAD

**Issue by HGab** [spack/spack#10267]
I want to use spack environments, based on a spack.yaml file in order to build a fully standalone environment, including the compiler deployement.

At the moment, I am using a simple spack.yaml file containing:

```
spack:
  specs:
  - intel%gcc@4.8.5
  - zlib%intel
```

While using `` spack install`` with this spack.yaml file, there is no issue while installing the intel compiler, but once it's installed, the zlib installation gives the following error:
```
==> Concretizing zlib%intel
==> Error: No compilers with spec intel found
```
which makes sense as the intel compiler is not defined as a compiler, but I still would like to use it without having to explicitly define the paths where it's installed.

That's an issue as it does not fit my requirement which is to deploy a full environment in a single spack environment, using the spack install command only once.

### Steps to reproduce the issue
In a new directory, define your spack.yaml as follows:
```
spack:
  # add package specs to the `specs` list
  specs:
  - intel%gcc@4.8.5
  - zlib%intel
```
run
```
spack install
```

### Error Message
`==> Concretizing zlib%intel`

`==> Error: No compilers with spec intel found`

### Information on your system
Cluster based on Linux (RedHat 7.5)

### Solution proposed
It's not a PR but I still would like to propose a first solution for this issue.

Adding a ``compiler:`` section in spack.yaml fixes the issue:

```
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel7
      paths:
        cc: <PATH_TO_SPACK_INSTALL>/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/icc
        cxx: <PATH_TO_SPACK_INSTALL>/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/icpc
        f77: <PATH_TO_SPACK_INSTALL>/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/ifort
        fc: <PATH_TO_SPACK_INSTALL>/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/ifort
      spec: intel@19.0.1.144
      target: x86_64
```

As I wanted to be as generic as possible (to enable my colleagues to re-use my environment), I wanted to define <PATH_TO_SPACK_INSTALL> as an environment variable defined in my project's environment, let's say:
``$SPACK_INSTALL_TREE``

However, cc, cxx, fc and f77 attributes do not evaluate env variables. So I decided to apply the following patch to: 
``spack/lib/spack/spack/build_environment.py``

```
    if compiler.cc:
-        env.set('SPACK_CC', compiler.cc)
+        env.set('SPACK_CC', os.path.expandvars(compiler.cc))
        env.set('CC', os.path.join(link_dir, compiler.link_paths['cc']))
    if compiler.cxx:
-        env.set('SPACK_CXX', compiler.cxx)
+        env.set('SPACK_CXX', os.path.expandvars(compiler.cxx))
        env.set('CXX', os.path.join(link_dir, compiler.link_paths['cxx']))
    if compiler.f77:
-        env.set('SPACK_F77', compiler.f77)
+        env.set('SPACK_F77', os.path.expandvars(compiler.f77))
        env.set('F77', os.path.join(link_dir, compiler.link_paths['f77']))
    if compiler.fc:
-        env.set('SPACK_FC',  compiler.fc)
+        env.set('SPACK_FC',  os.path.expandvars(compiler.fc))
        env.set('FC', os.path.join(link_dir, compiler.link_paths['fc']))
```
Enabling env variables expansion in compiler paths enables multiple users to have a fully standalone version of the environment with the following spack.yaml:
```
spack:
  # add package specs to the `specs` list
  specs:
  - intel%gcc@4.8.5
  - zlib%intel

  config:
    install_tree: $SPACK_INSTALL_TREE

  compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel7
      paths:
        cc: $SPACK_INSTALL_TREE/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/icc
        cxx: $SPACK_INSTALL_TREE/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/icpc
        f77: $SPACK_INSTALL_TREE/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/ifort
        fc: $SPACK_INSTALL_TREE/gcc-4.8.5/intel-19.0.1-vu2n/compilers_and_libraries_2019.1.144/linux/bin/intel64/ifort
      spec: intel@19.0.1.144
      target: x86_64
```

This can be simply used by setting a SPACK_INSTALL_TREE environment variable in a project environment.

An other solution could be that you enable cc,fc,.. to be relative, based on config.install_tree.
Or, we could also imagine a variable, based also on config.install_tree, which could be used in config files (such as $spack).
