### ISSUE TITLE
No Externals Actually Found

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10329]
Setting `OpenSSL` to `buildable=False` does not work.

### Steps to reproduce the issue

1. Set the following in your `packages.py`:
```
    # Recommended for security reasons
    # Do not install OpenSSL as non-root user.
    openssl:
        paths:
            openssl@1.0.1h: /usr
        version: [1.0.1h]
        buildable: False
```
This is fully correct on a Mac (try `which openssl`).

2. Try `spack spec python@3.7`.  I get the error in `concretize.py` line 100:
```
==> Error: The spec 'openssl' is configured as not buildable, and no matching external installs were found
```

Looking further, I added the following debugging to `concretize.py`:
```
        # For each candidate package, if it has externals, add those
        # to the usable list.  if it's not buildable, then *only* add
        # the externals.
        usable = []
        for cspec in candidates:
            if is_spec_buildable(cspec):
                usable.append(cspec)

            externals = spec_externals(cspec)
            print('eeeeeeeeeeexternals', cspec, externals)
            for ext in externals:
                if ext.satisfies(spec):
                    usable.append(ext)
```
From this, I learned that the `externals` variable never seems to get populated (at least not on my system):
```
Input spec
--------------------------------
python@3.7

Concretized
--------------------------------
eeeeeeeeeeexternals python@3.7 ^bzip2 ^diffutils ^gdbm ^libffi ^ncurses ^openssl@1.0.2: ^perl@5.14.0: ^pkgconfig ^readline ^sqlite ^zlib []
eeeeeeeeeeexternals bzip2 ^diffutils []
eeeeeeeeeeexternals diffutils []
eeeeeeeeeeexternals libffi []
eeeeeeeeeeexternals ncurses ^pkgconfig []
eeeeeeeeeeexternals pkg-config []
eeeeeeeeeeexternals pkgconf []
eeeeeeeeeeexternals python@3.7 ^bzip2 ^diffutils ^gdbm ^libffi ^ncurses ^openssl@1.0.2: ^perl@5.14.0: ^pkgconf ^readline ^sqlite ^zlib []
eeeeeeeeeeexternals bzip2 ^diffutils []
eeeeeeeeeeexternals diffutils []
eeeeeeeeeeexternals libffi []
eeeeeeeeeeexternals ncurses ^pkgconf []
eeeeeeeeeeexternals pkgconf []
eeeeeeeeeeexternals openssl@1.0.2: ^gdbm ^ncurses ^perl@5.14.0: ^pkgconf ^readline ^zlib []
==> Error: The spec 'openssl' is configured as not buildable, and no matching external installs were found
```
### Information on your system

macOS 10.13.6

**Comment by citibeth** [comment]
Thanks of course!

**Comment by citibeth** [comment]
The answer to the original problem is found here:

https://devguide.python.org/setup/

> As of OS X 10.11, Apple no longer provides header files for the deprecated system version of OpenSSL

Moral of the story... don't try to use the system OpenSSL in your `packages.yaml` file for macOS.

**Comment by jcbowden** [comment]
I had a similar problem on Linux (Debian 10) and it was fixed by changing of the format of the library version: 
On my system:
```
$openssl --version
OpenSSL 1.1.1d  10 Sep 2019

# package.yaml file should then contain (note: no 'd' specified):
   openssl:
      externals:
      - spec: openssl@1.1.1
        prefix: /usr/lib/x86_64-linux-gnu
      buildable: False
```
