### ISSUE TITLE
Installation issue: openmpi-3.1.3

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#10384]
Using `develop` from today, I am unable to install this spec `openmpi@3.1.3%clang@6.0.0-1ubuntu2` due to an error during the configuration phase of `openmpi`.

### Steps to reproduce the issue

```console
$ spack install openmpi@3.1.3%clang@6.0.0-1ubuntu2 
...
==> Building openmpi [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scott/spack/var/spack/stage/openmpi-3.1.3-u62a52wbetk62lgimhe4x77vqlp6ymk6/openmpi-3.1.3/configure' '--prefix=/scott/spack/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0-1ubuntu2/openmpi-3.1.3-u62a52wbetk62lgimhe4x77vqlp6ymk6' '--enable-shared' '--with-wrapper-ldflags=' '--enable-static' '--without-pmi' '--enable-mpi-cxx' '--with-zlib=/scott/spack/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0-1ubuntu2/zlib-1.2.11-37pzrwcovpu5wxaldr5l4eg6i255dv4h' '--without-psm' '--without-libfabric' '--without-ucx' '--without-mxm' '--without-verbs' '--without-psm2' '--without-alps' '--without-lsf' '--without-sge' '--without-slurm' '--without-tm' '--without-loadleveler' '--disable-memchecker' '--with-hwloc=/scott/spack/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0-1ubuntu2/hwloc-1.11.11-lsiketic23rfmmwxslyzv743s6nhj7pj' '--disable-java' '--disable-mpi-java' '--without-cuda' '--enable-cxx-exceptions'

1 error found in build log:
     376    checking if C and Fortran are link compatible... yes
     377    checking to see if Fortran compiler likes the C++ exception flags... yes
     378    checking to see if mpifort compiler needs additional linker flags... none
     379    checking if Fortran compiler supports CHARACTER... yes
     380    checking size of Fortran CHARACTER... configure: WARNING: Could not determine size of CHARACTER
     381    configure: WARNING: See config.log for details
  >> 382    configure: error: Cannot continue

See build log for details:
  /scott/spack/var/spack/stage/openmpi-3.1.3-u62a52wbetk62lgimhe4x77vqlp6ymk6/openmpi-3.1.3/spack-build.out
```

In case it's useful here's the full spec which spack tried to install:

```console
[ubuntu] spack: spack spec openmpi@3.1.3%clang@6.0.0-1ubuntu2
Input spec
--------------------------------
openmpi@3.1.3%clang@6.0.0-1ubuntu2

Concretized
--------------------------------
openmpi@3.1.3%clang@6.0.0-1ubuntu2~cuda+cxx_exceptions fabrics=auto ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt arch=linux-ubuntu18.04-x86_64 
    ^hwloc@1.11.11%clang@6.0.0-1ubuntu2~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-ubuntu18.04-x86_64 
        ^libpciaccess@0.13.5%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^libtool@2.4.6%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
                ^m4@1.4.18%clang@6.0.0-1ubuntu2 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-x86_64 
                    ^libsigsegv@2.11%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^pkgconf@1.5.4%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^util-macros@1.19.1%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
        ^libxml2@2.9.8%clang@6.0.0-1ubuntu2~python arch=linux-ubuntu18.04-x86_64 
            ^libiconv@1.15%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^xz@5.2.4%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^zlib@1.2.11%clang@6.0.0-1ubuntu2+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 
        ^numactl@2.0.12%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
            ^autoconf@2.69%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
                ^perl@5.26.2%clang@6.0.0-1ubuntu2+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64 
                    ^gdbm@1.18.1%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
                        ^readline@7.0%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64 
                            ^ncurses@6.1%clang@6.0.0-1ubuntu2~symlinks~termlib arch=linux-ubuntu18.04-x86_64 
            ^automake@1.16.1%clang@6.0.0-1ubuntu2 arch=linux-ubuntu18.04-x86_64
```

### Platform and user environment

```commandline
[ubuntu] spack: uname -a
Linux 02ae2cdde2be 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[ubuntu] spack: cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
``` 

I don't have a `packages.yaml`, but here's my `compilers.yaml`:

```commandline
[ubuntu] spack: cat ~/.spack/linux/compilers.yaml 
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: clang@6.0.0-1ubuntu2
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /usr/bin/gcc-5
      cxx: /usr/bin/g++-5
      f77: /usr/bin/gfortran-5
      fc: /usr/bin/gfortran-5
    spec: gcc@5.5.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@7.3.0
    target: x86_64
```

### Additional information

Having spack parse the `config.log` turned up a bunch of warnings and errors, so I'm not sure if this one is the culprit or not:

```console
     10286    configure:39917: $? = 0
     10287    configure:39927: /scott/spack/lib/spack/env/clang/gfortran  -fexceptions  conftestf.f90 conftest.o -o conftest   -L/scott/spack/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0-1ubuntu2/zlib-1.2.11-37pzrwcovpu5wxaldr5l4eg6i255
              dv4h/lib -fexceptions  -lz
     10288    /usr/bin/ld: conftest.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
  >> 10289    /usr/bin/ld: final link failed: Nonrepresentable section on output
  >> 10290    collect2: error: ld returned 1 exit status
     10291    configure:39934: $? = 1
     10292    configure:39955: here is the Fortran program:
     10293    program fsize
```

Since I'm not sure what the actual problem could be, I'm attaching some files generated by the failed build: the install output printed to the terminal, as well as `spack-build.out`, and `config.log`.

[install_output.log](https://github.com/spack/spack/files/2771349/install_output.log)
[spack-build.out.log](https://github.com/spack/spack/files/2771356/spack-build.out.log)
[config.log](https://github.com/spack/spack/files/2771344/config.log)

**Comment by scottwittenburg** [comment]
This initially came up when I was building it as a part of `xsdk-0.4.0`.  Pinging @balay and @davydden, just in case you may have seen this before or know something about it.

**Comment by davydden** [comment]
I have not seen this error.

**Comment by balay** [comment]
Normally I use a preinstalled mpi for most of my builds. On ubuntu-18.04 - I had a been using a prebuilt mpich.

I can reproduce this error with openmpi build - don't know why it occurs.

I tried  `spack install openmpi@3.1.3%clang@6.0.0-1ubuntu2 cflags=-fPIC cxxflags=-fPIC fflags=-fPIC` and this goes through fine

**Comment by scottwittenburg** [comment]
Sounds good @davydden, thanks for taking a look.  @balay since the `xsdk-0.4.0` concretization picks the version of openmpi we try to install in that case, how did you ensure spack would build against mpich?  Using the `packages.yaml` to prioritize that and say that it's not buildable?

**Comment by balay** [comment]
yeah - I use packages.yaml to specify some of system stuff - and my own  mpi [to cut down my rebuilt time - as I tend to rebuild xsdk many times]

Now looking at it - I'm using gcc buit mpich for clang build - so that is a bug in my test process. [I need to fix this..]

**Comment by jlippuner** [comment]
I'm seeing the same issue trying to build OpenMPI with spack using clang 7.0 and gfortran 8.3.0 to get the fortran bindings. @balay's solution of adding `cflags=-fPIC cxxflags=-fPIC fflags=-fPIC` to the `spack install` command works for me.

**Comment by tuxfan** [comment]
Any progress on this?

**Comment by KineticTheory** [comment]
I'm also seeing this issue when using a mixed compiler toolchain (clang@10.0.0 and gfortran-7.5.0).  I was attempting to build `openmpi@3.1.6 % clang-10.0.0`. Adding `-fPIC` fixed this issue for me:

```yaml
- compiler:
    spec: clang@10.0.0
    paths:
      cc: /home/kellyt/spack-0.15.0/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.5.0/llvm-10.0.0-sggs5macvtzd24anlgsjzboarsnjddsa/bin/clang
      cxx: /home/kellyt/spack-0.15.0/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.5.0/llvm-10.0.0-sggs5macvtzd24anlgsjzboarsnjddsa/bin/clang++
      f77: /usr/bin/gfortran-7
      fc: /usr/bin/gfortran-7
    flags:
      cflags: -fPIC
      cxxflags: -fPIC
      fflags: -fPIC
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by KineticTheory** [comment]
[Update] I continue to see this build failure and the `-fPIC` compiler flag fix still works.  I just worked through this with Ubuntu-20.04 ([wsl2](https://docs.microsoft.com/en-us/windows/wsl/install-win10)), `llvm@10.0.1`, and `gfortran@9.3.0` when building `openmpi@3.1.6 % clang`.  Here is the excerpt from my `compilers.yaml` that allows openmpi@clang to build:
```yaml
compilers:
- compiler:
    spec: clang@10.0.1
    paths:
      cc: /home/kellyt/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/llvm-10.0.1-sgw5fuj4tosf6l4jpoc3jayot7waxr6l/bin/clang
      cxx: /home/kellyt/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/llvm-10.0.1-sgw5fuj4tosf6l4jpoc3jayot7waxr6l/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags:
      cflags: -fPIC
      cxxflags: -fPIC
      fflags: -fPIC
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
