### ISSUE TITLE
Spack fails to parse module files in some instances

### ISSUE THREAD

**Issue by ptooley** [spack/spack#10455]
In trying to use spack on MareNostrum I have discovered that the parsing of system modules is somewhat fragile as it simply searches for lines contained the variable, such as "PATH", and therefore can fail if there are, e.g debug statements in there.

For a specific example, on MareNostrum, I am trying to use the provided intel-mpi:
```
packages:
  all:
    compiler: [intel@17.0.4]
    providers:
      blas: [intel-mkl]
      lapack: [intel-mkl]
      mpi: [intel-mpi]

  intel-mkl:
    modules:
      intel-mkl@17.3.196: mkl/2017.4
    buildable: False

  intel-mpi:
    modules:
      intel-mpi@2017.3.196: impi/2017.4
    buildable: False

```
which has the module file:
```
-------------------------------------------------------------------------------------------------------------------
   /apps/modules/modulefiles/environment/impi/2017.4:
-------------------------------------------------------------------------------------------------------------------
whatis("loads the impi 2017.4 environment ")
conflict("impi","openmpi","mvapich2")
LmodMessage("display impi/2017.4 (PATH, MANPATH, LD_LIBRARY_PATH)")
prepend_path("PATH","/apps/INTEL/2017.4/impi/2017.3.196/bin64")
prepend_path("MANPATH","/apps/INTEL/2017.4/impi/2017.3.196/man")
prepend_path("LD_LIBRARY_PATH","/apps/INTEL/2017.4/impi/2017.3.196/lib64")
setenv("MPI","impi")
setenv("MPI_V","2017.4")
setenv("I_MPI_ROOT","/apps/INTEL/2017.4/impi/2017.3.196")
setenv("MPI_ROOT","/apps/INTEL/2017.4/impi/2017.3.196")
help([[]])
```
which causes spack to fail with the error:
```
==> Warning: Extracted path from module does not exist:
        Extracted path: display impi/2017.4 (PATH, MANPATH, LD_LIBRARY_PATH
==> Error: substring not found
```
The offending code is in, `spack/lib/spack/spack/util/module_cmd.py` and it does not check that the line begins with a suitable command.

I can provide a patch but would the better approach be to whitelist certain setting commands like `prepend_path` or blacklist message commands like `LmodMessage`.  I am leaning towards the latter to avoid accidental breakages.

Opinions?
