### ISSUE TITLE
Conflict with system-provided spack when uninstalling a package

### ISSUE THREAD

**Issue by dorier** [spack/spack#10573]
I'm on a machine on which system packages have been installed with spack.
I also have my own installation of spack on my $HOME directory. My packages.yaml file contains the following to tell my local spack to use the system-installed Python:

```
    python:
        modules:
            python@2.7.15: python/2.7.15-b5bimol
            python@3.6.5: python/3.6.5-lvrzbky
        buildable: False
```

When I do `spack install py-numpy`, Numpy is install correctly and spack picks up the existing installation of Python rather than building a new one.

However if I do `spack uninstall --dependents py-numpy` I get a permission error:

```
==> Error: [Errno 13] Permission denied: '/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/python-3.6.5-lvrzbkyyf53gqe5xwp6xsp7xjzajdbbu/.spack/projections.yaml'
```

My local spack is apparently trying to go modify a system-spack package.
