### ISSUE TITLE
Spack should support the llvm-enabled pgi compiler

### ISSUE THREAD

**Issue by anderbubble** [spack/spack#10599]
Add support for finding / configuring PGI LLVM with `spack compiler find`.

### Rationale

PGI 2018 includes a production version of the PGI Linux/x86-64 compilers with an LLVM code generator and OpenMP runtime. It includes most features, languages, and programming model support found in the default PGI compilers, as well as the PGI debugger and profiler.

### Description

```
[joan5896@shas0136 ~]$ spack compiler add --scope=site /curc/sw/spack/summit/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pgi-18.4-p3oqv4mfexi5soq4lvfhb4vkrl4cpxqj/linux86-64-llvm/18.4
==> Found no new compilers
==> Compilers are defined in the following files:
    /curc/sw/spack/summit/etc/spack/compilers.yaml
```

This should either find `pgi%18.4`, or a new compiler `pgi-llvm%18.4` (preferred, I think)

**Comment by francesco-bongiovanni** [comment]
I have the same issue with Intel parallel studio 2019.2...
![intelspacknotfound](https://user-images.githubusercontent.com/943165/52776696-73c86b00-3042-11e9-95b2-f6cbc734a285.png)

**Comment by adamjstewart** [comment]
@anderbubble This should be a really easy feature to add. What are the compiler executable names, the same as PGI? What is the output of `pgcc -V`?

@francesco-bongiovanni Same question, what is the output of `icc --version`?

**Comment by francesco-bongiovanni** [comment]
> @anderbubble This should be a really easy feature to add. What are the compiler executable names, the same as PGI? What is the output of `pgcc -V`?
> 
> @francesco-bongiovanni Same question, what is the output of `icc --version`?

icc (ICC) 19.0.2.187 20190117
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.

**Comment by adamjstewart** [comment]
@francesco-bongiovanni That output looks pretty standard, no idea why Spack wouldn't be picking it up. Are you sure it isn't already in your `compilers.yaml`?

**Comment by anderbubble** [comment]
> @anderbubble This should be a really easy feature to add. What are the compiler executable names, the same as PGI? What is the output of `pgcc -V`?

```
[joan5896@shas0136 ~]$ /curc/sw/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pgi-18.4-p3oqv4mfexi5soq4lvfhb4vkrl4cpxqj/linux86-64-llvm/18.4/bin/pgcc-llvm -V

pgcc-llvm 18.4-0 LLVM 64-bit target on x86-64 Linux -tp haswell 
PGI Compilers and Tools
Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
```

**Comment by francesco-bongiovanni** [comment]
> @francesco-bongiovanni That output looks pretty standard, no idea why Spack wouldn't be picking it up. Are you sure it isn't already in your `compilers.yaml`?

Yes. 

We manage to install it by taking an old 2018 version and modifying the paths manually, not ideal but Spack picked it up.

**Comment by anderbubble** [comment]
@francesco-bongiovanni and @adamjstewart 

I just put this comment in the associated PR; but since that's merged already, I'll mirror it here.

On current develop, I just realized it's picking up the `-llvm` variants by default in all circumstances now.

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /curc/sw/spack-experimental/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pgi-19.4-lprd2a7fgdcunzt4nini67zq5mnttomm/linux86-64/19.4/bin/pgcc-llvm
      cxx: null
      f77: /curc/sw/spack-experimental/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pgi-19.4-lprd2a7fgdcunzt4nini67zq5mnttomm/linux86-64/19.4/bin/pgfortran-llvm
      fc: /curc/sw/spack-experimental/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/pgi-19.4-lprd2a7fgdcunzt4nini67zq5mnttomm/linux86-64/19.4/bin/pgf90-llvm
    spec: pgi@19.4
    target: x86_64
```

This even though I only ran

```
$ spack compiler find --scope=site $(spack location -i pgi@19.4)/linux86-64/19.4                                                                                                                               
==> Added 1 new compiler to /curc/sw/spack-experimental/etc/spack/compilers.yaml
    pgi@19.4
==> Compilers are defined in the following files:
    /curc/sw/spack-experimental/etc/spack/compilers.yaml
```

I guess I didn't notice that the `-llvm` variants are _also_ in `linux86-64/19.4/bin`, not just `linux86-64-llvm/19.4/bin`.

My understanding is that the llvm variant doesn't support all the same features as the traditional variant of the pgi code generator; so defaulting to the llvm variant is probably the wrong thing.

In my opinion, `spack compiler find` shouldn't be looking for the `-llvm` binaries by name; it should just be willing to accept when the standard binary names return LLVM in their version string. That way, you can specify which compiler you want by pointing it at `linux86-64` or `linux86-64-llvm`.
