### ISSUE TITLE
Installation issue: openmpi@1.10.2 %gcc@4.8.5

### ISSUE THREAD

**Issue by therealjero-me** [spack/spack#10822]
### Steps to reproduce the issue

```console
$ spack install openmpi@1.10.2%gcc@4.8.5
==> Error: ProcessError: Command exited with status 2:
    'make' '-j20'

14 errors found in build log:
     2997    checking whether linking with -ldl works... yes
     2998    checking whether RTLD_DEFAULT is declared... yes
     2999    checking whether RTLD_NEXT is declared... yes
     3000    checking BPatch.h usability... no
     3001    checking BPatch.h presence... no
     3002    checking for BPatch.h... no
  >> 3003    configure: error: no BPatch.h found; check path for Dyninst package first...
     3004    checking for tau_instrumentor... no
  >> 3005    configure: error: no tau_instrumentor found; check path for PDToolkit first...
     3006    configure: we are configuring inside Open MPI; preset some test results
     3007    checking for mpicc... (cached) /opt/spack/lib/spack/env/gcc/gcc
     3008    checking for mpicxx... (cached) /opt/spack/lib/spack/env/gcc/g++
     3009    checking whether MPI_IN_PLACE is declared... (cached) yes
     3010    checking whether MPI_ROOT is declared... (cached) yes
     3011    checking for MPI_Add_error_class... (cached) yes

     ...

     3028    checking for MPI_Register_datarep... (cached) yes
     3029    checking for PMPI_File_read_ordered... (cached) yes
     3030    checking for PMPI_File_read_ordered_begin... (cached) yes
     3031    checking for PMPI_File_write_ordered... (cached) yes
     3032    checking for PMPI_File_write_ordered_begin... (cached) yes
     3033    checking for unimci-config... no
  >> 3034    configure: error: no unimci-config found; check path for UniMCI package first...
     3035    checking math.h usability... yes
     3036    checking math.h presence... yes
     3037    checking for math.h... yes
     3038    checking whether we need to link -lm to get math functions... yes
     3039    checking f2c.h usability... yes
     3040    checking f2c.h presence... yes
     3041    checking for f2c.h... yes
     3042    checking for clapack.h... no
  >> 3043    configure: error: no clapack.h found; check path for CLAPACK package first...
     3044    checking for C++ runtime library... -lstdc++
     3045    checking for the pthreads library -lpthreads... no
     3046    checking whether pthreads work without any flags... no
     3047    checking whether pthreads work with -Kthread... no
     3048    checking whether pthreads work with -kthread... no
     3049    checking for the pthreads library -llthread... no

     ...

     3094    checking for nvcc... nvcc
     3095    checking cupti.h usability... yes
     3096    checking cupti.h presence... yes
     3097    checking for cupti.h... yes
     3098    checking whether linking with -lcupti works... yes
     3099    checking whether CUPTI API version >= 2 & <= 4... no
  >> 3100    configure: error: CUPTI API version could not be determined and/or is incompatible (< 2 o. > 4)
     3101    See `config.log' for more details.
     3102    checking for dlfcn.h... (cached) yes
     3103    checking whether linking with -ldl works... yes
     3104    checking whether RTLD_DEFAULT is declared... (cached) yes
     3105    checking whether RTLD_NEXT is declared... (cached) yes
     3106    checking for shared LIBC's pathname... /lib64/libc.so.6
     3107    checking whether __errno_location is declared... yes
     3108    checking ctool/ctool.h usability... no
     3109    checking ctool/ctool.h presence... no
     3110    checking for ctool/ctool.h... no
  >> 3111    configure: error: no ctool/ctool.h found; check path for CTool package first...
     3112    checking for __WAIT_STATUS... yes
     3113    checking whether environ is declared... yes
     3114    checking for execvpe... yes
     3115    checking for fexecve... yes
     3116    checking for waitid... yes
     3117    checking for wait3... yes

     ...

     3145    checking zlib.h presence... yes
     3146    checking for zlib.h... yes
     3147    checking whether linking with -lz works... yes
     3148    checking bmi.h usability... no
     3149    checking bmi.h presence... no
     3150    checking for bmi.h... no
  >> 3151    configure: error: no bmi.h found; check path for BMI package first...
     3152    configure: configuring in extlib/otf (/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/contrib/vt/vt/extlib/otf)
     3153    configure: running /bin/sh /opt/spack/var/spack/stage/openmpi-1.10.2-hdum7dzm7llkmyepci6uqwqasu7ytemy/openmpi-1.10.2/ompi/contrib/vt/
             vt/extlib/otf/configure  '--with-openmpi-inside=1.7' '--prefix=/opt/software/linux-centos7-x86_64/gcc/4.8.5/openmpi/1.10.2-hdum7dzm7l
             lkmyepci6uqwqasu7ytemy' '--enable-shared' '--with-wrapper-ldflags=' '--enable-static' '--without-pmi' '--with-verbs' '--without-psm2'
              '--without-libfabric' '--without-psm' '--without-mxm' '--without-ucx' '--without-sge' '--without-tm' '--without-lsf' '--without-alps
             ' '--without-slurm' '--without-loadleveler' '--disable-memchecker' '--with-hwloc=/opt/software/linux-centos7-x86_64/gcc/4.8.5/hwloc/1
             .11.11-m6abbvqd3mkkkhvjraecgadbkuhzxo2c' '--disable-java' '--disable-mpi-java' '--without-sqlite3' '--disable-mpi-thread-multiple' '-
             -without-cuda' '--enable-cxx-exceptions' 'CC=/opt/spack/lib/spack/env/gcc/gcc' 'CXX=/opt/spack/lib/spack/env/gcc/g++' 'FC=/opt/spack/
             lib/spack/env/gcc/gfortran' 'CPPFLAGS=-DINSIDE_OPENMPI -I/opt/spack/var/spack/stage/openmpi-1.10.2-hdum7dzm7llkmyepci6uqwqasu7ytemy/o
             penmpi-1.10.2/ompi/include -I/opt/spack/var/spack/stage/openmpi-1.10.2-hdum7dzm7llkmyepci6uqwqasu7ytemy/openmpi-1.10.2/ompi/contrib/v
             t/vt/../../../include -I/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/contrib/vt/vt/../../../include' 'LDFLAGS=-
             L/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/.libs -L/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.
             10.2/ompi/contrib/vt/vt/../../../.libs' '--disable-option-checking' MPICC="/opt/spack/lib/spack/env/gcc/gcc" MPICXX="/opt/spack/lib/s
             pack/env/gcc/g++" --with-mpi --with-mpi-lib="-lmpi" --with-zlib-lib="-lz" --without-zoidfs --includedir="${prefix}/include/vampirtrac
             e" --docdir="${datarootdir}/doc/otf"  --cache-file="/dev/null" --srcdir="/opt/spack/var/spack/stage/openmpi-1.10.2-hdum7dzm7llkmyepci
             6uqwqasu7ytemy/openmpi-1.10.2/ompi/contrib/vt/vt/extlib/otf" --disable-option-checking
     3154    checking build system type... x86_64-pc-linux-gnu
     3155    checking host system type... x86_64-pc-linux-gnu
     3156    checking target system type... x86_64-pc-linux-gnu
     3157    checking for a BSD-compatible install... /usr/bin/install -c

     ...

     3245    checking for mpicc... /opt/spack/lib/spack/env/gcc/gcc
     3246    checking for mpic++... /opt/spack/lib/spack/env/gcc/g++
     3247    checking for OpenMP flag of C++ compiler... -fopenmp
     3248    checking vtf3.h usability... no
     3249    checking vtf3.h presence... no
     3250    checking for vtf3.h... no
  >> 3251    configure: error: no vtf3.h found; check path for VTF3 package first...
     3252    checking zlib.h usability... yes
     3253    checking zlib.h presence... yes
     3254    checking for zlib.h... yes
     3255    checking whether linking with -lm works... yes
     3256    checking whether we need to link -lm to get math functions... yes
     3257    checking for pdflatex... no

     ...

     7219      CC       base/vprotocol_base_request.lo
     7220      CCLD     libmca_vprotocol.la
     7221    make[2]: Leaving directory `/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/mca/vprotocol'
     7222    Making all in mca/common/verbs_usnic
     7223    make[2]: Entering directory `/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/mca/common/verbs_usnic'
     7224      CC       libmca_common_verbs_usnic_la-common_verbs_usnic_fake.lo
  >> 7225    common_verbs_usnic_fake.c:72:5: error: unknown field 'ops' specified in initializer
     7226         .ops = {
     7227         ^
  >> 7228    common_verbs_usnic_fake.c:73:9: error: unknown field 'alloc_context' specified in initializer
     7229             .alloc_context = fake_alloc_context,
     7230             ^
  >> 7231    common_verbs_usnic_fake.c:74:9: error: unknown field 'free_context' specified in initializer
     7232             .free_context = fake_free_context
     7233             ^
     7234    common_verbs_usnic_fake.c: In function 'fake_driver_init':
     7235    common_verbs_usnic_fake.c:89:5: warning: implicit declaration of function 'ibv_read_sysfs_file' [-Wimplicit-function-declaration]
     7236         if (ibv_read_sysfs_file(uverbs_sys_path, "device/vendor",
     7237         ^
     7238    common_verbs_usnic_fake.c: In function 'ompi_common_verbs_usnic_register_fake_drivers':
     7239    common_verbs_usnic_fake.c:133:9: warning: implicit declaration of function 'ibv_register_driver' [-Wimplicit-function-declaration]
     7240             ibv_register_driver("usnic_verbs", fake_driver_init);
     7241             ^
  >> 7242    make[2]: *** [libmca_common_verbs_usnic_la-common_verbs_usnic_fake.lo] Error 1
     7243    make[2]: Leaving directory `/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi/mca/common/verbs_usnic'
  >> 7244    make[1]: *** [all-recursive] Error 1
     7245    make[1]: Leaving directory `/dev/shm/root/spack-stage/spack-stage-2293kt1i/openmpi-1.10.2/ompi'
  >> 7246    make: *** [all-recursive] Error 1

```

### Platform and user environment

Please report your OS here:
```commandline
# uname -a
Linux login 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
``` 
and, if relevant, post or attach:

- `packages.yaml`

```
packages:

  # ---------------  REBUILDABLE  ---------------
  libpng:
    paths:
      libpng@1.5.13     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
  qt:
    paths:
      qt@4.8.7          %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
  libpciaccess:
    paths:
      libpciaccess@0.14 %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
  libxc:
    paths:
      libxc@2.1.2      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
  libxsmm:
    paths:
      libxsmm@1.6.1      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /

  # --------------- NOT BUILDABLE ---------------
  rdma-core:
    paths:
      rdma-core@17.2    %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" build_type=RelWithDebInfo arch=linux-centos7-x86_64: /
    buildable: False
  autoconf:
    paths:
      autoconf@2.69     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  m4:
    paths:
      m4@1.4.16         %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  automake:
    paths:
      automake@1.13.4   %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  libtool:
    paths:
      libtool@2.4.2     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  curl:
    paths:
      curl@7.29.0       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  ghostscript:
    paths:
      ghostscript@9.07  %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  subversion:
    paths:
      subversion@1.7.14 %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  numactl:
    paths:
      numactl@2.0.9     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  pkgconf:
    paths:
      pkgconf@0.27.1    %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  pkg-config:
    paths:
      pkg-config@0.27.1 %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  bzip2:
    paths:
      bzip2@1.0.6       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  openssl:
    paths:
      openssl@1.0.2k    %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  sqlite:
    paths:
      sqlite@3.7.17     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  tar:   
    paths:
      tar@1.26          %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  xz:
    paths:
      xz@5.2.2          %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  gettext:
    paths:
      gettext@0.19.8.1  %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  expat:
    paths:
      expat@2.1.0       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  libarchive:
    paths:
      libarchive@3.1.2  %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  libuv:
    paths:
      libuv@1.24.1      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  rhash:
    paths:
      rhash@1.3.4       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  perl:
    paths:
      perl@5.16.3       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  help2man:
    paths:
      help2man@1.41.1   %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  pcre:
    paths:
      pcre@8.32         %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
  pango:
    paths:
      pango@1.42.4  %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" +X arch=linux-centos7-x86_64: /usr
    buildable: False
  libxt:
    paths:
      libxt@1.1.5       %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  tk:  # tk-devel tk-devel.i686
    paths:
      tk@1.1.5      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  cairo:
    paths:
      cairo@1.15.12     %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" +pdf +X arch=linux-centos7-x86_64: /usr
    buildable: False
  glib:
    paths:
      glib@2.17         %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  libx11:
    paths:
      libx11@1.6.5      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  ncurses:
    paths:
      ncurses@5.9      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  zlib:
    paths:
      zlib@1.2.7      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  diffutils:
    paths:
      diffutils@3.3      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  bison:
    paths:
      bison@3.0.4      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  gmp:
    paths:
      gmp@6.1.2      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  libunistring:
    paths:
      libunistring@6.1.2      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  readline:
    paths:
      readline@6.2      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  guile:
    paths:
      guile@2.0.9      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /usr
    buildable: False
  gdbm:
    paths:
      gdbm@1.10      %gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" arch=linux-centos7-x86_64: /
    buildable: False
```

to the issue

### Additional information
The error seems related to certain versions of libs missing in CentOS 7.6

First of all, you can post the full output of:
```console
$ spack spec --install-status <spec>
Input spec
--------------------------------
 -   openmpi@1.10.2%gcc@4.8.5

Concretized
--------------------------------
 -   openmpi@1.10.2%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" ~cuda+cxx_exceptions fabrics=verbs ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 
[+]      ^hwloc@1.11.11%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" ~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64 
[+]          ^libpciaccess@0.14%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2"  arch=linux-centos7-x86_64 
[+]          ^libxml2@2.9.8%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" ~python arch=linux-centos7-x86_64 
[+]              ^libiconv@1.15%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2"  arch=linux-centos7-x86_64 
[+]              ^pkgconf@0.27.1%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2"  arch=linux-centos7-x86_64 
[+]              ^xz@5.2.2%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2"  arch=linux-centos7-x86_64 
[+]              ^zlib@1.2.7%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2" +optimize+pic+shared arch=linux-centos7-x86_64 
[+]          ^numactl@2.0.9%gcc@4.8.5 cflags="-O2" cxxflags="-O2" fflags="-O2"  arch=linux-centos7-x86_64
```
