### ISSUE TITLE
Inconsistent Spec hash due to patch ordering

### ISSUE THREAD

**Issue by sknigh** [spack/spack#10851]
Spack sometimes generates a different hashes with identical specs. Printing the spec yaml shows the ```patches``` list gets reordered.

I haven't found a way to consistently reproduce it.

```
spack spec -y /wm7jo6a

spec:
- m4:
    version: 1.4.18
    arch:
      platform: linux
      platform_os: centos7
      target: x86_64
    compiler:
      name: gcc
      version: 4.8.5
    namespace: builtin
    parameters:
      patches:
      - 3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00
      - c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e
      - fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
      sigsegv: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    patches:
    - 3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00
    - fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
    - c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e
    dependencies:
      libsigsegv:
        hash: qpmaxx6z62df4s4hwyehdwptv6kmrfhf
        type:
        - build
        - link
    hash: wm7jo6alnjydyimqrfzouolsfjv5y7ej
- libsigsegv:
    version: '2.11'
    arch:
      platform: linux
      platform_os: centos7
      target: x86_64
    compiler:
      name: gcc
      version: 4.8.5
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: qpmaxx6z62df4s4hwyehdwptv6kmrfhf
```

```
spack spec -y /hhsvnb

spec:
- m4:
    version: 1.4.18
    arch:
      platform: linux
      platform_os: centos7
      target: x86_64
    compiler:
      name: gcc
      version: 4.8.5
    namespace: builtin
    parameters:
      patches:
      - 3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00
      - c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e
      - fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
      sigsegv: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    patches:
    - c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e
    - 3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00
    - fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
    dependencies:
      libsigsegv:
        hash: qpmaxx6z62df4s4hwyehdwptv6kmrfhf
        type:
        - build
        - link
    hash: hhsvnbbpgbjmyko773df2mzmp5knybru
- libsigsegv:
    version: '2.11'
    arch:
      platform: linux
      platform_os: centos7
      target: x86_64
    compiler:
      name: gcc
      version: 4.8.5
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: qpmaxx6z62df4s4hwyehdwptv6kmrfhf
```
