### ISSUE TITLE
spack confused about location of global package with local hash

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#11086]
Spack gets confused about the location of global install of package with locally generated hash despite being given the location and modulefile. 

### Steps to reproduce the issue

```
$ spack install ... ^intel@2018.3.222
```

### Error Message

```
[sajid@apsxrmd-0001 jobs]$ spack install --keep-stage -v -j 10 petsc@develop+hypre+mpi+knl %intel@18.0.3 ^intel-mkl@2018.3.222 ^intel-mpi@2018.3.222 ^/573
==> intel-mpi@2018.3.222 : externally installed in /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mpi-2018.3.222-4aoglyb6zfpaydn6iuiz63wyj3soolv2
==> intel-mpi@2018.3.222 : already registered in DB
...
==> intel-mkl@2018.3.222 : externally installed in /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4
==> intel-mkl@2018.3.222 : already registered in DB
==> Installing hypre
==> Searching for binary cache of hypre
==> Warning: No Spack mirrors are currently configured
==> No binary for hypre found: installing from source
==> Error: InstallError: Cannot locate core MKL libraries:
        ['libmkl_intel_lp64', 'libmkl_sequential', 'libmkl_core']

/blues/gpfs/home/sajid/packages/spack/lib/spack/spack/build_systems/intel.py:761, in blas_libs:
        758            shared=('+shared' in self.spec))
        759        debug_print(mkl_libs)
        760
  >>    761        if len(mkl_libs) < 3:
        762            raise_lib_error('Cannot locate core MKL libraries:', mkl_libnames)
        763
        764        # The Intel MKL link line advisor recommends these system libraries
```
that activate the full debug output. 

### Information on your system

This includes:

 1. linux-centos7-x86_64
 2. custom `packages.yaml`:
```
[sajid@apsxrmd-0001 ~]$ cat .spack/packages.yaml 
packages:
  all:
    # Set Intel as default compiler
    compiler: [intel, gcc, pgi, nag]
    providers:
      # Set Intel MKL as default BLAS/LAPACK provider
      blas:   [intel-mkl,openblas]
      lapack: [intel-mkl,openblas]
      # Set Intel MPI as default MPI implementation
      mpi: [intel-mpi, mvapich2, mpich, openmpi]
    variants: ~mpi+openmp
  # External Packages
  # Many of these are build dependencies, so it doesn't really matter
  # if we build with the latest version. Just use the system installation.
  autoconf:
    paths:
      autoconf@2.69 arch=linux-centos7-x86_64: /usr
#      autoconf@2.63 arch=linux-centos6-x86_64: /usr
    buildable: False
  automake:
    paths:
      automake@1.13.4 arch=linux-centos7-x86_64: /usr
      automake@1.11.1 arch=linux-centos6-x86_64: /usr
    buildable: False
  bison:
    paths:
      bison@2.7   arch=linux-centos7-x86_64: /usr
      bison@2.4.1 arch=linux-centos6-x86_64: /usr
    buildable: False
#  cmake:
#    paths:
#      cmake@2.8.12.2 arch=linux-centos6-x86_64: /usr
#  flex:
#    paths:
#      flex@2.5.37 arch=linux-centos7-x86_64: /usr
#      flex@2.5.35 arch=linux-centos6-x86_64: /usr
#    buildable: False
  libtool:
    paths:
      libtool@2.4.2 arch=linux-centos7-x86_64: /usr
      libtool@2.2.6b arch=linux-centos6-x86_64: /usr
    buildable: False
  m4:
    paths:
      m4@1.4.16 arch=linux-centos7-x86_64: /usr
      m4@1.4.13 arch=linux-centos6-x86_64: /usr
    buildable: False
  openssl:
    # Instead of rebuilding everything when a security update comes out,
    # always build with the system openssl. It is more likely to be
    # updated if the bug is serious enough
    paths:
      openssl@1.0.1e arch=linux-centos7-x86_64: /usr
      openssl@1.0.1e arch=linux-centos6-x86_64: /usr
    buildable: False
#  numactl:
#    paths:
#      numactl@2.0.9 arch=linux-centos6-x86_64: /usr
#    buildable: False
  #perl:
  #  # Perl cannot be built with the Intel compilers
  #  paths:
  #    perl@5.16.3 arch=linux-centos7-x86_64: /usr
  #    perl@5.10.1 arch=linux-centos6-x86_64: /usr
  #  buildable: False
#  #  pkg-config:
#    paths:
#    pkg-config@0.27.1 arch=linux-centos7-x86_64: /usr
#    pkg-config@0.23   arch=linux-centos6-x86_64: /usr
#    buildable: False
  # Build all compilers with the system compiler
#  gcc:
#    compiler: [gcc@4.8.5]
#    variants: ~binutils
#  intel:
#    compiler: [gcc@4.8.5]
#  intel-parallel-studio:
#    compiler: [gcc@4.8.5]
#    variants: +all
#  nag:
#    compiler: [gcc@4.8.5]
#  pgi:
#    compiler: [gcc@4.8.5]
  # Set default variants
  cantera:
    variants: +python
  gromacs:
    variants: +plumed
  hdf:
    variants: +szip
  hdf5:
    variants: +szip~mpi
  mvapich2:
    variants: ch3_rank_bits=32 fabrics=psm process_managers=slurm threads=multiple
  netcdf:
    variants: +hdf4+dap+cdmremote~mpi
  openmpi:
    variants: fabrics=psm2 schedulers=slurm +thread_multiple
  intel-mkl:
    modules:
       intel-mkl@2018.3.222%intel@18.0.3 +shared~ilp64 arch=linux-centos7-x86_64: /blues/gpfs/home/software/spack-0.10.1/share/spack/lmod/linux-centos7-x86_64/intel/18.0.3/intel-mkl/2018.3.222-6ff5hhp.lua
    paths:
       intel-mkl@2018.3.222%intel@18.0.3 +shared~ilp64 arch=linux-centos7-x86_64: /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4 
    buildable: False
  intel-mpi:
    modules:
        intel-mpi@2018.3.222%intel@18.0.3 arch=linux-centos7-x86_64: /blues/gpfs/home/software/spack-0.10.1/share/spack/lmod/linux-centos7-x86_64/intel/18.0.3/intel-mpi/2018.3.222-4aoglyb.lua
    paths:
       intel-mpi@2018.3.222%intel@18.0.3 arch=linux-centos7-x86_64: /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mpi-2018.3.222-4aoglyb6zfpaydn6iuiz63wyj3soolv2 
    buildable: False

```

Does spack know of the existance of intel-mkl@2018.3.222 ? Yes.
```
[sajid@apsxrmd-0001 jobs]$ spack find -lv intel-mkl
==> 2 installed packages
-- linux-centos7-x86_64 / intel@17.0.4 --------------------------
vrmvwju intel-mkl@2017.3.196~ilp64+shared threads=none

-- linux-centos7-x86_64 / intel@18.0.3 --------------------------
qn7bzkv intel-mkl@2018.3.222~ilp64+shared threads=none
``` 

Does spack know where to find it ? No!
```
[sajid@apsxrmd-0001 jobs]$ spack location intel-mkl@2018.3.222
==> Error: [Errno 2] No such file or directory: '/blues/gpfs/home/sajid/packages/spack/var/spack/stage/intel-mkl-2018.3.222-qn7bzkvvpmexkr2kwgxikhv3pcebhglg'
```

Extra info (module generated by local instance of spack):
```
[sajid@apsxrmd-0001 linux-centos7-x86_64]$ pwd
/home/sajid/packages/spack/share/spack/modules/linux-centos7-x86_64
[sajid@apsxrmd-0001 linux-centos7-x86_64]$ cat intel-mkl-2018.3.222-intel-18.0.3-qn7bzkv 
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-02-26 00:46:36.450210
##
## intel-mkl@2018.3.222%intel@18.0.3~ilp64+shared threads=none arch=linux-centos7-x86_64 /qn7bzkv
##
## Configure options: unknown, software installed outside of Spack
##


module-whatis "Intel Math Kernel Library."

proc ModulesHelp { } {
puts stderr "Intel Math Kernel Library."
}


prepend-path PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/bin"
prepend-path LD_LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/lib"
prepend-path LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/lib"
prepend-path CMAKE_PREFIX_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/"
prepend-path CPATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/include:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/include:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.3-d6gtsxst5w4bw3ko7qvtaweu23hv5y6b/compilers_and_libraries_2018.3.222/linux/pstl/include:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.3-d6gtsxst5w4bw3ko7qvtaweu23hv5y6b/compilers_and_libraries_2018.3.222/linux/tbb/include:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.3-d6gtsxst5w4bw3ko7qvtaweu23hv5y6b/include"
prepend-path LD_LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin"
prepend-path LD_LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin"
prepend-path LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin"
prepend-path LIBRARY_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin"
prepend-path NLSPATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/locale/%l_%t/%N:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/locale/%l_%t/%N:/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.3-d6gtsxst5w4bw3ko7qvtaweu23hv5y6b/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64/locale/%l_%t/%N"
append-path PKG_CONFIG_PATH "/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-mkl-2018.3.222-6ff5hhpjd6k3y4uvcg4mrthoqj3e3ok4/compilers_and_libraries_2018.3.222/linux/mkl/bin/pkgconfig"
```

PS : This worked in Feb, did something change ?
