### ISSUE TITLE
intel.py picks up gcc form environment which may conflict with -gcc-name=

### ISSUE THREAD

**Issue by davydden** [spack/spack#11135]
I was digging in some errors and noticed that in `build_system/intel.py` gcc version is being picked up from 
```
Executable('gcc')
```
If one uses modules in HPC, that's fine, but say on Ubuntu with 
```
    flags:
      cflags: -gcc-name=/usr/bin/gcc-4.8
      cxxflags: -gxx-name=/usr/bin/g++-4.8
      fflags: -gcc-name=/user/bin/gcc-4.8
```
this will lead to conflicting setup.
