### ISSUE TITLE
Installation issue: hypre 2.15.1 fails to configure with intel@19.0.3 + gcc@4.8

### ISSUE THREAD

**Issue by davydden** [spack/spack#11137]
### Steps to reproduce the issue

```console
$ spack install hypre
```

The error is:

```
   40    checking for dummy main to link with Fortran libraries... unknown
  >> 41    configure: error: in `/home/davydden/spack/var/spack/stage/hypre-2.15.1-tyrd6dwkdxwjzbudmrvhidgfs7ypdefp/hypre-2.15.1/src':
  >> 42    configure: error: linking to Fortran libraries from C fails
     43    See `config.log' for more details
```

I looked at `config.log` but did not immediately spot anything wrong (attached below).

### Platform and user environment

```
- compiler:
    flags:
      cflags: -gcc-name=/usr/bin/gcc-4.8
      cxxflags: -gxx-name=/usr/bin/g++-4.8
      fflags: -gcc-name=/usr/bin/gcc-4.8
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/bin/intel64/icc
      cxx: /home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/bin/intel64/icpc
      f77: /home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/bin/intel64/ifort
      fc: /home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/bin/intel64/ifort
    spec: intel@19.0.3.gcc.4.8
    target: x86_64
```

```commandline
$ uname -a 
Linux ... 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.2 LTS
``` 

### Additional information

[config.log](https://github.com/spack/spack/files/3057718/config.log)
