### ISSUE TITLE
Permit to install packages under the same prefix if they are concretizable together

### ISSUE THREAD

**Issue by alalazo** [spack/spack#11164]
This is a proposal to allow installing specs that are part of an environment under the same common prefix, if they are concretizable together. Installing under a common prefix should happen only upon user request.

### Rationale
This is a feature proposal based on #11158 and depending on #9902 being implemented. The basic idea is that, if we can concretize all the abstract specs of an environment together, then we can also install them under the same prefix without any conflict. This might be an option that would prove to be useful in some use-cases.

For instance a user might consider building a custom Docker image using a [multi-stage stage build](https://docs.docker.com/develop/develop-images/multistage-build/) and a `spack.yaml` file with specs that can be concretized together. With a `spack.yaml` file similar to:
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: ['hdf5+mpi', 'mpich', 'zlib@1.2.8' ]
  concretize_together: True
  common_prefix: '/opt'
```
and a Dockerfile like:
```dockerfile
FROM spack/centos as builder
COPY spack.yaml .
RUN spack install

FROM centos
[...]
COPY --from=builder /opt .
[...]
```
we could create a container with our environment installed in standard locations. This container can then be consumed by users without any knowledge of Spack or modules, etc.

Another use case might be software development, where we would give the choice to the user on whether to employ a view like in #10017 or install all the dependencies needed to start working on a software in some specific directory. 

### Description

The implementation of this - if considered a good feature - should involve:

- [ ] Modifying `spack.yaml` config file to support the use of a common installation prefix (ideally set to `None` by default and settable only if `concretize_together: True` is in `spack.yaml`)
- [ ] Add logic at install time to change the prefix of all the concretized specs before installing them (with possibly preliminary checks on the state of the common prefix)
