### ISSUE TITLE
packages.yaml: ninja and ninja-fortran are now virtual packages

### ISSUE THREAD

**Issue by goxberry** [spack/spack#11628]
### Description

On my macOS machines, I maintain a `packages.yaml` file I use to expose Homebrew- or system-installed software to Spack. As part of that file, I have an entry for `ninja`, but it appears that `ninja` has been made a virtual package as of merging PR #11347 (commit `251f3f5058beb60f65d420a03f1ee77998ddbc87`), and `ninja` provides, in some cases, `ninja-fortran` and vice versa. The name of a virtual package cannot be used as a package entry under the `packages:` field in a `package.yaml` file. Thus, a user who has installed Ninja on their system through some means other than Spack and wants to expose that installation to Spack cannot do so.

### Steps to reproduce the issue

1. Install `ninja` by some other means than through Spack.

2. Add an entry for `ninja` in a `packages.yaml` file discoverable by Spack (e.g., `~/.spack/packages.yaml`). For instance:

```yaml
packages:
  # other packages may go before this entry
   ninja:
     paths:
       ninja@1.9.0 %clang@10.0.1-apple: /usr/local/opt/ninja
  # other packages may go after this entry
```
3. Attempt to install or uninstall something.

```console
$ spack install cmake curl
```

### Error Message

```console
==> Error: packages.yaml entries cannot be virtual packages:
  in "/Users/oxberry1/.spack/packages.yaml", line 207, column 3: ninja
```

### Information on your system

My system is running macOS 10.14.5 and uses a custom `packages.yaml` file. An excerpted version is listed above to reproduce the error. This bug should be insensitive to OS, so it should be reproducible on Linux as well.
