### ISSUE TITLE
Ncurses package.py does not respect compiler CFLAGS

### ISSUE THREAD

**Issue by cdfh** [spack/spack#11819]
### Steps to reproduce the issue

Install/configure a compiler with a module that sets `CFLAGS` or `CXXFLAGS`.

Install ncurses with
```console
$ spack install ncurses
```
During installation, ncurses will be configured with:

```console
$ ./configure CFLAGS='' CXXFLAGS='' ...
```
overriding (without appending) whatever values were set by the compiler's module file.

### Platform and user environment

Affects all platforms.

User environment: any environment in which the compiler is configured to have a module file that sets the `CFLAGS` or `CXXFLAGS` environment variables.

### Additional information

For my purposes, I fixed this by changing ncurses' `package.py` file:

```
diff --git a/var/spack/repos/builtin/packages/ncurses/package.py b/var/spack/repos/builtin/packages/ncurses/package.py
index 56218a930..f6ba29239 100644
--- a/var/spack/repos/builtin/packages/ncurses/package.py
+++ b/var/spack/repos/builtin/packages/ncurses/package.py
@@ -33,10 +33,12 @@ class Ncurses(AutotoolsPackage):
     patch('patch_gcc_5.txt', when='@6.0%gcc@5.0:')
     patch('sed_pgi.patch',   when='@:6.0')
 
+    def setup_environment(self, spack_env, run_env):
+            spack_env.append_flags('CFLAGS', self.compiler.pic_flag)
+            spack_env.append_flags('CXXFLAGS', self.compiler.pic_flag)
+
     def configure(self, spec, prefix):
         opts = [
-            'CFLAGS={0}'.format(self.compiler.pic_flag),
-            'CXXFLAGS={0}'.format(self.compiler.pic_flag),
             '--with-shared',
             '--with-cxx-shared',
             '--enable-overwrite',
```

Being a new user to spack, I've created an issue rather than a pull request in case this is an unwise thing to do.

In my case, the issue was preventing me from compiling with clang on a system where the standard library was specified in the `CFLAGS` and `CXXFLAGS` of my compiler's module file. Possibly my setup is non-standard, but nevertheless, it seems reasonable that whatever values are deemed necessary to specify in a compiler's configuration should never be silently overridden when installing a package, unless at the explicit request of the user.

**Comment by healther** [comment]
I think we should consider this a bug in `ncurses/package.py` and I think your solution is correct:tm: 
In general you should feel free to just open a pull request, especially if you already have a solution for your problem. If the maintainers disagree we can just as easily close a PR as an issue :)

**Comment by scheibelp** [comment]
Your solution is great. I have assigned you in the hope that you have the time to submit a PR. Could you let me know if that's not the case?

**Comment by mwkrentel** [comment]
@cdfh I tried your steps, but I'm unable to reproduce your results.
For me, spack treats cflags from `compilers.yaml` the way I'd expect.

First, some background on how spack treats compiler flags.  Spack has
three ways to pass flags to the build system.

1. `inject_flags` -- this adds flags to the spack compiler wrapper.

2. `env_flags` -- this sets environment variables.

3. `build_system_flags` -- this puts flags on the configure command
line, only available for Autotools or CMake packages.

The default is (1), and this is what ncurses uses.  You don't see the
flags on the configure line, but they're there.  To see the flags, you
need to run:

```
spack -d install -v ncurses
```

See: https://spack.readthedocs.io/en/latest/packaging_guide.html#compiler-flags

----------

Here's what I ran.  This is on RedHat 7.x with a native gcc 4.8.5
compiler.  I used 4.8.5 to build gcc 7.3.0 and used that as a module.

This is my `compilers.yaml` entry for 7.3.0.  I added a dummy
`-DXYZ=1` flag to cflags/cxxflags so I could look for it in the debug
output.

```
- compiler:
    environment: {}
    extra_rpaths: []
    modules:
    - gcc-7.3.0-gcc-4.8.5-qemsqrc
    operating_system: rhel7
    paths:
      cc: /home/krentel/Modules/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-7.3.0-qemsqrcwkk52f6neef4kg5wvoucsroif/bin/gcc
      cxx: /home/krentel/Modules/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-7.3.0-qemsqrcwkk52f6neef4kg5wvoucsroif/bin/g++
      f77: /home/krentel/Modules/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-7.3.0-qemsqrcwkk52f6neef4kg5wvoucsroif/bin/gfortran
      fc: /home/krentel/Modules/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-7.3.0-qemsqrcwkk52f6neef4kg5wvoucsroif/bin/gfortran
    flags:
      cflags:  -DXYZ=1
      cxxflags:  -DXYZ=1
    spec: gcc@7.3.0
    target: x86_64
```

This is how `spack spec` reports that it will configure ncurses.

```
$ spack spec ncurses
Input spec
--------------------------------
ncurses

Concretized
--------------------------------
ncurses@6.1%gcc@7.3.0 cflags="-DXYZ=1" cxxflags="-DXYZ=1" ~symlinks~termlib arch=linux-rhel7-x86_64
    ^pkgconf@1.6.1%gcc@7.3.0 cflags="-DXYZ=1" cxxflags="-DXYZ=1"  arch=linux-rhel7-x86_64
```

Note that spack sees `-DXYZ=1` from `compilers.yaml`.

Then I build ncurses with full verbose + debug output.  I'm using the
default `package.py`, not your patch.

```
$ spack -d install -v ncurses 2>&1 | tee out.1
...
==> [2019-07-07-00:20:50.855346] Installing ncurses
...
==> [2019-07-07-00:20:52.641266] Building ncurses [AutotoolsPackage]
==> [2019-07-07-00:20:52.644797] Executing phase: 'autoreconf'
==> [2019-07-07-00:20:52.647116] Executing phase: 'configure'

==> [2019-07-07-00:20:52.649024] '../configure'
'--prefix=/home/krentel/flags/install/linux-rhel7-x86_64/gcc-7.3.0/ncurses-6.1-3kdtt2bfxa63en7bmesfw7sjul6elnhn'
'CFLAGS=-fPIC' 'CXXFLAGS=-fPIC' '--with-shared' '--with-cxx-shared'
'--enable-overwrite' '--without-ada' '--enable-pc-files'
'--with-pkg-config-libdir=/home/krentel/flags/install/linux-rhel7-x86_64/gcc-7.3.0/ncurses-6.1-3kdtt2bfxa63en7bmesfw7sjul6elnhn/lib/pkgconfig'
'--disable-widec' '--without-manpages' '--without-tests'

...

/home/krentel/flags/spack-repo/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H
-I../ncurses -I. -I../../ncurses -I../include
-I../../ncurses/../include -D_GNU_SOURCE -DNDEBUG -fPIC --param
max-inline-insns-single=1200 -fPIC -c ../../ncurses/tty/hardscroll.c
-o ../obj_s/hardscroll.o
```

First, I get CFLAGS and CXXFLAGS as `-fPIC`, not empty as you report.
Perhaps your compiler doesn't need an additional flag to build PIC,
but that seems odd.

Note that the compile line for `hardscroll.c` doesn't mention
`-DXYZ=1`.  That's because they're hidden in the
`.../spack/env/gcc/gcc` wrapper.

You can see them in the debug output file, in my case
`spack-cc-ncurses-3kdtt2b.out.log`.

```
[cc] /home/krentel/Modules/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-7.3.0-qemsqrcwkk52f6neef4kg5wvoucsroif/bin/gcc
-DXYZ=1 -I../ncurses -I. -I../../ncurses -I../include
-I../../ncurses/../include -DHAVE_CONFIG_H -D_GNU_SOURCE -DNDEBUG
-fPIC --param max-inline-insns-single=1200 -fPIC -c
../../ncurses/tty/hardscroll.c -o ../obj_s/hardscroll.o
```

So, the flag from `compilers.yaml` is there, you just have to look for
it.  Note that these flags are not getting overwritten.  `-DXYZ=1` goes
to the compiler wrapper and `-fPIC` goes to the configure line, so
they're separate.

----------

@cdfh Could you repeat your steps and show me your output from the
steps that I've done above: the compilers.yaml entry, the spack spec,
the configure line from the output, and the hardscroll.c line from the
spack-cc-ncurses file, plus of course, the error message you get where
it fails.

I'm willing to believe that it fails for you, but there must be
something else going on here.

Maybe you're using more advanced flags that don't work well in the
wrapper.  Maybe llvm requires more attention.  Maybe you forgot to
fill in the modules: field in compilers.yaml.  I don't know.

But whatever it is, I want to understand the mechanics of it because
for me, it works as I'd expect.

Thanks.

**Comment by mwkrentel** [comment]
Btw, for ncurses, I claim that these lines aren't needed at all.

```
'CFLAGS={0}'.format(self.compiler.pic_flag),
'CXXFLAGS={0}'.format(self.compiler.pic_flag),
```

Automake and libtool know how to build shared libraries and add
`-fPIC` themselves.  You can see that in the above output where it
uses `-fPIC` twice.

Also, adding `CFLAGS='...'` to the configure args changes the
optimization level from the autotools default `-O2` to nothing.  
Note that there is no `-O` flag in the output above.

This depends on the compiler family, but for GNU, this means `-O0`,
which I would regard as a mistake.

**Comment by cdfh** [comment]
@mwkrentel Thanks for the details on how `CFLAGS`/`CXXFLAGS` propagates in spack, I found them helpful.

I can't reproduce, I'm afraid: I've since moved away from my initial configuration and no longer set `CFLAGS`/`CXXFLAGS` in `compilers.yaml`. It took some time to arrive at the setup where my PR seemed to fix my problem, and I'm afraid I don't have time to try to reproduce it.

From your description, I agree with your logic that ncurses is not overriding the flags, contrary to my initial claim when opening this issue. At the time, ncurses was one of several packages that I was having problems building with my `CFLAGS` setup. I was confident at the time that my proposed PR fixed my issue, but possibly I was mistaken and this is a non-issue. 

While this specific issue with ncurses may be user-error on my part, I certainly encountered problems when building packages on a Linux system where gcc and ld were not present and the only compiler was clang, installed from a binary release. The `CFLAGS`/`CXXFLAGS` I used at the time were correct for setting rpaths, setting -stdlib=libc++, etc, but some packages failed to install (ncurses and cmake were particularly difficult). One failure modality that I remember was some packages attempting to use '/usr/bin/ld' explicitly, instead of calling CC for linking. In the end, I gave up, recognising that it was much easier to a) compile llvm instead of depending upon a binary release (build options set so that the built llvm used libc++ by default), and b) use modules and `extra_rpaths` in `compilers.yaml` instead of using `CFLAGS`/`CXXFLAGS` to achieve the same result. 

It took me some time to recognise how to correctly setup llvm so as to use libc++ by default. Since that represents the real issue I was facing at the time, it seems fitting to paste my working `compilers.yaml` setup prior to closing the issue. Old hat, I'm sure, to those experienced in spack, but perhaps less obvious to new users who may find this page from Google.

```
# compilers.yaml
compilers::
- compiler:
    environment: {}
    extra_rpaths: [/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/llvm-8.0.0-b3kkud6rq2w6ppzqujr4hl4c2tcb4dho/lib]
    flags: {}
    modules: [llvm-8.0.0-gcc-7.4.0-b3kkud6]
    operating_system: ubuntu18.04
    paths:
      cc: /spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/llvm-8.0.0-b3kkud6rq2w6ppzqujr4hl4c2tcb4dho/bin/clang
      cxx: /spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/llvm-8.0.0-b3kkud6rq2w6ppzqujr4hl4c2tcb4dho/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: clang@8.0.0
    target: x86_64
```

Note that llvm should be build with `spack install llvm+libcxx`, which will produce a clang binary that uses libc++ by default, so it's not necessary to add `-stdlib=libc++` to `CXXFLAGS` (see `/spack/var/spack/repos/builtin/packages/llvm/package.py`; note `-DCLANG_DEFAULT_CXX_STDLIB=libc++` is appended to configure args when `+libcxx` is specified in the spec). Finally note that when building projects with `spack setup` (as described [here](https://spack.readthedocs.io/en/latest/workflows.html#developing-software-with-spack)), it will be necessary to run `spack load llvm` prior to running the resulting binaries, as binaries compiled with cmake don't have the rpaths setup in their build target (only their install target, as I understand it). Loading the llvm module sets `LD_LIBRARY_PATH` appropriately.

Closing the issue as I can't reproduce, sorry for the inconvenience.
