### ISSUE TITLE
spack.yaml providers directive does not impose version or variants

### ISSUE THREAD

**Issue by wspear** [spack/spack#12001]
The first chunk of my spack.yaml file looks like this:
```
spack:
  packages:
    all:
      compiler: [gcc]
      variants: +mpi
      providers:
        mpi: [mpich@3.2.1~wrapperrpath]
```

This results in packages concretizing in my environment using mpich, but using the latest mpich version and without my requested variant. It would be nice if the specifications given to the provider could be enforced (or at least if there was some warning or error to indicate that the syntax isn't applicable here).

The workaround is to provides a separate mpich section that covers my requirements:

   ```
 mpich:
      version:
      - 3.2.1
      variants: ~wrapperrpath
```
