### ISSUE TITLE
spack module (tcl|lcov|dotkit) loads: does not work with upstream packages

### ISSUE THREAD

**Issue by albestro** [spack/spack#12062]
`spack module * loads` does not work with upstream packages.

### Steps to reproduce the issue

```console
$ spack module <module-type> loads <package_in_upstream>
```

### Error Message

```console
==> Error: 'module' object has no attribute 'upstream_module'
```

### Information on your system

I configured `upstreams.yaml` like this

```yaml
upstreams:
  myupstream:
    install_tree: <UPSTREAM_SPACK_ROOT>/opt/spack
    modules:
      tcl: <UPSTREAM_SPACK_ROOT>/share/spack/modules
```
