### ISSUE TITLE
Magma tcl module refresh error

### ISSUE THREAD

**Issue by tvery42** [spack/spack#12214]
The refresh of the TCL module for magma does not work.

### Steps to reproduce the issue

```console
$ spack module tcl refresh magma
```

### Error Message
spack/lib/spack/spack/modules/common.py:772 ==> [2019-07-31-16:09:02.077425]   WRITE: magma@2.5.1-alpha1%intel@19.0.4 build_type=RelWithDebInfo +fortran+shared arch=linux-rhel7-x86_64/utjhipx [/xxx/modulefiles/linux-rhel7-x86_64/magma/2.5.1-alpha1/intel-19.0.4-cuda]
spack/lib/spack/spack/cmd/modules/__init__.py:283 ==> [2019-07-31-16:09:02.098188] NameError: global name 'prefix' is not defined
spack/lib/spack/spack/cmd/modules/__init__.py:285 ==> [2019-07-31-16:09:02.101102] Warning: Could not write module file [/xxx/modulefiles/linux-rhel7-x86_64/magma/2.5.1-alpha1/intel-19.0.4-cuda]
spack/lib/spack/spack/cmd/modules/__init__.py:286 ==> [2019-07-31-16:09:02.101293] Warning:    --> global name 'prefix' is not defined <--

### Information on your system

 1. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)
The modules.yaml file is modified:

```
modules:
    tcl:
        naming_scheme: '{name}/{version}/{compiler.name}-{compiler.version}'
        all:
            suffixes:
                ^mpi: "mpi"
                ^cuda: "cuda"
            conflict:
                - '{name}'

        blacklist_implicits: true
        verbose: True
        hash_length: 0
```
