### ISSUE TITLE
Spurious Error Installing into Environment w/ View

### ISSUE THREAD

**Issue by citibeth** [spack/spack#12323]
I have a Spack environment (with view).  I did the command:
```
spack install py-tables
```
It came back to me with:
```
==> Successfully installed py-tables
  Fetch: 0.70s.  Build: 2m 12.17s.  Total: 2m 12.88s.
[+] /root/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-tables-3.4.4-gxdk7c5kh3bgbwcjeqwidzifqsfvch2l

==> Updating view at /root/spack/var/spack/environments/research/.spack-env/view
==> Error: Cannot deactivate r-rcppeigen@0.3.3.3.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64/76ff53y because r-car@2.1-4%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64/7kucd5b is activated and depends on it
```
Yes, I have a bunch of R stuff in the environment.  But why is it trying to deactivate / reactive R things when all I did was add `py-tables`?

**Comment by adamjstewart** [comment]
I had this same problem. When I tried to deactivate the package, it told me it wasn't activated to begin with.

**Comment by scheibelp** [comment]
I can look at this by tomorrow (8/9) or possibly later today.

@adamjstewart did you have this issue with `py-tables` specifically, or with some other Python extension (and your error message mentioned an R package)?

@citibeth could you add the output after rerunning with `-d --stacktrace` (like `spack -d --stacktrace install py-tables`)?

**Comment by adamjstewart** [comment]
@scheibelp My error had nothing to do with R packages, it was Python packages that I had already installed. Basically, I installed a set of packages in my environment, one of them crashed, I reconcretized and tried to install again, and it complained that `py-numpy` couldn't be deactivated because `py-scikit-learn` depended on it (both of these were packages I was trying to install). So they weren't random packages, but they were packages that I would like Spack to automatically deactivate and reinstall.

**Comment by scheibelp** [comment]
Can you also include your `spack.yaml`?

**Comment by adamjstewart** [comment]
My `spack.yaml`:
```yaml
spack:
  specs:
  - 'gdal+python'
  - 'python@3:+sqlite3'
  - 'py-earthengine-api'
  - 'py-flake8'
  - 'py-matplotlib'
  - 'py-numpy'
  - 'py-pandas'
  - 'py-pytest@3.9:'
  - 'py-scikit-learn'
  - 'py-scipy@0.14:'
  - 'py-tables'
  - 'py-torch@0.4:'
  - 'py-torchvision'
```
