### ISSUE TITLE
Installation issue: hunspell: autoreconf uses 'libtoolize' instead of 'glibtoolize' on macOS 10.14.6

### ISSUE THREAD

**Issue by goxberry** [spack/spack#12343]
### Steps to reproduce the issue

```console
$ spack install hunspell
==> Executing phase: 'autoreconf'
==> [2019-08-08-14:30:07.109776] Warning: *********************************************************
==> [2019-08-08-14:30:07.110472] Warning: * If the default procedure fails, consider implementing *
==> [2019-08-08-14:30:07.111416] Warning: *        a custom AUTORECONF phase in the package       *
==> [2019-08-08-14:30:07.112193] Warning: *********************************************************
==> [2019-08-08-14:30:07.113555] '/usr/local/opt/libtool/bin/libtoolize'
==> [2019-08-08-14:30:07.108623] Configure script not found: trying to generate it
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux nuvolari 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
``` 
and, if relevant, post or attach:

- `packages.yaml`:

```yaml
packages:
  autoconf:
    paths:
      autoconf@2.69 %clang@10.0.1-apple: /usr/local/opt/autoconf
  automake:
    paths:
      automake@1.16.1 %clang@10.0.1-apple: /usr/local/opt/automake
  libtool:
    paths:
      libtool@2.4.6 %clang@10.0.1-apple: /usr/local/opt/libtool
  m4:
    paths:
      m4@1.4.18 %clang@10.0.1-apple: /usr/local/opt/m4
```

### Additional information

I'm fairly confident the issue here is due to https://github.com/spack/spack/blob/3bd854f991305abaa54d8b7f4ab804aac80ae7b4/lib/spack/spack/build_systems/autotools.py#L196, which seems to call `libtoolize` explicitly via `spec['libtool'].prefix.bin.join('libtoolize')`.

The `packages.yaml` configuration above uses a Homebrew installation of libtool prefixed at `/usr/local/opt/libtool`. Homebrew installs the `libtoolize` executable using the name `glibtoolize` instead, to avoid conflicting with BSD libtool on some versions of macOS. So, on my system, `spec['libtool'].prefix.bin.join('libtoolize')`resolves to `/usr/local/opt/libtool/bin/libtoolize`, which doesn't exist on my system. Any Spack user on macOS who installs `libtool` via Homebrew and adds that `libtool` installation to one of their `packages.yaml` files will encounter this issue. However, executing `autoreconf` invokes `glibtoolize` on my system, as it is supposed to. I'll note here the irony here of the well-intentioned comment at https://github.com/spack/spack/blob/3bd854f991305abaa54d8b7f4ab804aac80ae7b4/lib/spack/spack/build_systems/autotools.py#L194, just above this `libtoolize` invocation: "This part should be redundant in principle, but won't hurt".

Below the `libtoolize` call, there is also a call to `aclocal`, which is now considered bad practice because GNU Automake is deprecating `aclocal`; see https://www.gnu.org/software/automake/manual/automake.html#Future-of-aclocal. The GNU Automake maintainers recommend calling `autoreconf` instead.

While the Spack error message recommends writing a custom `autoreconf` phase for this package, the implementation would be

```python
 def autoreconf(self, spec, prefix):
        autoreconf = which('autoreconf')
        autoreconf('-fiv')
```

which seems, well, silly -- the default implementation is already calling `autoreconf` plus additional arguments, and should work just fine. So I'll be filing a PR to change the Autotools base package instead.
