### ISSUE TITLE
Installation issue: netcdf

### ISSUE THREAD

**Issue by omsai** [spack/spack#12667]
Looks like a parallel build failure bug?  Works once I run `spack -d install -j 1 $spec`

### Steps to reproduce the issue

```console
$ spack install ioapi ^netcdf+parallel-netcdf % gcc@9.1.0
...
==> Installing netcdf
==> Searching for binary cache of netcdf
==> Warning: No Spack mirrors are currently configured
==> No binary for netcdf found: installing from source
==> Fetching https://www.gfd-dennou.org/arch/netcdf/unidata-mirror/netcdf-c-4.7.0.tar.gz
######################################################################## 100.0%
==> Fetching https://github.com/Unidata/netcdf-c/commit/e5315da1e748dc541d50796fb05233da65e86b6b.patch
######################################################################## 100.0%
==> Staging archive: /tmp/spack-stage/yul18051/netcdf-4.7.0-37sfmh5bvahdgrqfheudxoramuaehq74/netcdf-c-4.7.0.tar.gz
==> Created stage in /tmp/spack-stage/yul18051/netcdf-4.7.0-37sfmh5bvahdgrqfheudxoramuaehq74
The text leading up to this was:
--------------------------
|commit 13e70b397dcb0d1bf4a869b670f041c1d7b730d0
|Author: Björn Esser <besser82@fedoraproject.org>
|Date:   Sat Jan 20 20:22:53 2018 +0100
|
|    pp: Guard fix for really old bug in glibc libcrypt
|
|diff --git a/pp.c b/pp.c
|index d50ad7ddbf..6510c7b15c 100644
|--- a/pp.c
|+++ b/pp.c
--------------------------
File to patch:
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux cn01 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Nov 23 16:03:01 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Red Hat Enterprise Linux Server release 6.7 (Santiago)
``` 
and, if relevant, post or attach:

```yaml
# compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /home/yul18051/src/cmaq/5.2.1/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/gcc-9.1.0-ypwshntn6jtaq2dvhaf5tnn6fw6ayzkj/bin/gcc
      cxx: /home/yul18051/src/cmaq/5.2.1/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/gcc-9.1.0-ypwshntn6jtaq2dvhaf5tnn6fw6ayzkj/bin/g++
      f77: /home/yul18051/src/cmaq/5.2.1/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/gcc-9.1.0-ypwshntn6jtaq2dvhaf5tnn6fw6ayzkj/bin/gfortran
      fc: /home/yul18051/src/cmaq/5.2.1/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/gcc-9.1.0-ypwshntn6jtaq2dvhaf5tnn6fw6ayzkj/bin/gfortran
    spec: gcc@9.1.0
    target: x86_64
```

to the issue

### Additional information

Sometimes the issue benefits from additional details. In these cases there are
a few things we can suggest doing. First of all, you can post the full output of:
```console
$ spack spec --install-status ioapi ^netcdf+parallel-netcdf % gcc@9.1.0
Input spec
--------------------------------
 -   ioapi
 -       ^netcdf%gcc@9.1.0+parallel-netcdf

Concretized
--------------------------------
 -   ioapi@3.2%gcc@9.1.0 arch=linux-rhel6-x86_64
 -       ^netcdf@4.7.0%gcc@9.1.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi+parallel-netcdf patches=10a1c3f7fa05e2c82457482e272bbe04d66d0047b237ad0a73e87d63d848b16c +pic+shared arch=linux-rhel6-x86_64
[+]          ^autoconf@2.69%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]              ^m4@1.4.18%gcc@9.1.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-rhel6-x86_64
[+]                  ^libsigsegv@2.11%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]              ^perl@5.26.2%gcc@9.1.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-rhel6-x86_64
[+]                  ^gdbm@1.18.1%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                      ^readline@7.0%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                          ^ncurses@6.1%gcc@9.1.0~symlinks~termlib arch=linux-rhel6-x86_64
[+]                              ^pkgconf@1.6.1%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]          ^automake@1.16.1%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]          ^hdf5@1.10.5%gcc@9.1.0~cxx~debug~fortran+hl+mpi patches=b61e2f058964ad85be6ee5ecea10080bf79e73f83ff88d1fa4b602d00209da9c +pic+shared~szip~threadsafe arch=linux-rhel6-x86_64
[+]              ^openmpi@3.1.4%gcc@9.1.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-rhel6-x86_64
[+]                  ^hwloc@1.11.11%gcc@9.1.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-rhel6-x86_64
[+]                      ^libpciaccess@0.13.5%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                          ^libtool@2.4.6%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                          ^util-macros@1.19.1%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                      ^libxml2@2.9.9%gcc@9.1.0~python arch=linux-rhel6-x86_64
[+]                          ^libiconv@1.15%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                          ^xz@5.2.4%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]                          ^zlib@1.2.11%gcc@9.1.0+optimize+pic+shared arch=linux-rhel6-x86_64
[+]                      ^numactl@2.0.12%gcc@9.1.0 arch=linux-rhel6-x86_64
[+]          ^parallel-netcdf@1.11.2%gcc@9.1.0+cxx+fortran+pic arch=linux-rhel6-x86_64
 -       ^netcdf-fortran@4.4.5%gcc@9.1.0+pic arch=linux-rhel6-x86_64
 -       ^sed@4.2.2%gcc@9.1.0 arch=linux-rhel6-x86_64
```

```console
$ spack -d install -j 1 <spec>
# Apparently when I run this it works!?
```
