### ISSUE TITLE
Help needed on how to use intel-mpi in intel-parallel-studio installed within Spack

### ISSUE THREAD

**Issue by huqy** [spack/spack#12830]
Hello, 

I followed the instruction "[Installing Intel tools within Spack](https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html?highlight=intel#installing-intel-tools-within-spack)" installed `intel-parallel-studio/cluster.2018.3` successfully. But I wasn't able to make Spack select intel-mpi package in the studio. Here are what I tried: 

---

### Without configuring packages.yaml:

```console
$ spack spec fftw %intel ^intel-mpi
Input spec
--------------------------------
fftw%intel
    ^intel-mpi

Concretized
--------------------------------
fftw@3.3.8%intel@18.0.3+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-centos6-x86_64
    ^intel-mpi@2019.0.117%intel@18.0.3 arch=linux-centos6-x86_64
```

### With configuring packages.yaml

- `packages.yaml` as suggested in the [doc](https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html?highlight=intel#selecting-libraries-to-satisfy-virtual-packages):

```console
packages:
    all:
        compiler: [intel, gcc]
        providers:
            mpi: [intel-parallel-studio+mpi, openmpi, mpich]
            blas: [intel-parallel-studio+mkl, openblas]
            lapack: [intel-parallel-studio+mkl, openblas]
            scalapack: [intel-parallel-studio+mkl, openblas]
```

It reports the error when concretized:
 
```console
$ spack spec fftw
Input spec
--------------------------------
fftw

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "fftw@3.3.8%intel@18.0.3+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-centos6-x86_64 /2h5m425"

List of matching conflicts for spec:

    intel-parallel-studio@professional.2018.3%intel@18.0.3~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb threads=none ~vtune arch=linux-centos6-x86_64

1. "+mpi" conflicts with "intel-parallel-studio@professional.0:professional.9999"

``` 

I tried with adding the section of intel-parallel-studio section in `packages.yaml` as suggested in the [#11950](https://github.com/spack/spack/issues/11950) like below: 

```console
    intel-parallel-studio:
        paths:
            intel-parallel-studio@cluster.2018.3.222 +mkl+mpi+ipp+tbb+daal: /path/to/intel
        buildable: False
```
It reports the same error.

---

Any hints? Thanks.

**Comment by adamjstewart** [comment]
A few comments to help you understand the situation:

1. Spack has an idea of "virtual packages". That is, a package like FFTW can _require_ a virtual dependency on MPI, but many different packages can _provide_ MPI (mvapich2, mpich, openmpi, intel-mpi, etc)

2. The Intel ecosystem in Spack is a bit complex. `intel-mpi` is a completely different package than `intel-parallel-studio+mpi`, although both _provide_ MPI. 

3. The _professional_ and _composer_ versions of `intel-parallel-studio` do not come with Intel MPI support, only the _cluster_ version does

Try something like this:
```yaml
packages:
    all:
        compiler: [intel, gcc]
        providers:
            mpi: [intel-parallel-studio@cluster.2018.3.222+mpi, openmpi, mpich]
            blas: [intel-parallel-studio@cluster.2018.3.222+mkl, openblas]
            lapack: [intel-parallel-studio@cluster.2018.3.222+mkl, openblas]
            scalapack: [intel-parallel-studio@cluster.2018.3.222+mkl, openblas]
    intel-parallel-studio:
        paths:
            intel-parallel-studio@cluster.2018.3.222 +mkl+mpi+ipp+tbb+daal: /path/to/intel
        buildable: False
```
This tells Spack that you have the cluster version installed, and tells Spack that you want to use that version and that version only as an MPI dependency.

If that doesn't work, let me know.
