### ISSUE TITLE
Enable putting "target=xxxx" in the config.yaml file

### ISSUE THREAD

**Issue by martyitz** [spack/spack#12969]
If one is building on an x86 machine for a site which has many different chips,
it would be best to install all shared software built for the x86_64 architecture.
Currently that means adding a target clause on each install.  It would be more
graceful if the target could be specified in the config.yaml file

**Comment by tgamblin** [comment]
@martyitz: you can already do this, but not in `config.yaml`.  You can do it for all packages or per-package in `packages.yaml`:

```yaml
packages:
    cmake:
        target: ['x86_64']
    all:
        target: ['haswell']
```

Note you can do that in an [environment](https://spack.readthedocs.io/en/latest/environments.html) (`spack.yaml` file) too.

@alazo: can you add this to the docs?
