### ISSUE TITLE
Native support for clang+gfortran when spack builds both llvm and gcc would be nice

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#13204]
CC: @fryeguy52

## Feature request

Can spack be updated to automatically provide `f77` and `fc` in generated `compilers.yaml` file when it sets up the block for `clang@<version>` using the matching Fortran compiler used to build the `llvm@<version>` package?  That would save people from having to manually post-modify the file `compilers.yaml` after the block:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: <clang-path>/bin/clang
      cxx: <clang-path>/bin/clang++
      f77: null
      fc: null
    spec: clang@5.0.1
    target: x86_64
```

was added by `spack find compilers` to be:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: <clang-path>/bin/clang
      cxx: <clang-path>/bin/clang++
      f77: <gcc-path>/bin/gfortran
      fc: <gcc-path>/bin/gfortran
    spec: clang@5.0.1
    target: x86_64
```

At least provide an option to do this or something so users don't have to script this themselves.

## Related issues:

#5665, #5717, #3426, #3427

## Background

In order build a viable clang-based stack of MPI and TPLs for SNL ATDM codes, it seems we need to  to use GCC to build OpenMPI and many of our TPLs (e.g. HDF5) and our ATDM codes require a Fortran compiler.   For my current concrete use case (trying to replicate an existing stack of compilers, MPI and TPLs for ATDM), I have worked out an approach for doing this that involves:

1) Build the gcc@4.9.3 compiler with Spack (using native gcc@4.4.7 on RHEL6)
2) use gcc@4.9.3 to build llvm@5.0.1 (to get clang@5.0.1 `clang++` and `clang` compilers)
3) Use gcc@4.9.3 to build openmpi@1.10.2 (can't build openmpi@1.10.2 with clang@5.0.1, it fails and the existing use case I am trying to match is using gcc@4.9.3, not clang)
4) Use  `clang++` and `clang` from llvm@5.0.1 and `gfortran` from gcc@4.9.3 to build the TPLs including HDF5 (which needs Fortran).

In order to pull this off, I have had to do quite a bit of scripting.  Most of that scripting is pretty straightforward.  However, one irritating part is having to modify the generated file `compilers.yaml` to replace `f77: null` AND `fc: null` with
