### ISSUE TITLE
buildcache create ends without finishing, gives Warning: 'Name' object has no attribute 's'

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#13237]
Edit: Here is the output of running the buildcache create command with debug flag:
```spack -d buildcache create ... ```
LOG HERE ---> [bc_create.log](https://github.com/spack/spack/files/3744784/bc_create.log)

@becker33

`spack buildcache create` sometimes fails to finish, giving the warning shown below. I have only observed this with a small set of packages, which I will attach below -- the use case is the same for each of the packages in the list. First I install from a concrete spec yaml file:
```
$> spack install --no-cache --overwrite -y -f /hostmount/spack-env/llvm_nlxngt.spec.yaml
```

Then I try to cache the package and the following Warning is given:
```
$> spack buildcache create --no-deps -afr -d /hostmount -k prl -y /hostmount/spack-env/llvm_nlxngt.spec.yaml
==> Warning: 'Name' object has no attribute 's'
==> createtarball, reading spec from /hostmount/spack-env/llvm_nlxngt.spec.yaml
==> creating binary cache file for package llvm@9.0.0%gcc@7.3.0~all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb~omp_tsan+polly~python~shared_libs arch=linux-rhel7-x86_64
```

At this point, if you check `build_cache` directory, you will find a directory entry `gcc-7.3.0/llvm-9.0.0` and it will contain a .tar.gz file. No .spec.yaml file is created for llvm as one would expect under build_cache/

I've attached the exact llvm concretized .spec.yaml file below.

Other packages where I have observed this:
* mesa@18.3.6%gcc@7.3.0+glx+llvm+opengl~opengles+osmesa
* swig@4.0.0%gcc@7.3.0 
* lvm@8.0.0%gcc@7.3.0~all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb~omp_tsan 
* flang@20180921
* qwt@6.1.3%gcc@7.3.0~designer 
* qt@5.11.3%gcc@7.3.0~dbus~examples~framework freetype=spack ~gtk~krellpatch+opengl 
* catalyst@5.6.0%gcc@7.3.0
* glew@2.0.0%gcc@7.3.0

llvm_nlxngt.spec.yaml:
```
spec:
- llvm:
    version: 9.0.0
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      all_targets: false
      build_type: Release
      clang: true
      compiler-rt: true
      gold: true
      internal_unwind: true
      libcxx: true
      link_dylib: false
      lld: true
      lldb: true
      omp_tsan: false
      polly: true
      python: false
      shared_libs: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      binutils:
        hash: k5hdtpm2rtp6rzsidirns6gcyjqvyogt
        type:
        - build
        - link
      cmake:
        hash: y6txq3ykldssamyxuyvf6kzhdabawy5a
        type:
        - build
      libedit:
        hash: smthqopkg4tlnqnv3sfj5iyasd4rd467
        type:
        - build
        - link
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
      perl-data-dumper:
        hash: k2psjsodfsptekyb76jt6polar5cczhq
        type:
        - build
      python:
        hash: s7gu7ihz54ho442c25pnc6htm3i6vuus
        type:
        - build
      swig:
        hash: hunbwpumk3l7tonromnialk5ilzr532h
        type:
        - build
        - link
    hash: ooz4vxb7qaeoh2jogwwlkbolwczzglwo
    build_hash: nlxngtqnnbjjytyola34ntmy3pk6ibrz
- binutils:
    version: '2.32'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      gold: true
      headers: false
      libiberty: false
      nls: true
      plugins: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      gettext:
        hash: jqj7dlxxfo55zgq5me42mum5vyd32pqv
        type:
        - build
        - link
      zlib:
        hash: ldu43taplg2nbkxtem346zq4ibhad64i
        type:
        - build
        - link
    hash: oeg4auwjda3cn5y44ogveghnwj7bbb5b
    build_hash: k5hdtpm2rtp6rzsidirns6gcyjqvyogt
- gettext:
    version: 0.19.8.1
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      bzip2: true
      curses: true
      git: true
      libunistring: false
      libxml2: true
      patches:
      - 9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8
      tar: true
      xz: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    patches:
    - 9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8
    dependencies:
      bzip2:
        hash: 7zzahiwteusf7fwhp4htotoiuiykdpxq
        type:
        - build
        - link
      libxml2:
        hash: m7hhthrvmpapo4tkiarkhkqacxnikdzs
        type:
        - build
        - link
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
      tar:
        hash: 5ydwzw64c2cnwq5qk4foiwczgv2cpdnj
        type:
        - build
        - link
      xz:
        hash: 52pq7xrp2axthcs4pcn34ha5g6vwfuy5
        type:
        - build
        - link
        - run
    hash: g4b3z4ks3mbhxrxa274jzurpkdwcc4eh
    build_hash: jqj7dlxxfo55zgq5me42mum5vyd32pqv
- bzip2:
    version: 1.0.8
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      shared: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      diffutils:
        hash: 3e3nwr6wfitdrqvocayfqkypamquao5e
        type:
        - build
    hash: 7dgdglgrxgkjr6pqjnf73diprndokh4c
    build_hash: 7zzahiwteusf7fwhp4htotoiuiykdpxq
- diffutils:
    version: '3.7'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      libiconv:
        hash: tisngyii2rqgu6uvwwno4ji7i4ypijh2
        type:
        - build
        - link
    hash: 3e3nwr6wfitdrqvocayfqkypamquao5e
    build_hash: 3e3nwr6wfitdrqvocayfqkypamquao5e
- libiconv:
    version: '1.15'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: tisngyii2rqgu6uvwwno4ji7i4ypijh2
    build_hash: tisngyii2rqgu6uvwwno4ji7i4ypijh2
- libxml2:
    version: 2.9.9
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      python: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      libiconv:
        hash: tisngyii2rqgu6uvwwno4ji7i4ypijh2
        type:
        - build
        - link
      pkgconf:
        hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
        type:
        - build
      xz:
        hash: 52pq7xrp2axthcs4pcn34ha5g6vwfuy5
        type:
        - build
        - link
      zlib:
        hash: ldu43taplg2nbkxtem346zq4ibhad64i
        type:
        - build
        - link
    hash: sejmw3qjl2ncl3wzb4rhlo6ypdj7ze5z
    build_hash: m7hhthrvmpapo4tkiarkhkqacxnikdzs
- pkgconf:
    version: 1.6.1
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
    build_hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
- xz:
    version: 5.2.4
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: 52pq7xrp2axthcs4pcn34ha5g6vwfuy5
    build_hash: 52pq7xrp2axthcs4pcn34ha5g6vwfuy5
- zlib:
    version: 1.2.11
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      optimize: true
      pic: true
      shared: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: ldu43taplg2nbkxtem346zq4ibhad64i
    build_hash: ldu43taplg2nbkxtem346zq4ibhad64i
- ncurses:
    version: '6.1'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      symlinks: false
      termlib: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      pkgconf:
        hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
        type:
        - build
    hash: i6zkr74nebgmb6meyzexi4sg62qhnarp
    build_hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
- tar:
    version: '1.31'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: 5ydwzw64c2cnwq5qk4foiwczgv2cpdnj
    build_hash: 5ydwzw64c2cnwq5qk4foiwczgv2cpdnj
- cmake:
    version: 3.15.3
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      doc: false
      ncurses: true
      openssl: true
      ownlibs: true
      qt: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
      openssl:
        hash: 3d7h7mj2c3rvj6owksm7y6bjhudx2mdk
        type:
        - build
        - link
    hash: phicfpngfape3lnbrmipumntusjd2x77
    build_hash: y6txq3ykldssamyxuyvf6kzhdabawy5a
- openssl:
    version: 1.1.1c
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      systemcerts: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      perl:
        hash: fub3nmdugvhbmwiws4p32yathgl2dx7o
        type:
        - build
        - test
      zlib:
        hash: ldu43taplg2nbkxtem346zq4ibhad64i
        type:
        - build
        - link
    hash: v3yefyzyio4ltv6wsle5rff5dh3va6as
    build_hash: 3d7h7mj2c3rvj6owksm7y6bjhudx2mdk
- perl:
    version: 5.26.2
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cpanm: true
      patches:
      - 0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac
      shared: true
      threads: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    patches:
    - 0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac
    dependencies:
      gdbm:
        hash: tnhmrbreptwcxdl3uqfqbnmjrlet5ypx
        type:
        - build
        - link
    hash: c2rbjgnb5u7yybfnd64xc2bkfgrbhx6t
    build_hash: fub3nmdugvhbmwiws4p32yathgl2dx7o
- gdbm:
    version: 1.18.1
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      readline:
        hash: 7wsc3bp6lc3picrpbyk6ezgpyzdf325z
        type:
        - build
        - link
    hash: atuwrwr5arr5ywd4wzs5fztmk7aunti2
    build_hash: tnhmrbreptwcxdl3uqfqbnmjrlet5ypx
- readline:
    version: '7.0'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
    hash: iomtztdr32lxjensxi5jtwfpugjgbr7w
    build_hash: 7wsc3bp6lc3picrpbyk6ezgpyzdf325z
- libedit:
    version: 3.1-20170329
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
    hash: hsuvslbfjpclkq2mkxaakazsuexywkgs
    build_hash: smthqopkg4tlnqnv3sfj5iyasd4rd467
- perl-data-dumper:
    version: '2.173'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      perl:
        hash: fub3nmdugvhbmwiws4p32yathgl2dx7o
        type:
        - build
        - link
        - run
    hash: bnf2sj6aqlm3op6ermtmdgecglksco3t
    build_hash: k2psjsodfsptekyb76jt6polar5cczhq
- python:
    version: 2.7.16
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      bz2: true
      ctypes: true
      dbm: true
      lzma: true
      nis: false
      optimizations: false
      pic: true
      pyexpat: true
      pythoncmd: true
      readline: true
      shared: true
      sqlite3: true
      ssl: true
      tix: false
      tkinter: false
      ucs4: false
      uuid: false
      zlib: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      bzip2:
        hash: 7zzahiwteusf7fwhp4htotoiuiykdpxq
        type:
        - build
        - link
      expat:
        hash: oj46f5jzj7sifwx3owxgj2k2vptqphnm
        type:
        - build
        - link
      gdbm:
        hash: tnhmrbreptwcxdl3uqfqbnmjrlet5ypx
        type:
        - build
        - link
      gettext:
        hash: jqj7dlxxfo55zgq5me42mum5vyd32pqv
        type:
        - build
        - link
      libffi:
        hash: 23pznc42nxucd4aymz5mf4yfhprg2zam
        type:
        - build
        - link
      ncurses:
        hash: 37z4e5ayltdbfnukuel4vdbxm3uk7lqw
        type:
        - build
        - link
      openssl:
        hash: 3d7h7mj2c3rvj6owksm7y6bjhudx2mdk
        type:
        - build
        - link
      pkgconf:
        hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
        type:
        - build
      readline:
        hash: 7wsc3bp6lc3picrpbyk6ezgpyzdf325z
        type:
        - build
        - link
      sqlite:
        hash: mrizk5x23n4lcnxrmlga3sqlpqiyq763
        type:
        - build
        - link
      zlib:
        hash: ldu43taplg2nbkxtem346zq4ibhad64i
        type:
        - build
        - link
    hash: v4jof2rpqfyqzt3vgtnm4zpwncgdywbb
    build_hash: s7gu7ihz54ho442c25pnc6htm3i6vuus
- expat:
    version: 2.2.5
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      libbsd: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      libbsd:
        hash: kl3szpzehwn23t7uztplyni46mj4yr6r
        type:
        - build
        - link
    hash: oj46f5jzj7sifwx3owxgj2k2vptqphnm
    build_hash: oj46f5jzj7sifwx3owxgj2k2vptqphnm
- libbsd:
    version: 0.9.1
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: kl3szpzehwn23t7uztplyni46mj4yr6r
    build_hash: kl3szpzehwn23t7uztplyni46mj4yr6r
- libffi:
    version: 3.2.1
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: 23pznc42nxucd4aymz5mf4yfhprg2zam
    build_hash: 23pznc42nxucd4aymz5mf4yfhprg2zam
- sqlite:
    version: 3.29.0
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      column_metadata: false
      fts: true
      functions: false
      rtree: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      readline:
        hash: 7wsc3bp6lc3picrpbyk6ezgpyzdf325z
        type:
        - build
        - link
      zlib:
        hash: ldu43taplg2nbkxtem346zq4ibhad64i
        type:
        - build
        - link
    hash: weqsz23ippslxmkpmsayoqt6hyutazo2
    build_hash: mrizk5x23n4lcnxrmlga3sqlpqiyq763
- swig:
    version: 4.0.0
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      pcre:
        hash: lpbkhhnurtvzuaome72xi6znkdjzmt2d
        type:
        - build
        - link
      pkgconf:
        hash: 7mp3movko767rt7gxskkeuhm7cfcdqrk
        type:
        - build
    hash: pyot7i3f3qx4mbeobr4ahnvtu2jfxe64
    build_hash: hunbwpumk3l7tonromnialk5ilzr532h
- pcre:
    version: '8.42'
    arch:
      platform: linux
      platform_os: rhel7
      target: x86_64
    compiler:
      name: gcc
      version: 7.3.0
    namespace: builtin
    parameters:
      jit: false
      multibyte: true
      utf: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: lpbkhhnurtvzuaome72xi6znkdjzmt2d
    build_hash: lpbkhhnurtvzuaome72xi6znkdjzmt2d
```
