### ISSUE TITLE
Variable expansion in package lists for view definitions

### ISSUE THREAD

**Issue by nicholas-sly** [spack/spack#13409]
Provide the ability to reference named dictionaries/lists/etc when specifying specs for inclusion in views.

### Rationale

When building out a large environment using the Spack Stacks capability, having these lists defined in a central named structure allows for consistency across several places that it can be useful (defining the overall spec as well as the views in which they will be found).

### Description

```yaml
spack:
  ...
  view:
    # Should be portable across all systems?
    common:
      root: /install/location/common
      select: $base_packages
      projections:
        all: "{name}/{version}"
    toss:
      root: /install/location/toss
      select: $2019Q4-toolchain-compiler
      projections:
        all: "{name}/{version}"
```

In the above snippet, 'base_packages' and '2019Q4-toolchain-compiler' are lists including fully defined specs for the products that should be installed and placed in these respective views.  Instead of this, which is the desired format, a copy of the contents of those variables must be placed underneath the 'select' key.
