### ISSUE TITLE
Cannot override compilers inside an environment

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#13442]
TLDR: `with cfg.override('compilers:', actual_compilers):` does not seem actually to override the compilers inside a spack environment.

When running pipelines that are intended to bootstrap a missing compiler, we have typically added the compiler we want to the spack environment, substituting empty strings for all the paths.  This allows us to "cross-concretize" the specs against that compiler even if the system where we concretize doesn't actually have that compiler.

Now we are attempting to build that compiler and it's dependencies within the environment where we have listed it only for cross-concretization purposes, but it's getting picked as the compiler to build with.  For example, say my release environment wants to build:

```
bzip2@1.0.8@gcc@5.5.0 os=centos7
```

But I'm sure the machine where I want to build that doesn't have `gcc@5.5.0`, so I put it in my environment like this:

```
compilers:
    - compiler:
        spec: gcc@5.5.0
        target: x86_64
        operating_system: centos7
        paths: { "cc": "", "cxx": "", "f77": "", "fc": "" }
        environment: {}
        extra_rpaths: []
        flags: {}
        modules: []
```

And that allows me to concretize `bzip2` with the right compiler.  Then I'll add `gcc@5.5.0` as a compiler to bootstrapped in that environment (within the `gitlab-ci` section).  When I'm concretizing `gcc@5.5.0` to be able to stage it and all it's dependencies in the bootstrapping portion of the pipeline, I want spack to use whatever compiler is available on that machine to build `gcc@5.5.0`, so I try to explicitly override the compilers configuration to remove the compiler I know I only put there for cross-concretization, so that spack chooses an actual compiler on the system with which to build `gcc@5.5.0`.  This is happening in python and looks something like:

```python
import spack.config as cfg
from spack.spec import Spec
real_compilers = [{'compiler': {'environment': {}, 'extra_rpaths': [], 'flags': {}, 'implicit_rpaths': [], 'modules': [], 'operating_system': 'centos7', 'paths': {'cc': '/bin/gcc', 'cxx': '/bin/g++', 'f77': '/bin/gfortran', 'fc': '/bin/gfortran'}, 'spec': 'gcc@4.8.5', 'target': 'x86_64'}}]
with cfg.override('compilers:', real_compilers):
    s = Spec('gcc@5.5.0')
    s.concretize()
```

And what I get back is something like `gcc@5.5.0%gcc@5.5.0...`, which is not what I wanted.  So I feel it may be a bug that I cannot completely override the compiler config from within the environment.

### Steps to reproduce the issue

This is most easily and reliably reproduced in a docker container where the installed compilers are known.  

1. Start by putting the following `spack.yaml` into a directory (e.g. `/tmp/reproduce`):

```
spack:
  specs: [bzip2@1.0.8 os=centos7]
  mirrors: {mirror: 's3://spack-private/mirror'}
  gitlab-ci:
    mappings:
    - match: [os=centos7]
      runner-attributes:
        image:
          name: spack/centos7
          entrypoint: ['']
        tags: [docker]
        variables: {}
  compilers:
    - compiler:
        spec: gcc@5.5.0
        target: x86_64
        operating_system: centos7
        paths: { "cc": "", "cxx": "", "f77": "", "fc": "" }
        environment: {}
        extra_rpaths: []
        flags: {}
        modules: []
  repos: []
  upstreams: {}
  modules:
    enable: []
  packages: {}
  config: {}
```

2. In the same directory clone spack and make sure the latest `develop` branch is checked out.

3. Run the `spack/centos7` docker container, mounting that directory as `/work`:

```console
$ docker run --rm --entrypoint /bin/bash -v /tmp/reproduce:/work -ti spack/centos7
[root@ba3e3475c3c6 ~]# 
```

4. Change into the environment directory and source the newly cloned spack:

```console
[root@ba3e3475c3c6 ~]# cd /work/                
[root@ba3e3475c3c6 work]# source spack/share/spack/setup-env.sh
```

5. Now run a spack python session and try to manually override the compilers:

```console
[root@ba3e3475c3c6 work]# spack python
Spack version 0.12.1
Python 2.7.5, Linux x86_64
>>> import spack.config as cfg
>>> from spack.spec import Spec
>>> real_compilers = [{'compiler': {'environment': {}, 'extra_rpaths': [], 'flags': {}, 'implicit_rpaths': [], 'modules': [], 'operating_system': 'centos7', 'paths': {'cc': '/bin/gcc', 'cxx': '/bin/g++', 'f77': '/bin/gfortran', 'fc': '/bin/gfortran'}, 'spec': 'gcc@4.8.5', 'target': 'x86_64'}}]
>>> with cfg.override('compilers:', real_compilers):
...     s = Spec('gcc@5.5.0')
...     s.concretize() 
...     print(s)
... 
gcc@5.5.0%gcc@5.5.0...
>>>
```

Please let me know if more information is required.  Using the same docker container should allow faithful reproduction without worrying about different system configs.
