### ISSUE TITLE
Print or log a warning when downgrading targets

### ISSUE THREAD

**Issue by alalazo** [spack/spack#13482]
As a user I would like a warning to be either printed to screen or logged somewhere in debug mode when targets are downgraded by Spack so that I can spot deviations from the preferences expressed in e.g. configuration files more easily

### Rationale

Following a discussion happened on public Spack's slack in the #general channel. A `spack.yaml` file like the following:
```yaml
spack:
  specs:
  - mvapich2 fabrics=mrail
  packages:
    openssl:
      buildable: false
      paths:
        openssl@1.0.2: /usr
    all:
      target: [skylake-avx512]
  concretization: together
```
was causing all the specs to concretize as `x86_64`. This is because there's a typo in the preferred target that contains a dash where it should have an underscore i.e. `skylake_avx512`. 

What was happening is that Spack was falling back to a safe target after having tried to use a "non-existing" preference. Being a typo the error was hard to spot and probably it would have been much easier to debug if Spack prompted a visible warning about its decision to downgrade the target.

### Description

Make it such that Spack prompts a warning when it decides to downgrade targets. The warning should be as informative as possible on where and why this decision was taken.

### Additional information
No additional information
