### ISSUE TITLE
Autoload direct in modules.yaml does not work

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#13590]
I'm using the following `modules.yaml`:
```yaml
modules:
    enable::
        # Only generate TCL environment module files
        - tcl
    tcl:
        # Ignore compiler and compiler version in module file name
        naming_scheme: '${PACKAGE}/${VERSION}'
        # Automatically load modules for Java and Python dependencies
        ^java:
              autoload: 'direct'
        ^python:
              autoload: 'direct'
```
However, the Python packages I build don't autoload anything in their module files.
```console
$ module show py-torch
-------------------------------------------------------------------
/u/sciteam/stewart1/spack/share/spack/modules/cray-cnl5-interlagos/py-torch/1.3.0/l7hawiz:

module-whatis	 Tensors and Dynamic neural networks in Python with strong GPU acceleration. 
prepend-path	 PATH /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-5.3.0/py-torch-1.3.0-l7hawizlfcdrn532yv3qagdcwkarsnbi/bin 
prepend-path	 LIBRARY_PATH /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-5.3.0/py-torch-1.3.0-l7hawizlfcdrn532yv3qagdcwkarsnbi/lib 
prepend-path	 CMAKE_PREFIX_PATH /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-5.3.0/py-torch-1.3.0-l7hawizlfcdrn532yv3qagdcwkarsnbi/ 
prepend-path	 PYTHONPATH /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-5.3.0/py-torch-1.3.0-l7hawizlfcdrn532yv3qagdcwkarsnbi/lib/python3.7/site-packages 
-------------------------------------------------------------------
```
Ideally, #8639 would make these settings obsolete, but until then I need some way of loading dependencies for Python libraries.

**Comment by alalazo** [comment]
Can't reproduce. I used this `spack.yaml`:
```yaml
spack:
  specs:
  - python@3.7:+sqlite3
  - py-flake8
  - py-numpy
  modules:
    tcl:
      ^python:
        autoload: direct
  concretization: together
  view: False
```
After installing I get:
```console
spack module tcl find --full-path py-flake8
/home/culpo/PycharmProjects/spack/share/spack/modules/linux-ubuntu18.04-broadwell/py-flake8-3.7.8-gcc-9.0.1-qt3acb6
```
and the content is:
```tcl
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-11-05 11:51:17.583523
##
## py-flake8@3.7.8%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell/qt3acb6
##


module-whatis "Flake8 is a wrapper around PyFlakes, pep8 and Ned Batchelder's McCabe script."

proc ModulesHelp { } {
puts stderr "Flake8 is a wrapper around PyFlakes, pep8 and Ned Batchelder's McCabe"
puts stderr "script."
}

if { [ module-info mode load ] && ![ is-loaded py-entrypoints-0.3-gcc-9.0.1-jtienqn ] } {
    module load py-entrypoints-0.3-gcc-9.0.1-jtienqn
}
if { [ module-info mode load ] && ![ is-loaded py-mccabe-0.6.1-gcc-9.0.1-teprndv ] } {
    module load py-mccabe-0.6.1-gcc-9.0.1-teprndv
}
if { [ module-info mode load ] && ![ is-loaded py-pycodestyle-2.5.0-gcc-9.0.1-6vw5gac ] } {
    module load py-pycodestyle-2.5.0-gcc-9.0.1-6vw5gac
}
if { [ module-info mode load ] && ![ is-loaded py-pyflakes-2.1.1-gcc-9.0.1-oskzzyz ] } {
    module load py-pyflakes-2.1.1-gcc-9.0.1-oskzzyz
}
if { [ module-info mode load ] && ![ is-loaded py-setuptools-41.4.0-gcc-9.0.1-m3midf4 ] } {
    module load py-setuptools-41.4.0-gcc-9.0.1-m3midf4
}
if { [ module-info mode load ] && ![ is-loaded python-3.7.4-gcc-9.0.1-4zkul3b ] } {
    module load python-3.7.4-gcc-9.0.1-4zkul3b
}

prepend-path PATH "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/py-flake8-3.7.8-qt3acb6qx7xorq5u4colhndyojrzsmbi/bin"
prepend-path LD_LIBRARY_PATH "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/py-flake8-3.7.8-qt3acb6qx7xorq5u4colhndyojrzsmbi/lib"
prepend-path LIBRARY_PATH "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/py-flake8-3.7.8-qt3acb6qx7xorq5u4colhndyojrzsmbi/lib"
prepend-path CMAKE_PREFIX_PATH "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/py-flake8-3.7.8-qt3acb6qx7xorq5u4colhndyojrzsmbi/"
prepend-path PYTHONPATH "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/py-flake8-3.7.8-qt3acb6qx7xorq5u4colhndyojrzsmbi/lib/python3.7/site-packages"
```
