### ISSUE TITLE
Error: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#13608]
We seem to be hitting the maximum open filehandle limit during `spack env activate`.

### Steps to reproduce the issue

```console
$ spack env activate -d .
```

Interestingly enough, if I use:
```console
$ spack -d env activate -d .
```
I can avoid the bug.

### Error Message

```console
==> Error: filedescriptor out of range in select()
```

### Information on your system

Blue Waters, Cray CNL5, Python 2.6.9

`spack.yaml`:
```yaml
spack:
  specs:
  - 'gdal+python'
  - 'python@3.7:+sqlite3'
  - 'py-flake8'
  - 'py-matplotlib'
  - 'py-numpy'
  - 'py-pandas'
  - 'py-pytest@3.9:'
  - 'py-scikit-learn'
  - 'py-scipy@0.14:'
  - 'py-tables@3.0.0:'
  - 'py-torch@0.4:'
  - 'py-torchvision'
  concretization: together
```

This bug seems to be very intermittent and hard to reproduce...
