### ISSUE TITLE
libiconv won't compile gcc 9.2.0

### ISSUE THREAD

**Issue by ifelsefi** [spack/spack#13662]
Hi

I am trying to install latest R with gcc 9.2.0 though this fails at libivcov.

Operating system:

```
[root@node158 centos7]# uname -a
Linux node158.panda 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Latest code from `develop`:

```
[root@node158 centos7]# git log | head
commit d01a8f7cd69dd26797da3c637829943fa4efd910
Author: Seth R. Johnson <johnsonsr@ornl.gov>
Date:   Sat Nov 9 13:47:04 2019 -0500

    Fix visit+ (#13652)
    
    * Propagate MPI option in VTK to NetCDF
    
    This fixes a conflict message reads as though NetCDF always requires
    hdf5+mpi. It allows `visit~mpi` to resolve correctly without an
```

Nothing changed except compilers:

```
[root@node158 centos7]# git status .
# On branch develop
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       etc/spack/defaults/compilers.yaml
#
# It took 2.80 seconds to enumerate untracked files. 'status -uno'
# may speed it up, but you have to be careful not to forget to add
# new files yourself (see 'git help status').
```

I also added `$SPACK_ROOT/etc/packages.yaml`:

```
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user
  openssl:
       paths:
           openssl@1: /usr
       buildable: False
  slurm:
       paths:
           slurm@17: /usr
       buildable: False
```

`$SPACK_ROOT/etc/spack/compilers.yaml`

```
compilers:
- compiler:
    paths:
      cc: /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/gcc-9.2.0-j2j7q4srcoumcrnyz75gcozagh7zuouj/bin/gcc
      cxx: /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/gcc-9.2.0-j2j7q4srcoumcrnyz75gcozagh7zuouj/bin/g++
      f77: /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/gcc-9.2.0-j2j7q4srcoumcrnyz75gcozagh7zuouj/bin/gfortran
      fc: /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/gcc-9.2.0-j2j7q4srcoumcrnyz75gcozagh7zuouj/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@9.2.0
```

Tried with one thread:

```
spack install -j 1 r+X+memory_profiling %gcc@9.2.0
```

Errors attached!

[spack-build-out.txt](https://github.com/spack/spack/files/3827689/spack-build-out.txt)
