### ISSUE TITLE
Module Names without Hashes

### ISSUE THREAD

**Issue by citibeth** [spack/spack#13726]
Have environments generate a set of modules without hashes in their name, for the items in the environment.  (They would likely be symlinks to the "original" modules generated in Spack).

### Rationale

There is a persistent desire for this feature.  But people are doing it in a way that breaks Spack.

> What I do in the center Spack installation is to use module suffixes, as described in customize-the-naming-scheme.
>
>In your case, I think that you want to have modules.yaml file something similar to

```
modules:
  enable::
    - tcl
  tcl:
    verbose: True
    hash_length: 0
    naming_scheme: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}/${VERSION}"
    all:
      suffixes:
        '+cuda': 'cuda'
        '~cuda': 'nocuda'
```
