### ISSUE TITLE
Spack not processing config files

### ISSUE THREAD

**Issue by glennpj** [spack/spack#13756]
With a recent update I noticed that Spack was not seeing previously installed packages. I then also noticed that Spack would install packages to the wrong directory. Essentially, Spack is ignoring the configuration information that states where packages **should** be installed and instead is looking at the default install directory. Using `git bisect` the commit that introduced the issue is 43b0356e14a8227f33040302cf948d3c98508d59, #13725. I believe this is the same issue that is causing #13754.

My environment has the following:
```
spack:                                                                                                                  
  include:                                                                                                              
  - ../../config.yaml                                                                                                   
  - ../../compilers.yaml                                                                                                
  - ../../mirrors.yaml                                                                                                  
  - ../../modules.yaml                                                                                                  
  - ../../mpi_packages.yaml                                                                                             
  - ../../packages.yaml                                                                                                 
  - ../../repos.yaml 
```
The config.yaml contains:
```
config:                                                                                                                 
  build_stage: /dev/shm                                                                                                 
  misc_cache: $spack/var/spack/cache                                                                                    
  install_tree: $spack/../apps     
```

However, when installing new packages, or looking for installed packages in the environment, spack is looking in the default
```
install_tree: $spack/opt/spack
```
