### ISSUE TITLE
Version concretization failing for virtual dependencies

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#13870]
I'm working on updating the `bazel` package in #13813. `bazel` contains:
```python
depends_on('java@8', type=('build', 'link', 'run'))
```
`jdk` contains:
```python
provides('java')
provides('java@8',  when='@1.8.0:1.8.999')
```
My `packages.yaml` contains:
```yaml
packages:
    jdk:
        paths:
            jdk@12.0.1_12: /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
            jdk@10.0.1_10: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
            jdk@1.8.0_231-b11: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home
            jdk@1.7.0_45-b18: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
        buildable: False
```
However, `spack spec bazel` and `spack install bazel` happily use JDK 12.0.1_12, even though it doesn't provide `java@8`.
