### ISSUE TITLE
Installation issue: gromacs (with intel-parallel-studio)

### ISSUE THREAD

**Issue by plasmas** [spack/spack#13948]
When trying to install `gromacs@2019.5` with `intel-parallel-studio@cluster.2019.5`, Spack did not recognize that `intel-parallel-studio@cluster.2019.5` was already installed and tried to install `intel-parallel-studio` again.

---

### Steps to reproduce the issue

1. Confirm the installation of `intel-parallel-studio`
```console
$ spack find -v intel-parallel-studio %intel@19.0.5 target=cascadelake
==> 1 installed package
-- linux-centos7-cascadelake / intel@19.0.5 ---------------------
intel-parallel-studio@cluster.2019.5+advisor auto_dispatch=none ~clck+daal~gdb~ilp64+inspector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp +vtune
```
2. Install `gromacs` with the `intel-parallel-studio` found above:
```console
$ spack install gromacs+mpi@2019.5 %intel@19.0.5 simd=AVX_512 target=cascadelake ^intel-parallel-studio@cluster.2019.5+advisor auto_dispatch=none ~clck+daal~gdb~ilp64+insp
ector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp +vtune
==> pkgconf is already installed in ...
==> ...
==> fftw is already installed in ...
==> Installing intel-parallel-studio
==> Searching for binary cache of intel-parallel-studio
==> ...
```
3. Additional specs of the installation above:
```console
$ spack spec gromacs+mpi@2019.5 %intel@19.0.5 simd=AVX_512 target=cascadelake ^intel-parallel-studio@cluster.2019.5+advisor auto_dispatch=none ~clck+daal~gdb~ilp64+insp
ector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp +vtune
Input spec
--------------------------------
gromacs@2019.5%intel@19.0.5+mpi simd=AVX_512 arch=linux-None-cascadelake
    ^intel-parallel-studio@cluster.2019.5+advisor auto_dispatch=none ~clck+daal~gdb~ilp64+inspector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp +vtune

Concretized
--------------------------------
gromacs@2019.5%intel@19.0.5 build_type=RelWithDebInfo ~cuda~double~double_precision~mdrun_only+mpi+openmp~plumed+rdtscp+shared simd=AVX_512 arch=linux-centos7-cascadelake
    ^cmake@3.15.5%intel@19.0.5~doc+ncurses+openssl+ownlibs patches=3387faf4a71efe81c0fa17410b270ca7d352081ac88d2322df3da9bb6a6a3f2d ~qt arch=linux-centos7-cascadelake
        ^ncurses@6.1%intel@19.0.5~symlinks~termlib arch=linux-centos7-cascadelake
            ^pkgconf@1.6.3%intel@19.0.5 arch=linux-centos7-cascadelake
        ^openssl@1.1.1d%intel@19.0.5+systemcerts arch=linux-centos7-cascadelake
            ^perl@5.30.0%intel@19.0.5+cpanm+shared+threads arch=linux-centos7-cascadelake
                ^gdbm@1.18.1%intel@19.0.5 arch=linux-centos7-cascadelake
                    ^readline@8.0%intel@19.0.5 arch=linux-centos7-cascadelake
            ^zlib@1.2.11%intel@19.0.5+optimize+pic+shared arch=linux-centos7-cascadelake
    ^fftw@3.3.8%intel@19.0.5~mpi+openmp~pfft_patches precision=double,float arch=linux-centos7-cascadelake
    ^intel-parallel-studio@cluster.2019.5%intel@19.0.5+advisor auto_dispatch=none ~clck+daal~gdb~ilp64+inspector+ipp+itac+mkl+mpi~newdtags+rpath+shared+tbb threads=openmp +vtune arch=linux-centos7-cascadelake
```
### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux login3.pi.sjtu.edu.cn 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	CentOS Linux release 7.5.1804 (Core)
``` 
- `packages.yaml`
```yaml
packages:
  all:
    compiler:
    - gcc
    - intel
    - pgi
    providers:
      blas:
      - openblas
      - intel-mkl
      lapack:
      - openblas
      - intel-mkl
      mpi:
      - openmpi
      - mvapich2
      - mpich
      - intel-mpi
      scalapack:
      - netlib-scalapack
      - intel-mkl
    variants: ~mpi +openmp
  intel-mkl:
    variants: threads=openmp
  intel-parallel-studio:
    variants: +inspector +itac +mkl +mpi +advisor +vtune threads=openmp
  libfabric:
    paths:
      libfabric@1.6.2: /usr
  mpich:
    variants: +hydra +romio +slurm netmod=ofi
  openblas:
    variants: +avx2 +avx512 threads=openmp
  openmpi:
    variants: +pmi +legacylaunchers fabrics=libfabric schedulers=slurm
  slurm:
    buildable: false
    paths:
      slurm@17-11-9-13: /usr
```
- `compilers.yaml`
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-kbfjue2cejfoi6e5n3cfgkydzwvlkx4p/bin/gcc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-kbfjue2cejfoi6e5n3cfgkydzwvlkx4p/bin/g++
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-kbfjue2cejfoi6e5n3cfgkydzwvlkx4p/bin/gfortran
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-kbfjue2cejfoi6e5n3cfgkydzwvlkx4p/bin/gfortran
    spec: gcc@5.5.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-8.3.0-aoqn7jsisvrj2u5puapmiufudxmm6wt4/bin/gcc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-8.3.0-aoqn7jsisvrj2u5puapmiufudxmm6wt4/bin/g++
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-8.3.0-aoqn7jsisvrj2u5puapmiufudxmm6wt4/bin/gfortran
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-8.3.0-aoqn7jsisvrj2u5puapmiufudxmm6wt4/bin/gfortran
    spec: gcc@8.3.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gcc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/g++
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gfortran
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gfortran
    spec: gcc@9.2.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.4-zxtvkrsgqvhud4og62e55kwgqvhy26d3/compilers_and_libraries_2019.4.243/linux/bin/intel64/icc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.4-zxtvkrsgqvhud4og62e55kwgqvhy26d3/compilers_and_libraries_2019.4.243/linux/bin/intel64/icpc
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.4-zxtvkrsgqvhud4og62e55kwgqvhy26d3/compilers_and_libraries_2019.4.243/linux/bin/intel64/ifort
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.4-zxtvkrsgqvhud4og62e55kwgqvhy26d3/compilers_and_libraries_2019.4.243/linux/bin/intel64/ifort
    spec: intel@19.0.4
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.5-2wbf5cihe2454tnokwkbxjjym4nozecd/bin/icc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.5-2wbf5cihe2454tnokwkbxjjym4nozecd/bin/icpc
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.5-2wbf5cihe2454tnokwkbxjjym4nozecd/bin/ifort
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-19.0.5-2wbf5cihe2454tnokwkbxjjym4nozecd/bin/ifort
    spec: intel@19.0.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.4-yzuuq5mpke4i44enduypudbrp2mty2s5/bin/icc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.4-yzuuq5mpke4i44enduypudbrp2mty2s5/bin/icpc
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.4-yzuuq5mpke4i44enduypudbrp2mty2s5/bin/ifort
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/intel-18.0.4-yzuuq5mpke4i44enduypudbrp2mty2s5/bin/ifort
    spec: intel@18.0.4
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/pgi-19.4-hz2tz6aeh4wt5zlw4dfb6mjbccdn5c4h/linux86-64/19.4/bin/pgcc
      cxx: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/pgi-19.4-hz2tz6aeh4wt5zlw4dfb6mjbccdn5c4h/linux86-64/19.4/bin/pgc++
      f77: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/pgi-19.4-hz2tz6aeh4wt5zlw4dfb6mjbccdn5c4h/linux86-64/19.4/bin/pgfortran
      fc: /lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/pgi-19.4-hz2tz6aeh4wt5zlw4dfb6mjbccdn5c4h/linux86-64/19.4/bin/pgf95
    spec: pgi@19.4
    target: x86_64
```
