### ISSUE TITLE
Spack on Mac fails to build for Skylake

### ISSUE THREAD

**Issue by victorusu** [spack/spack#14565]
After running `spack compilers` in a recent spack installation on a mac. I get the following list of compilers
```
==> Available compilers
-- clang mojave-x86_64 ------------------------------------------
clang@11.0.0-apple
```

But when building any package I get the following warning

```
spack install cmake
==> Warning: clang@11.0.0-apple cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
```

When I try to force the build for skylake, I get the following
```
spack install cmake@3.12.0 target=skylake
==> Error: cannot produce optimized binary for micro-architecture 'skylake' with clang@11.0.0-apple [supported compiler versions are 3.9:]
```

But after changing the compiler configuration from

```
compilers:                                                                         
- compiler:                                                                        
    paths:                                                                         
      cc: /usr/bin/clang                                                           
      cxx: /usr/bin/clang++                                                        
      f77:                                                                         
      fc:                                                                          
    operating_system: mojave                                                       
    target: x86_64                                                                 
    modules: []                                                                    
    environment: {}                                                                
    extra_rpaths: []                                                               
    flags: {}                                                                      
    spec: clang@11.0.0-apple  
```

to

```
compilers:                                                                         
- compiler:                                                                        
    paths:                                                                         
      cc: /usr/bin/clang                                                           
      cxx: /usr/bin/clang++                                                        
      f77:                                                                         
      fc:                                                                          
    operating_system: mojave                                                       
    target: x86_64                                                                 
    modules: []                                                                    
    environment: {}                                                                
    extra_rpaths: []                                                               
    flags: {}                                                                      
    spec: clang@11.0.0
```

Spack is able to build for skylake on my mac.

---

The user workaround is simple, so I think that either spack should not append the `-apple` to the `spec` field or it should ignore the suffixes on the specs when comparing compiler versions.
