### ISSUE TITLE
Jobs should fail when module is not correctly loaded (as defined in compilers.yaml)

### ISSUE THREAD

**Issue by paulbry** [spack/spack#14620]
When a module associated with a compiler is not present or fails to load properly the job should fail. For instance, if my `compilers.yaml` is configured like below, missing the `gcc/9.2.0` from my MODULEPATH does not result in a failure. Instead it will continue to install, and since I don't define full paths it will just use the underlying system gcc.

```yaml
- compiler:
    spec: gcc@9.2.0
    operating_system: centos7
    target: x86_64
    modules: [gcc/9.2.0]
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
   ...
```

There are a number of steps I can take to address this without changes to Spack, however, I felt it would be valuable to fail jobs in the above cases since it can be easily overlooked.
