### ISSUE TITLE
How to build OpenMPI 4.0.x (with UCX support) with the Intel compiler ?

### ISSUE THREAD

**Issue by samfux84** [spack/spack#14779]
Hi,

We have added new hardware to our cluster containing Mellanox ConnectX-6 Infiniband cards. Those require OpenMPI 4.0.x to be built with UCX support.

UCX depends on numactl and rdma-core. But according to https://github.com/spack/spack/pull/9255, rdma-core conflicts with Intel. I could not find any reference regarding this, except the comment from https://github.com/spack/spack/pull/9072#issuecomment-421492369 from @pramodk mentioning:

`@michaelkuhn : I see that rdma-core doesn't build with Intel. In the past I was simply doing spack install mvapich2 %intel (new users have to specify now ^rdma-core %gcc). Have you tested with Intel?`

Does anybody have a reference, explaining why rdma-core does not build with the Intel compiler ? And does this mean that in general OpenMPI 4.0.x with UCX support cannot be built with the Intel compiler ?

https://github.com/spack/spack/pull/9255#issuecomment-441676893

mentions that one can also take rdma-core from the CentOS repository and use it as external package:

```
packages:
  rdma-core:
    paths:
      rdma-core@15%gcc@4.8.5 arch=linux-centos7-x86_64: /
    buildable: False
```

Do you think something like

```
packages:
  rdma-core:
    paths:
      rdma-core@15%intel@18.0.1 arch=linux-centos7-x86_64: /
    buildable: False
```

could be used to compile UCX with the Intel compiler ?

Even though I am afraid that It might triggers another issue when building software that depends on rdma-core with the Intel compiler:

https://marc.info/?t=150643483900004&r=1&w=2

Would you have any recommendation on how to workaround this problem ?

Best regards

Sam
