### ISSUE TITLE
Cannot set env variables in Environment initialization file

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#14886]
If an environment yaml initialization file contains a `compilers` section, and one of the compilers in that section contains an `environment` section as described in https://spack-tutorial.readthedocs.io/en/latest/tutorial_configuration.html#advanced-compiler-configuration, then when trying to create a new environment from that file, it fails with `Error: test.yaml: Additional properties are not allowed ('...' was not expected)`

This issue appears starting with b9629c3 (the previous commit does not have this problem).

### Steps to reproduce the issue

Create a `test.yaml` which looks like:

```console
spack:
  compilers:
  - compiler:
      environment:
        prepend-path:
          PATH: /a/test/path
      ... (you can copy any other compiler definition from your compilers.yaml for this)
```

Then run `spack env create testenv1 test.yaml`

It then fails with 

`Error: test.yaml: Additional properties are not allowed ('prepend-path' was not expected)`

(this also happens if I choose `prepend_path` instead as described in https://spack.readthedocs.io/en/latest/configuration.html#environment-modifications)

### Information on your system

Platform: Mac OS (this has also been observed on a Linux system)

**Comment by scheibelp** [comment]
@bvanessen FYI

**Comment by alalazo** [comment]
I can't reproduce if I use `prepend_path` (which is the expected attribute name). I used this `spack.yaml`:
```yaml
spack:
  specs:
  - zlib
  compilers:
  - compiler:
      spec: gcc@9.0.1
      paths:
        cc: /usr/bin/gcc-9
        cxx: /usr/bin/g++-9
        f77: /usr/bin/gfortran-9
        fc: /usr/bin/gfortran-9
      flags: {}
      operating_system: ubuntu18.04
      target: x86_64
      modules: []
      environment:
        prepend_path:
          FOO: /path/to/foo
      extra_rpaths: []
```
and got this result:
```console
$ spack env create testenv1 spack.yaml
==> Updating view at /home/culpo/PycharmProjects/spack/var/spack/environments/testenv1/.spack-env/view
==> Created environment 'testenv1' in /home/culpo/PycharmProjects/spack/var/spack/environments/testenv1
```
If I use the wrong attribute `prepend-path` I get:
```
$ spack env create testenv1 spack.yaml
[ ... ]
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/environment.py", line 410, in validate
    e, data, filename, e.instance.lc.line + 1)
spack.config.ConfigFormatError: /home/culpo/tmp/spack-issues/14886/spack.yaml:19: Additional properties are not allowed ('prepend-path' was unexpected)
```
which is expected. I'll submit a fix for the docs.

**Comment by alalazo** [comment]
@scheibelp Ok, got it. It's the **name** of the file. If I use a file named `test.yaml` instead of `spack.yaml` I can reproduce the bug.

**Comment by alalazo** [comment]
Given this in the description:

> `Error: test.yaml: Additional properties are not allowed ('...' was not expected)`

Is the `...` an edit to shorten a long string or the manifest file contains a verbatim `...`?

**Comment by scheibelp** [comment]
> Is the ... an edit to shorten a long string or the manifest file contains a verbatim ...? Asking because the docs page that are linked are full of ... so I am wondering if this is a cut'n paste error.

It is not a literal `...` - I replaced that myself. I repeat the error message in https://github.com/spack/spack/issues/14886#issue-562948116 without the `...`

**Comment by alalazo** [comment]
@scheibelp Can you post the entire `spack.yaml` that is showing the issue?

**Comment by scheibelp** [comment]
```
spack:
  compilers:
  - compiler:
      environment:
        prepend_path:
          LD_LIBRARY_PATH: /a/nonexistent/path
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: mojave
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77:
        fc:
      spec: clang@9.0.0-apple
      target: x86_64
```
