### ISSUE TITLE
BOOST_ROOT

### ISSUE THREAD

**Issue by azukaitis** [spack/spack#14883]
Have boost package provide BOOST_ROOT environment variable

### Rationale

Searching through the packages for examples, I see a lot of them using BOOST_ROOT as part of their builds.  Seems like a nice thing for spack to provide.

### Implementation
Mind if I file a pull request for this via fork to help out with this feature?  should be a 2 liner if I understand spack.

**Comment by sethrj** [comment]
Note that newer cmake versions search for packages by default using the environment variable `${package}_ROOT`, so it's not just Boost. In fact, I always set my `modules.yaml` files to generate and export such a variable:
```yaml
modules:
  # ...
  lmod:
    # ...
    all:
       # ...
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
```

This also makes it really easy to load auxiliary files installed by packages, e.g. in my .bashrc I have
```bash
source ${NINJA_ROOT}/misc/bash-completion
```
