### ISSUE TITLE
Very slow environment concretization

### ISSUE THREAD

**Issue by ajw1980** [spack/spack#15040]
I updated to the latest git yesterday and ran concretize on an existing environment that was built a couple of months ago. This was very slow. I'll attach the pyinstrument output.
[spack-pyinstrument-con.txt](https://github.com/spack/spack/files/4219767/spack-pyinstrument-con.txt)

**Comment by alalazo** [comment]
Could you please attach the environment too?

**Comment by ajw1980** [comment]
[spack-env.txt](https://github.com/spack/spack/files/4219796/spack-env.txt)

**Comment by alalazo** [comment]
@ajw1980 Very difficult to reproduce. Most of the packages in the environment are not in the built-in repository...

**Comment by ajw1980** [comment]
r-caret alone in the environment seems to exhibit similar behavior (r-caret is like the worst case for a single package dependency)
```
spack:
  # add package specs to the `specs` list
  specs:
  - r-caret
  view: false
  mirrors: {}
  modules:
    enable: []
  repos: []
  packages: {}
  config: {}
  upstreams: {}
  definitions: []
  concretization: together
```
```
  _     ._   __/__   _ _  _  _ _/_   Recorded: 10:56:07  Samples:  163192                                                                                                   
 /_//_/// /_\ / //_// / //_'/ //     Duration: 194.968   CPU time: 176.991                                                                                                  
/   _/                      v3.1.0   
```
