### ISSUE TITLE
Installation issue: LLVM@3.6.2

### ISSUE THREAD

**Issue by LouisJenkinsCS** [spack/spack#15051]
### Steps to reproduce the issue

**Prerequisite Step**

Need to have gcc version lower than 8 installed... I went with gcc@6.1.0

```console
spack install gcc@6.1.0
```

As well I found that CMake does not build properly with gcc@6.1.0 so I went with something earlier...

```console
spack install llvm@3.6.2%gcc@6.1.0 ^cmake@3.8.0%gcc@6.1.0
```

Now, some software I am using requires an older version of LLVM, and so I am using Spack to install older versions of dependencies for said software; I'd even say I want to go as far as creating a Spack package for the software as I see it as rather valuable (its software used in research literature, that has been long abandoned but is still widely referred to: https://github.com/HewlettPackard/Atlas). 

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux [REDACTED] 5.3.7-200.fc30.x86_64 #1 SMP Fri Oct 18 20:13:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:	Fedora release 30 (Thirty)
``` 

**Packages**

```yaml
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user

```

**Compilers**

```console
==> Available compilers
-- clang fedora30-x86_64 ----------------------------------------
clang@8.0.0

-- gcc fedora30-x86_64 ------------------------------------------
gcc@9.2.1  gcc@6.1.0  gcc@3.4.6

```

### Additional information

Spack spec output...

```console
Input spec
--------------------------------
 -   llvm@3.6.2%gcc@6.1.0
 -       ^cmake@3.8.0%gcc@6.1.0

Concretized
--------------------------------
==> Warning: gcc@6.1.0 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
 -   llvm@3.6.2%gcc@6.1.0~all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb~omp_tsan+polly~python~shared_libs arch=linux-fedora30-skylake_avx512
[+]      ^binutils@2.33.1%gcc@6.1.0+gold~headers~libiberty+nls~plugins arch=linux-fedora30-skylake_avx512
[+]          ^gettext@0.20.1%gcc@6.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-fedora30-skylake_avx512
[+]              ^bzip2@1.0.8%gcc@6.1.0+shared arch=linux-fedora30-skylake_avx512
[+]                  ^diffutils@3.7%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]                      ^libiconv@1.16%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]              ^libxml2@2.9.9%gcc@6.1.0~python arch=linux-fedora30-skylake_avx512
[+]                  ^pkgconf@1.6.3%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]                  ^xz@5.2.4%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]                  ^zlib@1.2.11%gcc@6.1.0+optimize+pic+shared arch=linux-fedora30-skylake_avx512
[+]              ^ncurses@6.1%gcc@6.1.0~symlinks+termlib arch=linux-fedora30-skylake_avx512
[+]              ^tar@1.32%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^cmake@3.8.0%gcc@6.1.0~doc+ncurses+openssl+ownlibs patches=dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-fedora30-skylake_avx512
[+]          ^openssl@1.1.1d%gcc@6.1.0+systemcerts arch=linux-fedora30-skylake_avx512
[+]              ^perl@5.30.1%gcc@6.1.0+cpanm+shared+threads arch=linux-fedora30-skylake_avx512
[+]                  ^gdbm@1.18.1%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]                      ^readline@8.0%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^gmp@6.1.2%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^autoconf@2.69%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]              ^m4@1.4.18%gcc@6.1.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-fedora30-skylake_avx512
[+]                  ^libsigsegv@2.12%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^automake@1.16.1%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^libtool@2.4.6%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^isl@0.21%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^libedit@3.1-20170329%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^perl-data-dumper@2.173%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]      ^python@2.7.16%gcc@6.1.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-fedora30-skylake_avx512
[+]          ^expat@2.2.9%gcc@6.1.0+libbsd arch=linux-fedora30-skylake_avx512
[+]              ^libbsd@0.10.0%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^libffi@3.2.1%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^sqlite@3.30.1%gcc@6.1.0~column_metadata+fts~functions~rtree arch=linux-fedora30-skylake_avx512
[+]      ^swig@4.0.0%gcc@6.1.0 arch=linux-fedora30-skylake_avx512
[+]          ^pcre@8.42%gcc@6.1.0~jit+multibyte+utf arch=linux-fedora30-skylake_avx512
```
