### ISSUE TITLE
spack env activate doesn't load system modules

### ISSUE THREAD

**Issue by mdorier** [spack/spack#15236]
`spack env activate myenv` doesn't seem to load system-provided modules.

Here is an example: on Theta I have boost (along with other packages) already installed as a system-provided module, and I tell spack about it as follows in my packages.yaml file:

```
   boost:
        modules:
            boost@1.64.0 arch=cray-cnl6-mic_knl: boost/gnu/1.64.0
        buildable: False
```

I created an environment `myenv` as follows:
```
spack env create myenv
spack env activate myenv
spack add boost
spack add X # where X is a package that depends on boost
spack install
```
This installs everything correctly and spack is picking up the boost from the system.

However later, if I activate the environment, it doesn't load the boost module. I have to explicitely do `module load boost/gnu/1.64.0`.

This happens to all the packages that are system-provided as modules.
