### ISSUE TITLE
Definitions as requirements in environments

### ISSUE THREAD

**Issue by ilbiondo** [spack/spack#15231]
It would be very useful to be able to use definitions as requirements in specs so as to make environments very easy to share and reuse:

For example we declare the compiler, core compiler and mpi:

```
  definitions:
    - mygcc: [ gcc@8.3.0 ]
    - mybasegcc: [ gcc@4.8.5 ]
    - mympi: [ mpich@3.3.2+slurm pmi=pmi2 ]

  specs:
  - matrix:
    - [$mygcc]
    - [% $mybasegcc]
  
  - matrix:
    - [openblas@0.3.8, $mympi , fftw~mpi]
    - [% mygcc ]
  - matrix:
    - [openfoam,  fftw]
    - [^ $mympi]
    - [% $mygcc]
```

At present this isn't possible as `%$mygcc` is invalid syntax (needs expansion?) so even if we can define things to be installed they have to be added by hand when used as requirements:

```
  - matrix:
    - [openblas, $mympi , fftw~mpi]
    - [ "%gcc@8.3.0" ]
  - matrix:
    - [openfoam, fftw]
    - ["^mpich@3.3.2+slurm pmi=pmi2"]
    - ["%gcc@8.3.0"]
```
