### ISSUE TITLE
mpich exports hwloc symbols

### ISSUE THREAD

**Issue by eschnett** [spack/spack#15302]
I am building `mpich @3.3.2` (the latest version) on OS X. This library apparently ships with a version of `hwloc @2.0` included. When I install `mpich`, then its library seems to contain (and make visible to others) the respective `hwloc` symbols. Of course, the `hwloc` include files are not installed.

This leads to a conflict if a different version of `hwloc` is installed as well, as (depending on the link order) `mpich`'s `hwloc` symbols are found first. The error I am then seeing is
```
ERROR from host Redshift.local process 0
  while executing schedule bin hwloc_startup, routine hwloc::hwloc_version
  in thorn hwloc, file /Users/eschnett/CarpetX/arrangements/ExternalLibraries/hwloc/src/version.c:24:
  -> library version 2.1.0, build-time API version 0x20100, run-time API version 0x20000
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

This error is generated from a consistency check I implemented for `hwloc`, which compares the version numbers of `hwloc` used to build, and the version found at run time.

Possible remedies could be:
- Configure `mpich` so that it doesn't export `hwloc` symbols. Maybe they can be renamed at the source level? Or maybe they can be hidden using linker magic?
- Tell `spack` about this, i.e. ensure that `mpich` depends on the same version of `hwloc` that it contains anyway. That would be cheating, but would avoid the error I'm seeing.
- Tell `spack` about this, making it a conflict to use `mpich` and `hwloc` at the same time since they export the same symbols. That's technically correct, but would make `mpich` unusable for me.

**Comment by eschnett** [comment]
My `spec.yaml` for the installed `mpich`:
```yaml
spec:
- mpich:
    version: 3.3.2
    arch:
      platform: darwin
      platform_os: catalina
      target:
        name: skylake
        vendor: GenuineIntel
        features:
        - adx
        - aes
        - avx
        - avx2
        - bmi1
        - bmi2
        - clflushopt
        - f16c
        - fma
        - mmx
        - movbe
        - pclmulqdq
        - popcnt
        - rdrand
        - rdseed
        - sse
        - sse2
        - sse4_1
        - sse4_2
        - ssse3
        - xsavec
        - xsaveopt
        generation: 0
        parents:
        - broadwell
    compiler:
      name: gcc
      version: 9.2.0-spack
    namespace: builtin
    parameters:
      device: ch3
      hydra: true
      netmod: tcp
      pci: false
      pmi: pmi
      romio: true
      slurm: false
      verbs: false
      wrapperrpath: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      libxml2:
        hash: 7shax7k6yv4bt6siczz6pfhxngybeh2u
        type:
        - build
        - link
    hash: kagnmitv33crplu2epdnwfqrcwsobkuf
- libxml2:
    version: 2.9.9
    arch:
      platform: darwin
      platform_os: catalina
      target:
        name: skylake
        vendor: GenuineIntel
        features:
        - adx
        - aes
        - avx
        - avx2
        - bmi1
        - bmi2
        - clflushopt
        - f16c
        - fma
        - mmx
        - movbe
        - pclmulqdq
        - popcnt
        - rdrand
        - rdseed
        - sse
        - sse2
        - sse4_1
        - sse4_2
        - ssse3
        - xsavec
        - xsaveopt
        generation: 0
        parents:
        - broadwell
    compiler:
      name: gcc
      version: 9.2.0-spack
    namespace: builtin
    parameters:
      python: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    dependencies:
      libiconv:
        hash: n6yw7szwmfbmiqe7swet7i43swvi5q5o
        type:
        - build
        - link
      xz:
        hash: p5m3lolbopfwfnsatgy7delaasioy5zr
        type:
        - build
        - link
      zlib:
        hash: opei6id72kbotldxfsbkow4ucgurzi2z
        type:
        - build
        - link
    hash: 7shax7k6yv4bt6siczz6pfhxngybeh2u
- libiconv:
    version: '1.16'
    arch:
      platform: darwin
      platform_os: catalina
      target:
        name: skylake
        vendor: GenuineIntel
        features:
        - adx
        - aes
        - avx
        - avx2
        - bmi1
        - bmi2
        - clflushopt
        - f16c
        - fma
        - mmx
        - movbe
        - pclmulqdq
        - popcnt
        - rdrand
        - rdseed
        - sse
        - sse2
        - sse4_1
        - sse4_2
        - ssse3
        - xsavec
        - xsaveopt
        generation: 0
        parents:
        - broadwell
    compiler:
      name: gcc
      version: 9.2.0-spack
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: n6yw7szwmfbmiqe7swet7i43swvi5q5o
- xz:
    version: 5.2.4
    arch:
      platform: darwin
      platform_os: catalina
      target:
        name: skylake
        vendor: GenuineIntel
        features:
        - adx
        - aes
        - avx
        - avx2
        - bmi1
        - bmi2
        - clflushopt
        - f16c
        - fma
        - mmx
        - movbe
        - pclmulqdq
        - popcnt
        - rdrand
        - rdseed
        - sse
        - sse2
        - sse4_1
        - sse4_2
        - ssse3
        - xsavec
        - xsaveopt
        generation: 0
        parents:
        - broadwell
    compiler:
      name: gcc
      version: 9.2.0-spack
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: p5m3lolbopfwfnsatgy7delaasioy5zr
- zlib:
    version: 1.2.11
    arch:
      platform: darwin
      platform_os: catalina
      target:
        name: skylake
        vendor: GenuineIntel
        features:
        - adx
        - aes
        - avx
        - avx2
        - bmi1
        - bmi2
        - clflushopt
        - f16c
        - fma
        - mmx
        - movbe
        - pclmulqdq
        - popcnt
        - rdrand
        - rdseed
        - sse
        - sse2
        - sse4_1
        - sse4_2
        - ssse3
        - xsavec
        - xsaveopt
        generation: 0
        parents:
        - broadwell
    compiler:
      name: gcc
      version: 9.2.0-spack
    namespace: builtin
    parameters:
      optimize: true
      pic: true
      shared: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: opei6id72kbotldxfsbkow4ucgurzi2z
```
