### ISSUE TITLE
NAG/GNU mixed toolchain problem

### ISSUE THREAD

**Issue by aradi** [spack/spack#15445]
I have set up a NAG/GNU mixed compiler tool-chain according to the [documentation](https://spack.readthedocs.io/en/latest/getting_started.html#nag). When I try to build a simple package, I get an error. It turns out, that configure fails, since instead of `-fPIC` the `-PIC` flag is passed to the C-compiler.  Apparently the `-PIC` flag is defined in the `nag.py` compiler definition file, which is OK for the NAG Fortran compiler, but not for the GNU C-compiler.

### Spack version
```console
$ spack --version
0.14.0
```

### Steps to reproduce the issue

```console
spack install zlib %nag@7.0
```

The NAG compiler had been added by adding the following lines to the `compilers.yaml` configuration file:
```yaml
- compiler:
    spec: nag@7.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /opt/nag/7.0/bin/nagfor
      fc: /opt/nag/7.0/bin/nagfor
    flags:
        fflags: -dusty -dcfuns -mismatch_all
    operating_system: centos8
    target: x86_64
    modules: [nagfor/7.0]
    environment: {}
    extra_rpaths: []
```

### Error Message
The `configure.log` file of the zlib-build contains the following error message:
```
Checking for obsessive-compulsive compiler options...                          
=== ztest15505.c ===
int foo() { return 0; }
===
/home/packager/spack/spack-packages/lib/spack/env/cc -c -PIC -O2 ztest15505.c  
gcc: error: unrecognized command line option '-PIC'; did you mean '-fPIC'?     
(exit code 1)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```
