### ISSUE TITLE
Concretization options in environments 

### ISSUE THREAD

**Issue by ilbiondo** [spack/spack#15542]
At present concretisation can be either `together`or `separately` which leads to a few problems.

For example in the following environment with two compilers:

```
  definitions:                                                                                                                                                              
  - mybasegcc: [gcc@4.8.5]                                                                                                                                                  
  - mygcc: [gcc@8.3.0]                                                                                                                                                      
  - myintel: [intel@19.1.0.166]                                                                                                                                             
                                                                                                                                                                            
  - basepackages:                                                                                                                                                           
    - eigen@3.3.7                                                                                                                                                           
    - gsl@2.5                                                                                                                                                               
                                                                                                                                                                            
  specs:                                                                                                                                                                    
  - matrix:                                                                                                                                                                 
    - [$mygcc]                                                                                                                                                              
    - [$%mybasegcc]                                                                                                                                                         
  - matrix:                                                                                                                                                                 
    - [$basepackages]                                                                                                                                                       
    - [$%mygcc]                                                                                                                                                             
  - matrix:                                                                                                                                                                 
    - [$myintel]                                                                                                                                                            
    - [$%mybasegcc]                                                                                                                                                         
  - matrix:                                                                                                                                                                 
    - [$basepackages]                                                                                                                                                       
    - [$%myintel]                                                                                                                                                           
  concretization: together 
```

We see

```
$ spack concretize -f
==> Error: environment that are configured to concretize specs together cannot contain more than one spec for each package [eigen, gsl]
```

Would it be possible (or desirable) to allow concretisation either by `compiler` or perhaps even better by `matrix` to allow something between the current all or nothing approach?
