### ISSUE TITLE
spack compiler find fails on OSX

### ISSUE THREAD

**Issue by khuck** [spack/spack#15608]
I have an OSX system with the Xcode tools installed, and with macports installed.  Currently, there are no compilers selected under port select:

```bash
khuck@OACISS-MacBook-Air:~$ sudo port select --summary
Password:
Name         Selected          Options
====         ========          =======
clang        none              mp-clang-8.0 mp-clang-9.0 none
cython       none              cython37 none
flake8       flake8-38         flake8-38 none
gcc          none              mp-gcc9 none
llvm         none              mp-llvm-8.0 mp-llvm-9.0 none
...
```

When I pull a fresh spack from the repo, and perform the spack setup, it fails to configure compilers correctly (cc and cxx are not set):

```bash
khuck@OACISS-MacBook-Air:~$ source spack-mine/share/spack/setup-env.sh
khuck@OACISS-MacBook-Air:~$ spack compiler find
==> Added 3 new compilers to /Users/khuck/.spack/darwin/compilers.yaml
    clang@11.0.0-apple  clang@9.0.1  clang@8.0.1
==> Compilers are defined in the following files:
    /Users/khuck/.spack/darwin/compilers.yaml
khuck@OACISS-MacBook-Air:~$ spack config edit compilers
khuck@OACISS-MacBook-Air:~$ head .spack/darwin/compilers.yaml 
compilers:
- compiler:
    spec: clang@11.0.0-apple
    paths:
      cc:
      cxx:
      f77: /opt/local/bin/gfortran-mp-9
      fc: /opt/local/bin/gfortran-mp-9
    flags: {}
    operating_system: catalina
```

### Spack version

```console
$ spack --version
0.14.0-316-42db14358
```

### Steps to reproduce the issue

```console
khuck@OACISS-MacBook-Air:~$ rm -rf $HOME/.spack
khuck@OACISS-MacBook-Air:~$ source spack-mine/share/spack/setup-env.sh
khuck@OACISS-MacBook-Air:~$ spack compiler find
khuck@OACISS-MacBook-Air:~$ spack config edit compilers  # confirm that cc, cxx are not set
```

### Error Message

n/a

### Information on your system

```
$ uname -a
Darwin OACISS-MacBook-Air.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Can you post the full contents of `/Users/khuck/.spack/darwin/compilers.yaml`?

**Comment by khuck** [comment]
```yaml
khuck@OACISS-MacBook-Air:~$ cat .spack/darwin/compilers.yaml 
compilers:
- compiler:
    spec: clang@11.0.0-apple
    paths:
      cc:
      cxx:
      f77: /opt/local/bin/gfortran-mp-9
      fc: /opt/local/bin/gfortran-mp-9
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
- compiler:
    spec: clang@8.0.1
    paths:
      cc: /opt/local/bin/clang-mp-8.0
      cxx: /opt/local/bin/clang++-mp-8.0
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@9.0.1
    paths:
      cc: /opt/local/bin/clang-mp-9.0
      cxx: /opt/local/bin/clang++-mp-9.0
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by adamjstewart** [comment]
Huh, I'm kind of surprised that it didn't pick up the system `/usr/bin/clang` at all.

Can you try copying the following line from `lib/spack/spack/compilers/gcc.py`:
```python
suffixes = [r'-mp-\d\.\d', r'-\d\.\d', r'-\d', r'\d\d']
```
to `lib/spack/spack/compilers/clang.py`? Then delete your `compilers.yaml` and run `spack compiler find` again.

**Comment by khuck** [comment]
@adamjstewart Yes, that seems to have helped:

```yaml
cat .spack/darwin/compilers.yaml
compilers:
- compiler:
    spec: clang@11.0.0-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
- compiler:
    spec: clang@8.0.1
    paths:
      cc: /opt/local/bin/clang-mp-8.0
      cxx: /opt/local/bin/clang++-mp-8.0
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@9.0.1
    paths:
      cc: /opt/local/bin/clang-mp-9.0
      cxx: /opt/local/bin/clang++-mp-9.0
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
