### ISSUE TITLE
lmod modules generated for intel packages include LMOD_* environment variables

### ISSUE THREAD

**Issue by anderbubble** [spack/spack#15775]
When I build lmod modules from installed intel packages (including intel, intel-mkl, and intel-mpi) the generated modules include LMOD and related environment variables from the point-in-time environment. This breaks for us because our default lmod environment is different from the environment I'm building the modulefiles for.

### Spack version
```console
$ spack --version
0.14.1-415-cbcac72
```

### Steps to reproduce the issue

```console
$ spack install intel
$ spack module lmod refresh --delete-tree
$ module show intel/19.0.5 2>&1 | grep 'LMOD_'
```

### Error Message

```console
setenv("LMOD_CMD","/curc/sw/lmod/lmod/libexec/lmod")
setenv("LMOD_DIR","/curc/sw/lmod/lmod/libexec")
setenv("LMOD_PKG","/curc/sw/lmod/lmod")
setenv("LMOD_VERSION","6.3.7")
...
```

### Information on your system

1. RHEL7.6

```
modules:
  enable:
  - lmod
  lmod:
    hash_length: 0
    core_compilers:
    - gcc@4.8.5
    hierarchy:
    - mpi
    - lapack
    blacklist:
      - '%gcc'
      - '%intel'
    whitelist:
      - intel@19.0.5
      - gcc@9.3.0
      - intel-mkl
      - intel-mpi
      - openmpi
```

```
packages:
  intel:
    variants: auto_dispatch=AVX,CORE-AVX2,CORE-AVX512,SSE4.2
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
