### ISSUE TITLE
bug: combination of external module loaded compiler and external depnedencies

### ISSUE THREAD

**Issue by JaroslavHron** [spack/spack#1787]
On a small cluster we use spack with compiler provided by external module:

compilers.yaml

``` yaml
- compiler:
    modules: [GCC/5.3.0-2.26]
    operating_system: centos6
    paths:
      cc: /apps/all/GCCcore/5.3.0/bin/gcc
      cxx: /apps/all/GCCcore/5.3.0/bin/g++
      f77: /apps/all/GCCcore/5.3.0/bin/gfortran
      fc: /apps/all/GCCcore/5.3.0/bin/gfortran
    spec: gcc@5.3.0
```

in combination with some external dependencies which I want to use from the system:

packages.yaml 

``` yaml
packages:
  all:
    compiler: [gcc@5.3.0]
    providers:
      mpi: [openmpi, mpich]
      blas: [openblas]
      lapack: [openblas]
  openssl:
    paths:
      openssl@system: /usr
    buildable: False
    version: [system]
```

this leads to a situation that the compilation environment setup by spack has
`/usr/bin` prepended to `PATH` (due to the requested external system openssl form packages.yaml)

However this leads to this cryptic assembler failure:

```
/tmp/cce6FYR4.s: Assembler messages:
/tmp/cce6FYR4.s:2159: Error: expecting string instruction after `rep'
make: *** [Parser/node.o] Error 1
```

The reason is that the external `gcc` module also loads corresponding libtools 
(which includes the correct `as`) 
but due to the prepended `/usr/bin` in `PATH` spack is picking `/usr/bin/as` instead.

Solutions might be:
1.  modify compiler wrappers so that the correct 'as' is used for example by  `gcc -B/path_to_as_bin_dir/`  and let user supply the `path_to_as_bin_dir` in compilers.yaml
2. or skip the systems dirs already in `PATH` when adding the external dependencies to the spack's `PATH`

Is there any better way to prevent this?

I have the 2. fix which helps and i can prepare it as PR.
