### ISSUE TITLE
Error resolving providers when additional repos are set

### ISSUE THREAD

**Issue by JaroslavHron** [spack/spack#1801]
consider packages.yaml:

```
packages:
  all:
    compiler: [gcc@5.3.0]
        providers:
            mpi: [openmpi]
            blas: [openblas]
            lapack: [openblas]
```

now I have a local repo with my own `openmpi` and `openblas` packages and repos.yaml:

```
repos:
- ~/spack/local
```

According to 
https://groups.google.com/forum/#!msg/spack/YZMe02JH5Zo/gl11k_s9DwAJ
the local repo should take precedence.

But while mpi resolves correctly to `openmpi` package from local repo,
the blas/lapack resolve to `openblas` from the builtin repo...
`spack spec blas` -> openblas from the builtin repo
`spack spec openblas` -> openblas from the local repo

Any idea why?

**Comment by JaroslavHron** [comment]
Just for reference - this can be solved by specifying providers with full namespace.
```
packages:
  all:
    compiler: [gcc@5.3.0]
        providers:
            mpi: [local.openmpi]
            blas: [local.openblas]
            lapack: [local.openblas]
```
where `local` is the local repo namespace
