### ISSUE TITLE
Error installing moab on titan, not recognizing mpich module

### ISSUE THREAD

**Issue by sarich** [spack/spack#1865]
I'm getting an error trying to install moab (I stripped out the trilinos requirement). it's possible the packages.yaml file isn't correct

sarich@titan-ext2:/ccs/proj/cli112/sarich/spack> ./bin/spack  install moab%pgi

Traceback (most recent call last):
  File "./bin/spack", line 192, in <module>
    main()
  File "./bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/cmd/install.py", line 79, in install
    specs = spack.cmd.parse_specs(args.packages, concretize=True)
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/cmd/**init**.py", line 106, in parse_specs
    spec.concretize()  # implies normalize
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/spec.py", line 1266, in concretize
    self._expand_virtual_packages(),
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/spec.py", line 1183, in _expand_virtual_packages
    spec)
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/concretize.py", line 116, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/concretize.py", line 108, in _valid_virtuals_and_externals
    usable.sort(cmp=cmp_externals)
  File "/autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/spack/concretize.py", line 96, in cmp_externals
    return candidates.index(a) - candidates.index(b)
ValueError: mpich@7.4.0%pgi@15.7.0 arch=cray-CNL-interlagos is not in list

My packages.yaml:

```
packages:
  mpich:
    modules:
      mpich@7.4.0%pgi@15.7.0 arch=cray-CNL-interlagos: cray-mpich
    buildable: False
  netcdf:
    modules:
      netcdf@4.4.0%pgi@15.7.0 arch=cray-CNL-interlagos: cray-netcdf-hdf5parallel/4.4.0
    buildable: False
  hdf5:
    modules:
      hdf5@1.8.16%pgi@15.7.0 arch=cray-CNL-interlagos: cray-hdf5/1.8.16
    buildable: False
  all:
    compiler: [pgi@15.7.0]
    providers:
      mpi: [mpich, openmpi]
      blas: [openblas]
      lapack: [openblas]
```

**Comment by robertdfrench** [comment]
Hi @sarich,

When I build against cray-mpich, I usually lie to Spack about what version
of Cray's mpich library is actually being used (since it is effectively
masquerading as vanilla mpich in this context). Can you try using a version
that is available in the mpich package.py file?

Someone more learned than me can weigh in on whether or not that actually
matters.

**Comment by sarich** [comment]
I tried changing the package.yaml to 
```
mpich:
    modules:
      mpich@3: cray-mpich
    buildable: False
```

But I'm still getting the same error. 

I added some debugging prints to concretize.py, it looks like this is related to issue #1622 
```usable= [mpich@3, mpich@3, openmpi@1.6.5, openmpi@1.7.5:, openmpi@2.0.0:,```
``` intel-parallel-studio@cluster:+mpi, mvapich2@2.0:, mvapich2@1.9]```
```candidates= [mpich@1:, mpich@3:, openmpi@1.6.5, openmpi@1.7.5:, ```
```openmpi@2.0.0:, intel-parallel-studio@cluster:+mpi, mvapich2@2.0:, mvapich2@1.9]````

The python error occurs when trying to index ```'mpich@3'``` in ```candidates```, where this value has a colon attached.

I tried setting ```external_spec.namespace='builtin'``` in config.py, it didn't change anything.
