### ISSUE TITLE
per-package setting for --run-tests and --keep-stage in packages.yaml

### ISSUE THREAD

**Issue by davydden** [spack/spack#2223]
Would be good to have a per-package setting for `--run-tests`  and `--keep-stage` in `packages.yaml`. 

Say if I build a huge graph, but care about running small tests only for a few packages, i could add
```
packages:
  all:
    run-tests: false
    keep-stage: false
  petsc:
    run-tests: true
    keep-stage: false
  dealii:
    run-tests: true
    keep-stage: true
```

ps. CLI would still take precedence to settings in `packages.yaml`.
