### ISSUE TITLE
Quirk in `spack spec -lI`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2305]
Note how it doesn't think OpenSSL is installed. This seems like a quirk (not quite a bug, but I don't think it was intended either):
```
[+]  glayfkq          ^curl@7.50.3%gcc@4.9.3 arch=linux-centos7-x86_64
[-]  nhr6nvf              ^openssl@system%gcc@4.9.3 arch=linux-centos7-x86_64
[+]  gs5rqbz          ^expat@2.2.0%gcc@4.9.3 arch=linux-centos7-x86_64
```
`openssl` is set up in my `packages.yaml`:
```
    openssl:
        paths:
            openssl@system: /false/path
        version: [system]
        buildable: False
```
