### ISSUE TITLE
Spack does not respect openmpi version

### ISSUE THREAD

**Issue by aprokop** [spack/spack#2342]
I have the following in my `~/.spack/packages.yml`
```yaml
packages:
    all:
        providers:
            mpi: [openmpi]

    gcc:
        version: [4.8.5]
        variants: ~binutils
    openmpi:
        version: [1.8.8]
    zlib:
        version: [1.2.8]
    libxml2:
        version: [2.9.2]
        variants: ~python
    boost:
        version: [1.55.0]
        variants: +mpi
    hdf5:
        version: [1.8.12]
        variants: ~fortran +mpi
    parallel-netcdf:
        version: [1.6.1]
        variants: ~fortran
    netcdf:
        version: [4.3.3.1]
        variants: +mpi +parallel-netcdf ~shared
    cmake:
        version: [3.1.0]
```
Testing on openmpi works as it fetches the correct 1.8.8 version:
```
$ spack spec -I openmpi
     openmpi@1.8.8%gcc@6.2.1~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-fedora24-x86_64
         ^hwloc@1.11.4%gcc@6.2.1 arch=linux-fedora24-x86_64
             ^libpciaccess@0.13.4%gcc@6.2.1 arch=linux-fedora24-x86_64
                 ^libtool@2.4.6%gcc@6.2.1 arch=linux-fedora24-x86_64
                     ^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux-fedora24-x86_64
                         ^libsigsegv@2.10%gcc@6.2.1 arch=linux-fedora24-x86_64
                 ^pkg-config@0.29.1%gcc@6.2.1+internal_glib arch=linux-fedora24-x86_64
                 ^util-macros@1.19.0%gcc@6.2.1 arch=linux-fedora24-x86_64
```
However, testing on boost produces
```
$ spack spec -I boost
  boost@1.55.0%gcc@6.2.1+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math+mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=linux-fedora24-x86_64
         ^bzip2@1.0.6%gcc@6.2.1 arch=linux-fedora24-x86_64
         ^openmpi@2.0.1%gcc@6.2.1~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-fedora24-x86_64
             ^hwloc@1.11.4%gcc@6.2.1 arch=linux-fedora24-x86_64
                 ^libpciaccess@0.13.4%gcc@6.2.1 arch=linux-fedora24-x86_64
                     ^libtool@2.4.6%gcc@6.2.1 arch=linux-fedora24-x86_64
                         ^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux-fedora24-x86_64
                             ^libsigsegv@2.10%gcc@6.2.1 arch=linux-fedora24-x86_64
                     ^pkg-config@0.29.1%gcc@6.2.1+internal_glib arch=linux-fedora24-x86_64
                     ^util-macros@1.19.0%gcc@6.2.1 arch=linux-fedora24-x86_64
         ^zlib@1.2.8%gcc@6.2.1 arch=linux-fedora24-x86_64
```
So it picks up openmpi 2.0.1 instead of 1.8.8. Same thing happens when trying other packages depending on mpi, such as hdf5
```
$ spack spec -I hdf5
     hdf5@1.8.12%gcc@6.2.1+cxx~debug~fortran+mpi+shared~szip~threadsafe arch=linux-fedora24-x86_64
         ^openmpi@2.0.1%gcc@6.2.1~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-fedora24-x86_64
             ^hwloc@1.11.4%gcc@6.2.1 arch=linux-fedora24-x86_64
                 ^libpciaccess@0.13.4%gcc@6.2.1 arch=linux-fedora24-x86_64
                     ^libtool@2.4.6%gcc@6.2.1 arch=linux-fedora24-x86_64
                         ^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux-fedora24-x86_64
                             ^libsigsegv@2.10%gcc@6.2.1 arch=linux-fedora24-x86_64
                     ^pkg-config@0.29.1%gcc@6.2.1+internal_glib arch=linux-fedora24-x86_64
                     ^util-macros@1.19.0%gcc@6.2.1 arch=linux-fedora24-x86_64
         ^zlib@1.2.8%gcc@6.2.1 arch=linux-fedora24-x86_64
```

Am I doing something wrong here?

**Comment by adamjstewart** [comment]
I've noticed this behavior as well. It seems like `packages.yaml` is only consulted when you are explicitly installing that package. If the package is listed as a dependency, your preferences are ignored. See #1371 for another example of this.

**Comment by aprokop** [comment]
> It seems like packages.yaml is only consulted when you are explicitly installing that package. If the package is listed as a dependency, your preferences are ignored.

I don't know if it's true. It seems that for instance netcdf changes the version of its hdf5 dependency depending on whether it is in packages.yaml or not. I wonder if this is a question of whether the dependency is virtual or not, as they seem to be treated differently in `spec.py` (line 1157)
```python
            # Concretize virtual dependencies last.  Because they're added
            # to presets below, their constraints will all be merged, but we'll
            # still need to select a concrete package later.
            if not self.virtual:
                changed |= any(
                    (spack.concretizer.concretize_architecture(self),
                     spack.concretizer.concretize_compiler(self),
                     spack.concretizer.concretize_compiler_flags(
                         self),  # has to be concretized after compiler
                     spack.concretizer.concretize_version(self),
                     spack.concretizer.concretize_variants(self)))
            presets[self.name] = self
```
The `concretize_version` in `concretizer.py` seems like the right place for establishing the version, and the above code in `spec.py` seems like the only place that calls it.

**Comment by adamjstewart** [comment]
Maybe this is more complicated than I anticipated. With a simple `packages.yaml` like:
```yaml
packages:
  mpc:
    version: [1.0.2]
    compiler: [intel]
```
`spack spec mpc` builds everything with `%gcc`, but `spack spec gcc` builds everything (including mpc) with `%gcc`. But both of those commands pick up the requested version from `packages.yaml`. Perhaps you are right that the version problem is specific to hdf5 or to mpi, but the compiler problem is related to which package you explicitly install.
