### ISSUE TITLE
External variants hang concretization

### ISSUE THREAD

**Issue by zzzoom** [spack/spack#2693]
With the following packages.yaml, running `spack spec fftw%gcc@5.4.0+mpi ^openmpi@2.0.1%gcc@5.4.0` gets stuck indefinitely in concretization.

```
packages:
  openmpi:
    paths:
      openmpi@2.0.1 %gcc@5.4.0 +mxm +pmi +slurm +verbs arch=linux-centos6-x86_64: /opt/openmpi/2.0.1-gcc_5-cuda_8.0-mellanox
```

After removing the variants from packages.yaml the problem goes away and I can build fftw+mpi without issues.
