### ISSUE TITLE
freetype: Cannot build with external libpng

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2752]
I'm trying to build `freetype` with the following in my `packages.yaml`:
```
    # yum: libpng-devel
    libpng:
        paths:
            libpng@1.5.13: /usr
        version: [1.5.13]
        buildable: False
```
Freetype then complains with the enclosed log. [spack-build.out.txt](https://github.com/LLNL/spack/files/687914/spack-build.out.txt)

The problem is, it's not able to find `libpng` --- not with `pkg-config`, and not with an env var telling `freetype` where it is:
```
checking for LIBPNG... no
checking for libpng-config... Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
```

Any suggestions on how to resolve this?  (Other than using a Spack-built `libpng`, which is what I'm doing now)?
