### ISSUE TITLE
Understanding --install-status with command spack spec

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2815]
Trying to understand output of `spack spec -I`. In below example I have specified *mpich* and *automake* as externally installed package in *packages.yaml*. `spack spec -I` shows `[-]`  for `mpich` but not for `autoconf`, `libtool`, `automake` etc.

My expectation was to see `[+]` for externally installed packages as well.
Could someone clarify?

`packages.yaml` is:

```
................
    mpich:
        paths:
            mpich@3.2: /usr/local
        buildable: False
        version: [3.2]

    automake:                                 //same for autoconf, libtool etc
        paths:
            automake@system: /usr/local
        buildable: False
        version: [system]
............
```

And `spack spec -I` gives:
```
spack spec -Il neuronperfmodels@neuron '^reportinglib+static' %clang
Input spec
--------------------------------
     qwm2sld  neuronperfmodels@neuron
     jikxgl4      ^reportinglib%clang+static

Normalized
--------------------------------
     rrpdbfr  neuronperfmodels@neuron
     qzuc2dn      ^cmake@2.8.12:
     uqxsqv5      ^hdf5
     j52z7qb          ^zlib@1.1.2:
     2xnea7r      ^mpi
     ci6h75q      ^neuron
     giq2nnl          ^autoconf
     gwv2ucp              ^m4@1.4.6:
     qdutste          ^automake
     mbrra2l          ^libtool
     lbqdjps          ^pkg-config%clang
     meerqbd      ^reportinglib%clang+static

Concretized
--------------------------------
     xrhgrtl  neuronperfmodels@neuron%clang@3.9.0~profile arch=darwin-elcapitan-x86_64
     tesxhxo      ^cmake@3.5.2%clang@3.9.0~doc+ncurses+openssl+ownlibs~qt arch=darwin-elcapitan-x86_64
     toxmufu      ^hdf5@1.8.17%clang@3.9.0+cxx~debug~fortran+mpi+pic+shared~szip~threadsafe arch=darwin-elcapitan-x86_64
[-]  klcnbph      ^mpich@3.2%clang@3.9.0+hydra+pmi+romio~verbs arch=darwin-elcapitan-x86_64
     f76ksdo      ^neuron@develop%clang@3.9.0~cross-compile+mpi~profile+python+static arch=darwin-elcapitan-x86_64
     6mbumme          ^autoconf@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
     rdjfvva          ^automake@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
     qidhy7e          ^libtool@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
     2xkpyqa          ^pkg-config@system%clang@3.9.0+internal_glib arch=darwin-elcapitan-x86_64
     675gjmc          ^python@2.7.10%clang@3.9.0~tk~ucs4 arch=darwin-elcapitan-x86_64
[+]  ha22so4      ^reportinglib@develop%clang@3.9.0~profile+static arch=darwin-elcapitan-x86_64
```
