### ISSUE TITLE
spack refuses to install mercurial on NERSC cori

### ISSUE THREAD

**Issue by amklinv** [spack/spack#2816]
@BarrySmith @tgamblin

I'm trying to use spack to install the xsdk package on NERSC's cori, using the barry/xsdk branch.  Spack crashes during the last stage, installing pflotran, because it needs mercurial to fetch pflotran.  I tried using the mercurial module available on cori, which didn't work.  (See #1645 and #2811)  Then I tried having spack install mercurial for me, which it did not want to do.

```
amklinv@cori02:~/cori/spack/bin> ./spack install mercurial
==> Installing mercurial
==> py-docutils is already installed in /global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/py-docutils-0.12-tmg4ex555o5ytsir6swkatqcdqy5g53i
==> python is already installed in /global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/python-2.7.13-aum5cm2nu2dj6xabkwi3rzwqfuq3xtmx
==> Using cached archive: /global/u1/a/amklinv/cori/spack/var/spack/cache/mercurial/mercurial-3.9.1.tar.gz
==> Already staged mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2 in /global/u1/a/amklinv/cori/spack/var/spack/stage/mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2
==> No patches needed for mercurial
==> Building mercurial [Package]
==> Executing phase : 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32' 'install' 'PREFIX=/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2'
/global/u1/a/amklinv/cori/spack/var/spack/repos/builtin/packages/mercurial/package.py:48, in install:
     47       def install(self, spec, prefix):
  >> 48           make('install', 'PREFIX={0}'.format(prefix))
     49
     50           # Configuration of HTTPS certificate authorities
     51           # https://www.mercurial-scm.org/wiki/CACertificates
     52           hgrc_filename = join_path(prefix.etc, 'mercurial', 'hgrc')
     53           mkdirp(os.path.dirname(hgrc_filename))
     54
     55           with open(hgrc_filename, 'w') as hgrc:
     56               if os.path.exists('/etc/ssl/certs/ca-certificates.crt'):
     57                   # Debian/Ubuntu/Gentoo/Arch Linux
     58                   hgrc.write('[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt')  # noqa
     59               elif os.path.exists('/etc/pki/tls/certs/ca-bundle.crt'):
     60                   # Fedora/RHEL/CentOS
     61                   hgrc.write('[web]\ncacerts = /etc/pki/tls/certs/ca-bundle.crt')
     62               elif os.path.exists('/etc/ssl/ca-bundle.pem'):
     63                   # openSUSE/SLE
     64                   hgrc.write('[web]\ncacerts = /etc/ssl/ca-bundle.pem')
     65               else:
     66                   tty.warn('CA certificate not found. You may not be able to '
     67                            'connect to an HTTPS server. If your CA certificate '
     68                            'is in a non-standard location, you should add it to '
     69                            '{0}'.format(hgrc_filename))

See build log for details:
  /tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/spack-build.out
```
```
amklinv@cori02:~/cori/spack/bin> cat /tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/spack-build.out
==> 'make' '-j32' 'install' 'PREFIX=/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2'
python setup.py  build
make -C doc
make[1]: Entering directory '/tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/doc'
cd doc && make -j --jobserver-fds=15,16 install
make[1]: Entering directory '/tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/doc'
for i in hg.1 hgignore.5 hgrc.5 hg-ssh.8 ; do \
  subdir=`echo $i | sed -n 's/^.*\.\([0-9]\)$/man\1/p'` ; \
  mkdir -p /global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2/share/man/$subdir ; \
  install -c -m 644 $i /global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/mercurial-3.9.1-nbquc2hhudv5tioe76yq5wmoxuyuexs2/share/man/$subdir ; \
done
running build
running build_mo
make[1]: Leaving directory '/tmp/amklinv/spack-stage/spack-stage-Dze5h5/mercurial-3.9.1/doc'
running build_py
copying mercurial/__modulepolicy__.py -> build/lib.linux-x86_64-2.7/mercurial
running build_ext
building 'mercurial.base85' extension
/global/u1/a/amklinv/cori/spack/lib/spack/env/gcc/gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -I/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/python-2.7.13-aum5cm2nu2dj6xabkwi3rzwqfuq3xtmx/include/python2.7 -c mercurial/base85.c -o build/temp.linux-x86_64-2.7/mercurial/base85.o
/opt/cray/pe/craype/2.5.7/bin/cc -shared -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/bzip2-1.0.6-js6dsfr4ifivstb2bdx6zv5wxddgn3u2/lib -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/ncurses-6.0-ti24btafu5zwhzgzcy5in43e5weafmyr/lib -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/zlib-1.2.10-aixjrovjk3dib5regbxkbxfslevn5tip/lib -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/openssl-1.0.2j-xlx57k4cycp7nqpjzvqwwcwx6rmlgked/lib -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/sqlite-3.8.5-7bhh4zabny4jon6rbefcl5mdd32cu3on/lib -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/readline-6.3-m5k57f2ifjsleqw6tazdyrjhhuvtyjbs/lib build/temp.linux-x86_64-2.7/mercurial/base85.o -L/global/u1/a/amklinv/cori/spack/opt/spack/cray-CNL-haswell/gcc-6.2.0/python-2.7.13-aum5cm2nu2dj6xabkwi3rzwqfuq3xtmx/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/mercurial/base85.so
error: command '/opt/cray/pe/craype/2.5.7/bin/cc' failed with exit status 11
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by becker33** [comment]
@amklinv @tgamblin I was able to install mercurial from the tip of develop today on Cori. I did so both with and without the mercurial module loaded on the system.

@amklinv On what commit did you see this error?

**Comment by amklinv** [comment]
I am using the barry/xsdk branch, on commit

```
amklinv@cori07:~/cori/spack> git log
commit 87ac588fe76fa37c7abf8ac70e96b9c1c52bf1a2
Author: Barry Smith <bsmith@mcs.anl.gov>
Date:   Tue Jan 3 13:45:45 2017 -0600

    PETSc needs c++11 when built with Trilinos
```

**Comment by becker33** [comment]
I was able to build mercurial on the barry/xsdk branch on Cori. What was your packages.yaml file? Were you building default mercurial (`spack install mercurial`) or did you select other options?

**Comment by becker33** [comment]
Closing this as not reproducible. Feel free to reopen if the problem persists.

**Comment by amklinv** [comment]
Thank you for trying to reproduce this, @becker33!  Here are my yaml files, which I placed in etc/spack/cray.  (I didn't want to put them in .spack because I would also like to use spack on edison.)  I tried moving the files to .spack, but I got the same error.  I tried wiping out both etc/spack/cray and .spack...same error.  If I wipe out all of those directories and start from a clean spack clone, this error doesn't occur.

If it would help, I'm very willing to set up a screen sharing meeting.  Please contact me at amklinv@sandia.gov if this is something you're interested in.

```
amklinv@cori02:~/cori/spack> cat etc/spack/cray/compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - gcc/6.2.0
    operating_system: CNL
    paths:
      cc: /opt/cray/pe/craype/2.5.7/bin/cc
      cxx: /opt/cray/pe/craype/2.5.7/bin/CC
      f77: /opt/cray/pe/craype/2.5.7/bin/ftn
      fc: /opt/cray/pe/craype/2.5.7/bin/ftn
    spec: gcc@6.2.0
```
```
amklinv@cori02:~/cori/spack> cat etc/spack/cray/packages.yaml
packages:
  mpich:
    modules:
      mpich@7.4.4%gcc@6.2.0 arch=cray-CNL-haswell : cray-mpich/7.4.4
    buildable: False
  all:
    providers:
      mpi: [mpich]
```

**Comment by tgamblin** [comment]
@amklinv: I was able to just install `mercurial` from scratch on Cori as well, three ways:

1. On `develop` with a default `compilers.yaml` generated by `spack compiler find`
1. On `develop` with your `compilers.yaml`
1. On `barry/xsdk` with your `compilers.yaml`

I'm not sure what is up.  

Just out of curiosity, can you type `module list` and paste the output?  Here is mine:

```console
$ module list
Currently Loaded Modulefiles:
  1) modules/3.2.6.7                   9) ugni/6.0.12-2.1                  17) rca/1.0.0-8.1
  2) nsg/1.2.0                        10) pmi/5.0.10-1.0000.11050.0.0.ari  18) atp/2.0.3
  3) modules/3.2.10.5                 11) dmapp/7.1.0-12.37                19) PrgEnv-intel/6.0.3
  4) intel/17.0.1.132                 12) gni-headers/5.0.7-3.1            20) craype-haswell
  5) craype-network-aries             13) xpmem/0.1-4.5                    21) cray-shmem/7.4.4
  6) craype/2.5.7                     14) job/1.5.5-3.58                   22) cray-mpich/7.4.4
  7) cray-libsci/16.09.1              15) dvs/2.7_0.9.0-2.221
  8) udreg/2.3.2-4.6                  16) alps/6.1.3-17.12
```

I am curious whether you have something loaded that I don't, or that might interfere with your build environment.  One issue with the Cray platform is that `module purge` renders the environment unusable, so we can't sanitize the build environment nearly as well as we'd like.  But we do try to clean out PrgEnv and compiler modules... which I believe covers most of the potential issues.

**Comment by amklinv** [comment]
Here's my environment:
```
amklinv@cori02:~> module list
Currently Loaded Modulefiles:
  1) modules/3.2.6.7                   7) cray-libsci/16.09.1              13) xpmem/0.1-4.5                    19) PrgEnv-intel/6.0.3
  2) nsg/1.2.0                         8) udreg/2.3.2-4.6                  14) job/1.5.5-3.58                   20) craype-haswell
  3) modules/3.2.10.5                  9) ugni/6.0.12-2.1                  15) dvs/2.7_0.9.0-2.221              21) cray-shmem/7.4.4
  4) intel/17.0.1.132                 10) pmi/5.0.10-1.0000.11050.0.0.ari  16) alps/6.1.3-17.12                 22) cray-mpich/7.4.4
  5) craype-network-aries             11) dmapp/7.1.0-12.37                17) rca/1.0.0-8.1                    23) altd/2.0
  6) craype/2.5.7                     12) gni-headers/5.0.7-3.1            18) atp/2.0.3                        24) darshan/3.0.1
```

And here are the important steps needed to reproduce my problem:
```
amklinv@cori02:~> rm -rf spack .spack

amklinv@cori02:~> git clone https://github.com/LLNL/spack.git

amklinv@cori02:~/spack/etc/spack/cray> cat compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - gcc/6.2.0
    operating_system: CNL
    paths:
      cc: /opt/cray/pe/craype/2.5.7/bin/cc
      cxx: /opt/cray/pe/craype/2.5.7/bin/CC
      f77: /opt/cray/pe/craype/2.5.7/bin/ftn
      fc: /opt/cray/pe/craype/2.5.7/bin/ftn
    spec: gcc@6.2.0

amklinv@cori02:~/spack/etc/spack/cray> cat packages.yaml
packages:
  mpich:
    modules:
      mpich@7.4.4%gcc@6.2.0 arch=cray-CNL-haswell : cray-mpich/7.4.4
    buildable: False
  all:
    providers:
      mpi: [mpich]

./spack install mercurial
```

Here's my complete history for the day:
```
 1002  rm -rf spack .spack
 1003  module list
 1004  history | grep clone
 1005  git clone https://github.com/LLNL/spack.git
 1006  cd spack/etc/spack/
 1007  vim compilers.yaml
 1008  vim packages.yaml
 1009  ls
 1010  mkdir cray
 1011  mv *.yaml cray/
 1012  cd cray/
 1013  ls
 1014  cat compilers.yaml
 1015  cat packages.yaml
 1016  cd ..
 1017  ls
 1018  cd ../../
 1019  ls
 1020  cd bin/
 1021  ./spack install mercurial
 1022  history
```
