### ISSUE TITLE
GCC error : error while installing Tau on MIRA @ALCF

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2828]
I am trying to install our software stack including `Tau` on `MIRA` after few weeks (doing this regularly on other bg-q system without any issue). I can install Tau stand-alone (with the same command) but when I try within Spack I get: 

```
gcc    -O2 -Wl,-rpath,/gpfs/mira-home/kumbhar/spack/opt/spack/bgq-cnk-ppc64/xl-12.1/tau-2.25-4fm5bofq4jr2fnn6tv6hf2ssqqdjxhyq/lib -Wl,-rpath,/gpfs/mira-home/kumbhar/spack/opt/spack/bgq-cnk-ppc64/xl-12.1/tau-2.25-4fm5bofq4jr2fnn6tv6hf2ssqqdjxhyq/lib64 -Wl,-rpath,/bgsys/drivers/ppcfloor/comm/xl/lib -I../include -DTAU_DOT_H_LESS_HEADERS -DTAU_XLC  -w         -c tau_merge.c

In file included from tau_merge.c:14:
/usr/include/stdio.h:34:21: error: stddef.h: No such file or directory
In file included from /usr/include/stdio.h:75,
                 from tau_merge.c:14:
/usr/include/libio.h:53:21: error: stdarg.h: No such file or directory
In file included from /usr/include/stdio.h:75,
                 from tau_merge.c:14:
```

above `gcc` is for `front-end` which is specified in `compilers.yaml` as:
```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
```
Wondering whats going on (from wrapper?). Any suggestion?
