### ISSUE TITLE
Unable to build Perl with Intel

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2930]
Has anyone ever had problems building Perl with the Intel compilers? I'm seeing:
```
ld: cannot find -lm
ld: cannot find -lcilkrts
ld: cannot find -lc
ld: cannot find -ldl
ld: cannot find -lc
ld: cannot find -lm
ld: cannot find -lcilkrts
```
I've tried with both Intel 16 and 17.

**Comment by weijianwen** [comment]
I failed to build Perl 5.24.0 with Intel compiler 16.0, which gave different error messages.

```
$ spack install perl@5.24.0 %intel@16.0.3
...
cc  -shared -O2 -L/usr/local/lib re_exec.o re_comp.o re.o  -o ../../lib/auto/re/re.so   \
        \

ld: re_exec.o: relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a shared object; recompile with -fPIC
re_exec.o: error adding symbols: Bad value
make[1]: *** [../../lib/auto/re/re.so] Error 1
make[1]: Leaving directory `/tmp/pytest-of-rpm/pytest-4/test_fetch0/tmp/spack-stage/spack-stage-tb4QzE/perl-5.24.0/ext/re'
make[1]: Entering directory `/tmp/pytest-of-rpm/pytest-4/test_fetch0/tmp/spack-stage/spack-stage-tb4QzE/perl-5.24.0/ext/re'
rm -f ../../lib/auto/re/re.so
cc  -shared -O2 -L/usr/local/lib re_exec.o re_comp.o re.o  -o ../../lib/auto/re/re.so   \
        \

Processing LineBreak.txt
ld: re_exec.o: relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a shared object; recompile with -fPIC
re_exec.o: error adding symbols: Bad value
make[1]: *** [../../lib/auto/re/re.so] Error 1
make[1]: Leaving directory `/tmp/pytest-of-rpm/pytest-4/test_fetch0/tmp/spack-stage/spack-stage-tb4QzE/perl-5.24.0/ext/re'
Unsuccessful make(ext/re): code=512 at make_ext.pl line 569.
make: *** [lib/auto/re/re.so] Error 25
```

Intel compiler 16.0.3 is configured as follows in `~/.spack/linux/compilers.yml`:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: [icc/16.0]
    operating_system: centos7
    paths:
      cc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
      cflags: -gcc-name /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/gcc
      cxx: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
      cxxflags: -gxx-name /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/g++
      f77: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
      fc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
      fflags: -gcc-name /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/gcc
    spec: intel@16.0.3
    target: x86_64
```

**Comment by adamjstewart** [comment]
Your cflags and friends are in the wrong place. They should be under flags, not paths.

**Comment by weijianwen** [comment]
Thank you @adamjstewart . I tried to install Perl with the following updated configuration.

```
- compiler:
    environment: {}
    extra_rpaths: []
    modules:
      - icc/16.0
    operating_system: centos7
    paths:
      cc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
      cxx: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
      f77: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
      fc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
    flags:
      cflags: -gcc-name=/lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/gcc
      cxxflags: -gxx-name=/lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/g++
      fflags: -gcc-name=/lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/bin/gcc
    spec: intel@16.0.3
    target: x86_64
```

However, it complains that CC is unsuable this time. Removing those `-gcc-name` settings results a usable CC compiler while giving the same `-fPIC` errors as before.

```
You appear to have ELF support.  I'll try to use it for dynamic loading.
If dynamic loading doesn't work, read hints/linux.sh for further information.
Operating system name? [linux]
Operating system version? [3.10.0-514.2.2.el7.x86_64]
Installation prefix to use? (~name ok)
[/lustre/spack/tools/linux-centos7-x86_64/intel-16.0.3/perl-5.24.0-7hf5uwdbfnurzalyxhyw6cerdsfck62o]
AFS does not seem to be running...
What installation prefix should I use for installing files? (~name ok)
[/lustre/spack/tools/linux-centos7-x86_64/intel-16.0.3/perl-5.24.0-7hf5uwdbfnurzalyxhyw6cerdsfck62o]
Getting the current patchlevel...
Build a threading Perl? [n]
Build Perl for multiplicity? [n]
Use which C compiler? [cc]
ld: /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/lib64/gcc/x86_64-unknown-linux-gnu/5.4.0/crtbegin.o: unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
Uh-oh, the C compiler 'cc' doesn't seem to be working.
You seem to have a working gcc, though.

*** However, any setting of the C compiler flags (e.g. for thread support)
*** will be lost.  It may be necessary for you to restart Configure and
*** add -Dcc=gcc to your Configure command line.

Would you like to go ahead and try gcc anyway? [n]
ld: /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-66o72l5drxzzfs4o6nt2olm276vdtiv3/lib64/gcc/x86_64-unknown-linux-gnu/5.4.0/crtbegin.o: unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
Uh-oh, the C compiler 'cc' doesn't seem to be working.
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
```

**Comment by weijianwen** [comment]
Removing GCC emulatigon settings and adding the `-fPIC` flag to `intel@16` compiler solves my issue. I've successfully build Perl 5.24.0 with Intel 16.0 compiler. I am not sure adding `-fPIC` globally is a good practice and wonder if we can customize cflag for the Perl package.

```
- compiler:
    environment: {}
    extra_rpaths: []
    modules:
      - icc/16.0
    operating_system: centos7
    paths:
      cc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
      cxx: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
      f77: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
      fc: /lustre/usr/intel_cluster_studio/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
    flags:
      cflags: -fPIC
      cxxflags: -fPIC
      fflags: -fPIC
    spec: intel@16.0.3
    target: x86_64
```
