### ISSUE TITLE
External packages: bug when version is not specified

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3164]
Assuming `gcc@4.4.7` is in `compilers.yaml`, the following `packages.yaml` work for `spack spec py-numpy`:
```yaml
packages:
  python:
    paths:
      python@2.6.6: /usr
    buildable: False
```
```yaml
packages:
  python:
    paths:
      python@2.6.6%gcc@4.4.7: /usr
    buildable: False
```
Even if only a single GCC 4 is in `compilers.yaml`, the following `packages.yaml` results in the error message:
```
==> Error: The spec 'python' is configured as not buildable, and no matching external installs were found
```
```yaml
packages:
  python:
    paths:
      python@2.6.6%gcc@4: /usr
    buildable: False
```
All of the following `packages.yaml` cause `spack spec py-numpy` to hang indefinitely. An informative error message would be appreciated:
```yaml
packages:
  python:
    paths:
      python@2.6.6%gcc: /usr
    buildable: False
```
```yaml
packages:
  python:
    paths:
      python%gcc@4.4.7: /usr
    buildable: False
```
```yaml
packages:
  python:
    paths:
      python: /usr
    buildable: False
```
