### ISSUE TITLE
Want easier way to specify compiler

### ISSUE THREAD

**Issue by eschnett** [spack/spack#3372]
When I install a package on macOS, I often prefer to install with my own version of `gcc@6`. However, certain packages don't build with GCC, and require Apple's Clang instead. The packages that require Clang are often "unimportant" for my application (bison, cmake, gettext, pkg-config, python).

It is unfortunately very difficult to tell Spack "build everything with `%gcc`, except for these few packages". I end up having to specify a compiler for almost every package. If I don't, Spack might make a wrong choice, and use Clang for a package which I need to have installed via GCC. (For example, if package A requires B, and B contains C++ code that is linked in, then it needs to be built with GCC as well.)

In the end, this means that I need to run `spack spec` to find out what dependencies there are, and explicitly list most of these with `%gcc`. This is amazingly tedious.

I would like to have a feature where I tell Spack: "Install all packages with `%gcc`, except for those packages where I explicitly specify something different".

**Comment by davydden** [comment]
> It is unfortunately very difficult to tell Spack "build everything with %gcc, except for these few packages"

no, it is not. Look at `packages.yaml`, e.g.
```
packages:
  all:
    compiler: [clang, gcc]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
  cmake:
    compiler: [clang]
```
