### ISSUE TITLE
External packages for multiple OSes

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3508]
I'm managing two clusters, one of which runs CentOS 6 while the other runs CentOS 7. With a `packages.yaml` like:
```yaml
packages:
  flex:
    paths:
      flex@2.5.37 arch=linux-centos7-x86_64: /usr
      flex@2.5.35 arch=linux-centos6-x86_64: /usr
    buildable: False
```
things work great on CentOS 7. But on CentOS 6, I'm seeing:
```
$ spack spec flex
...
==> Error: The spec 'flex' is configured as not buildable, and no matching external installs were found
```
If I had to guess, I bet it's choosing `flex@2.5.37` because it's newer, and then getting an error because `arch=linux-centos7-x86_64` says it isn't for CentOS 6.

**Comment by davydden** [comment]
i guess a workaround is to pin the version by `version: [2.5.35]` in the file used on CentOS6.

**Comment by davydden** [comment]
I would have gotten the same issues with `openmpi` (current newest is `2.0.2`) on `Centos7` cluster if I would not be doing
```
openmpi:
    version: [2.0.1]
    paths:
      openmpi@2.0.1%gcc@4.8.5: /apps/OpenMPI/2.0.1-gcc/
    buildable: False
```
which works perfectly.

**Comment by adamjstewart** [comment]
@davydden The `version` setting doesn't make a difference in this case. The only reason that your `packages.yaml` works for you is because you don't specify an `arch` to use. For my case, the home directory and Spack installation directory are in a shared GPFS mount, so there is no "file used on CentOS6". If I pinned the version to be the one on CentOS 6, things would work on 6 and break on 7. If we could expand `linux/packages.yaml` to be more specific: `linux-centos6-x86_64`, that would help alleviate the problem, but wouldn't really solve it.

**Comment by davydden** [comment]
> For my case, the home directory and Spack installation directory are in a shared GPFS mount, so there is no "file used on CentOS6".

oh, i see now. Yes, then you can not indeed pin the version.

The other workaround which comes to mind is to pretend that both are the same version and pit it. 

But I agree, there should be a way to do it properly. How about `buildable: False` making conretizer choose among versions specified in the file as opposed to all possible options? Essentialy, "I don't want to build it, just use what i have, or throw and error if you can't conretize a package".

**Comment by citibeth** [comment]
Would #2700 help?   It would not be hard to implement.  You should also be able to get immediate relief using #2686 and a couple of Bash aliases.

**Comment by adamjstewart** [comment]
#2700 would certainly help. I still think it's a bug that what I'm trying to do doesn't work, but #2700 seems like a good idea regardless.

**Comment by alalazo** [comment]
Works with `clingo`. I used:
```yaml
opengl:
    paths:
      opengl@4.5.0 arch=linux-rhel7-x86_64: /opt/mesa/17.3
      opengl@4.2.0 arch=linux-rhel7-ppc64le: /opt/mesa/17.1
    buildable: False
```
on:
* **Spack:** 0.17.1-1520-9ab21024e2
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

It always selects the ubuntu external. If I comment it out:
```
$ spack spec opengl
==> Error: opengl is unsatisfiable, errors are:
  External package does not satisfy external spec

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs

```
