### ISSUE TITLE
Bug in spec resolution of virtual dependencies

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3764]
I'm trying to build `hpl`, which contains:
```python
depends_on('mpi@1.1:')                                                      
depends_on('blas')
```
The concretized spec looks like:
```
$ spack spec hpl
...
hpl@2.2%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX" +openmp arch=linux-centos6-x86_64 
    ^intel-parallel-studio@professional.2017.1%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX" +all+daal~ilp64+ipp+mkl~mpi~newdtags+openmp+rpath+shared+tools arch=linux-centos6-x86_64 
    ^mvapich2@2.2%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX" ~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock arch=linux-centos6-x86_64 
        ^bison@2.4.1%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX"  arch=linux-centos6-x86_64 
        ^libpciaccess@0.13.4%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX"  arch=linux-centos6-x86_64 
            ^libtool@2.2.6b%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX"  arch=linux-centos6-x86_64 
            ^pkg-config@0.23%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX" +internal_glib arch=linux-centos6-x86_64 
            ^util-macros@1.19.1%intel@17.0.2 cflags="-axCORE-AVX512,CORE-AVX2,AVX" cxxflags="-axCORE-AVX512,CORE-AVX2,AVX" fflags="-axCORE-AVX512,CORE-AVX2,AVX"  arch=linux-centos6-x86_64
```
However, `spack install` crashes with the following error message:
```
==> Error: AttributeError: 'Spec' object has no attribute 'mpicc'
```
At first, I thought this was another case of #3487, but that's where things get weird. `mvapich2` defines `self.mpicc`, so I was confused why I would get this error message. On a whim, I added:
```python
print(spec['mpi'].name)
```
to the `hpl` package, only to find that it returns `intel-parallel-studio`.

Now, my `intel-parallel-studio` installation is the `professional` version, so it doesn't come with Intel MPI. I didn't want to reinstall such a large package every time I built something that required BLAS/LAPACK, so I installed it with Spack and added it to my `packages.yaml` file:
```yaml
packages:
all:
    compiler: [intel, gcc, pgi, nag]
    providers:
      blas:   [intel-parallel-studio]
      lapack: [intel-parallel-studio]
      mpi: [mvapich2, mpich, openmpi]
  intel-parallel-studio:
    paths:
      intel-parallel-studio@professional.2017.1+all+daal~ilp64+ipp+mkl~mpi~newdtags+openmp+rpath+shared+tools arch=linux-centos6-x86_64: /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4
    buildable: False
```
Here I'm clearly setting `~mpi` because it doesn't provide MPI. Yet for some reason, `spec['mpi']` resolves to `spec['intel-parallel-studio']`. And for some reason, `spack spec hpl` correctly adds `mvapich2` to the list of dependencies.

My theory is that there's a bug in the way we specify provides in the `intel-parallel-studio` package:
```python
provides('mpi', when='@cluster:+mpi')
```
I have a feeling that `@professional.2017.1` satisfies `@cluster:`. But I don't see why it would satisfy `+mpi` since I clearly marked it as `~mpi` in my `packages.yaml`. And I don't understand why `spack spec` would correctly choose `mvapich2` but `spec['mpi']` wouldn't.

By the way, I tried:
```
$ spack install hpl ^openblas
```
and that succeeded, so it's definitely a problem with `intel-parallel-studio` being mistakenly picked up as the MPI provider.

@tgamblin @alalazo you may want to look at this.
