### ISSUE TITLE
spack compiler find adds python unicode strings

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3842]
Just noticed this interesting behavior. I deleted my `compilers.yaml` and `spack compiler find` created a new one that looks like:
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: !!python/unicode '/Library/Developer/CommandLineTools/usr/bin/clang'
      cxx: !!python/unicode '/Library/Developer/CommandLineTools/usr/bin/clang++'
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@8.1.0-apple
    target: x86_64
```
I'm going to investigate why it adds these `!!python/unicode` strings. Just wanted to report it so I can keep track of the bug.
