### ISSUE TITLE
different installations for the same os/architecture, depending on instruction set of the CPU

### ISSUE THREAD

**Issue by samfux84** [spack/spack#3919]
Hi,

when compiling applications and libraries with spack, I would like to compile separate versions that are used depending on which node type a job is running on the cluster. If the compute nodes have a differnt os or a different target architecture, this is not a problem.

But we have for instance different nodes that have the same architecture and os, but differnt CPU's that support different types of instruction sets. All nodes have CentOS 7 and x86_64 architecture, but the oldest nodes support only up to sse4, a newer generation of nodes support avx, and the newest nodes support avx2.

With default settings, spack packages are in my case installed into the directory:

linux-centos7-x86_64

Is it possible to have something like:

linux-centos7-x86_64
linux-centos7-x86_64-avx
linux-centos7-x86_64-avx2

I tried having multiple specifications for the compilers, like for instance:

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O2 -fPIC -ftree-vectorize -march=corei7 -msse4
      cppflags: -O2 -fPIC -ftree-vectorize -march=corei7 -msse4
      cxxflags: -O2 -fPIC -ftree-vectorize -march=corei7 -msse4
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O2 -fPIC -ftree-vectorize -march=core-avx-i -mavx
      cppflags: -O2 -fPIC -ftree-vectorize -march=core-avx-i -mavx
      cxxflags: -O2 -fPIC -ftree-vectorize -march=core-avx-i -mavx
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64-avx
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O2 -fPIC -ftree-vectorize -march=core-avx2 -mavx2
      cppflags: -O2 -fPIC -ftree-vectorize -march=core-avx2 -mavx2
      cxxflags: -O2 -fPIC -ftree-vectorize -march=core-avx2 -mavx2
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64-avx2
```

This results in:
```

[sfux@lo-login-02 ~]$ spack compiler list
==> Available compilers
-- gcc centos7-x86_64 -------------------------------------------
gcc@4.8.5

-- gcc centos7-x86_64-avx ---------------------------------------
gcc@4.8.5

-- gcc centos7-x86_64-avx2 --------------------------------------
gcc@4.8.5
[sfux@lo-login-02 ~]$
```
But when installing a package with

`spack install patch@2.7.5 arch=x86_64-avx2`

then I get the error

```
==> Error: No compilers found for operating system centos7 and target linux-centos7-x86_64-avx2.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
        centos7-x86_64
        centos7-x86_64-avx
        centos7-x86_64-avx2
```
I guess it is because I can not use an identifier for the CPU instruction set as part of the "target". What would be a better way to have separate installations depending on the CPU instruction sets ?
