### ISSUE TITLE
Question/Help with building on the Cray platform

### ISSUE THREAD

**Issue by jgalarowicz** [spack/spack#4828]
I'm hoping someone can point out what I'm doing wrong w.r.t. building on the Cray platform.

I'm trying to port the spack builds of the Krell products to the Cray.  I'm doing that work at NERSC on Cori.   But, when I try to build for the Front end using gcc and the sles12-x86_64, spack says it can't find the compiler.

```
jgalaro@cori10:~/spack> spack install cbtf-krell%gcc@6.3.0 os=sles12
==> Error: No compilers found for operating system sles12 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	CNL-any
	sles12-x86_64
Run 'spack compiler find' to add compilers.

jgalaro@cori10:~/spack> spack install cbtf-krell%gcc@6.3.0 os=sles12-x86_64
==> Error: No compilers found for operating system sles12-x86_64 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	CNL-any
	sles12-x86_64
Run 'spack compiler find' to add compilers.

jgalaro@cori10:~/spack> spack compiler find
==> Added 1 new compiler to /global/homes/j/jgalaro/.spack/cray/compilers.yaml
    gcc@6.3.0
==> Compilers are defined in the following files:
    /global/homes/j/jgalaro/.spack/cray/compilers.yaml

jgalaro@cori10:~/spack> spack install cbtf%gcc@6.3.0 os=sles12-x86_64
==> Error: No compilers found for operating system sles12-x86_64 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	CNL-any
	sles12-x86_64
Run 'spack compiler find' to add compilers.

jgalaro@cori10:~/spack> spack install cbtf%gcc@6.3.0 os=sles12
==> Error: No compilers found for operating system sles12 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	CNL-any
	sles12-x86_64
Run 'spack compiler find' to add compilers.
jgalaro@cori10:~/spack> 
```

```
jgalaro@cori10:~/spack> module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.5                             12) pmi/5.0.10-1.0000.11050.0.0.ari
  2) nsg/1.2.0                                    13) dmapp/7.1.1-39.37
  3) gcc/6.3.0                                    14) gni-headers/5.0.11-2.2
  4) craype-haswell                               15) xpmem/2.1.1_gf9c9084-2.38
  5) craype-network-aries                         16) job/2.1.1_gc1ad964-2.175
  6) craype/2.5.7                                 17) dvs/2.7_2.1.68_g779d71a-1.0000.779d71a.2.34
  7) cray-mpich/7.4.4                             18) alps/6.3.4-2.21
  8) cray-shmem/7.4.4                             19) rca/2.1.6_g2c60fbf-2.265
  9) cray-libsci/16.09.1                          20) atp/2.0.3
 10) udreg/2.3.2-7.54                             21) PrgEnv-gnu/6.0.3
 11) ugni/6.0.15-2.2
```
```yaml
jgalaro@cori10:~/spack> cat ~/.spack/cray/compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.4.2'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.4.2
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.5.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.5.4'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.4
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.5.8'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.8
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.4.4'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.4.4
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.5.1'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.1
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - !!python/unicode 'cce/8.5.7'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.7
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/4.9.3'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@4.9.3
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/5.3.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@5.3.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/6.2.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@6.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/5.2.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@5.2.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/6.1.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@6.1.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - !!python/unicode 'gcc/6.3.0'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@6.3.0
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/16.0.3.210'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@16.0.3.210
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/17.0.1.132'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@17.0.1.132
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/17.0.2.174'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@17.0.2.174
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/17.0.0.098'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@17.0.0.098
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/2018'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@2018
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/17.0.3.191'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@17.0.3.191
    target: any
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /opt/cray/pe/craype/2.5.7/bin/cc
      cxx: /opt/cray/pe/craype/2.5.7/bin/CC
      f77: /opt/cray/pe/craype/2.5.7/bin/ftn
      fc: /opt/cray/pe/craype/2.5.7/bin/ftn
    spec: cce@2.174
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /usr/bin/gcc-4.8
      cxx: /usr/bin/g++-4.8
      f77: null
      fc: null
    spec: gcc@4.8
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/icc
      cxx: /opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/icpc
      f77: /opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort
      fc: /opt/intel/compilers_and_libraries_2017.2.174/linux/bin/intel64/ifort
    spec: intel@17.0.2
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /opt/gcc/6.3.0/bin/gcc
      cxx: /opt/gcc/6.3.0/bin/g++
      f77: /opt/gcc/6.3.0/bin/gfortran
      fc: /opt/gcc/6.3.0/bin/gfortran
    spec: gcc@6.3.0
    target: x86_64
```
