### ISSUE TITLE
variants in packages.yaml not showing up in spec

### ISSUE THREAD

**Issue by mamelara** [spack/spack#4913]
Not sure if this is a duplicate issue but it would be nice to have the ability to specify variants for external packages and have them used. An example:

We want to link with cray-petsc and there are currently 4 different cray-petsc's to link to: 
{cray-petsc, cray-petsc-64, cray-petsc-complex, cray-petsc-complex-64} 

I was hoping to be able to add this to packages.yaml 

```yaml
packages:
   petsc:
       buildable: false
       modules:
             petsc@X.X.X: cray-petsc
             petsc@X.X.X+int64: cray-petsc-64
             petsc@X.X.X+complex: cray-petsc-complex
             petsc@X.X.X+int64+complex: cray-petsc-complex-64
```

Unfortunately whenever I do spack spec petsc+int64 or any of the ones with variants, I always get the defaults set by package.py. 

This is a problem since some of the cray packages we need to link with have variants with them.

**Comment by scheibelp** [comment]
I was able to get the desired behavior by setting the variants explicitly for all cases in packages.yaml:

```
petsc@3.7.5~int64~complex: cray-petsc
petsc@3.7.5+int64~complex: cray-petsc-64
petsc@3.7.5~int64+complex: cray-petsc-complex
petsc@3.7.5+int64+complex: cray-petsc-complex-64
```

Default variant settings are not considered when matching external specs in package.py to the spec the user provides on the command line, so for example ```petsc@X.X.X``` above matches any combination of user-specified variants when calling ```spack spec```. This also means that the user-specified variants should be explicit: ```spack spec petsc+int64``` matches ```petsc@X.X.X+int64+complex``` and ```petsc@X.X.X+int64~complex```, so ```spack spec petsc+int64~complex``` is best.

It would be preferable if default settings were taken into account. As of now, from quickly skimming over the logic it seems to me this would take significant effort (e.g. a few days on my part). So assuming the above suggestion is suitable I would prioritize this low for now, but I'll leave the issue open.

**Comment by mamelara** [comment]
I guess cray-petsc is one of the easier ones to know what kind of variants were built. Other cray packages like fftw are unknown which probably means we might need to add a combination of variants for just one package (I guess that's fine? More work on the user though). I say this because I was trying to build abinit+openmp which depended on fftw but I didn't put any variants (because I don't know how it was built, thanks Cray!).

So is the suggestion for packages like fftw to take into account every combination of variant? It would be nice if we had some tag that said "this satisfies everything". If such a way exists I'd be interested to know.

Anyway, I'm tasked with setting suitable defaults for the consultants here so the burden is on me. The solution above works.

**Comment by adamjstewart** [comment]
If you don't specify any variants, it is equivalent to saying "this satisfies everything".

**Comment by mamelara** [comment]
```shell
spack spec abinit+openmp^intel-mkl^fftw+openmp
Input spec
--------------------------------
abinit+openmp
    ^fftw+openmp
    ^intel-mkl

Normalized
--------------------------------
abinit+openmp
    ^fftw+float+openmp
    ^intel-mkl
    ^libxc@2.2.2

Concretized
--------------------------------
==> Error: Invalid spec: 'fftw@3.3.6.2%gcc@6.3.0+double+float+long_double+mpi~openmp~pfft_patches~quad arch=cray-cnl6-ivybridge'. Package fftw requires variant +openmp, but spec asked for ~openmp
```

and in my packages.yaml

```yaml
    fftw:
        buildable: false
        modules:
            fftw@3.3.6.2%gcc@6.3.0 arch=cray-cnl6-ivybridge: cray-fftw
            fftw@3.3.6.2%intel@17.0.2.174 arch=cray-cnl6-ivybridge: cray-fftw
```  

Doesn't seem to work even if I explicitly say ```^fftw+openmp```
