### ISSUE TITLE
[Question] : How to register all external packages into db before spack install? 

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#5219]
Suppose I have specified external package as:

```
    boost:
        paths:
            boost@1.55.0%clang@8.1.0-apple: /usr/local
        version: [1.55.0]
```

Now if I check install status I see:

```
$ spack spec -I hdf5 %clang
Input spec
--------------------------------
     hdf5%clang
....
Concretized
--------------------------------
     boost@1.55.0%clang@8.1.0-apple+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=darwin-sierra-x86_64
```

It's not showing as installed because it is not registered into db yet. I know that when I will try to install it first time Spack will register into db and then we will see status as installed.

But suppose we have such 50 external packages into `packages.yaml` and would like to register all in one go (instead of doing one by one). Is there any way to do this?  (this will be "convenient" when we are providing `packages.yaml` to  end users and they can check the status of packages with `spec -I` and we don't have register with `spack install` one by one).

**Comment by svenevs** [comment]
I'm pretty sure all you're missing is `buildable: False`.

```yaml
boost:
    buildable: False
    paths:
        boost@1.55.0%clang@8.1.0-apple: /usr/local
    version: [1.55.0]
```

**Note**: you _may_ also need to explicitly specify the `variants` associated with your `boost` installation.  Hopefully not, though, because otherwise you'll have to know what they are (hard to discover after-the-fact...).

In my experience, there is a really subtle feature / bug that was explained to me by @adamjstewart the omnipotent.  I don't quite fully understand it, but say for example that you decided the default `boost` variants are exactly what you want.  Then you would now specify

```yaml
boost:
    buildable: False
    # NOTE: I moved this up here because below gets crazy
    # You don't need to move it
    version: [1.55.0]
    variants: +atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave
    # This is the feature / bug
    # The paths variable must explicitly state the EXACT SAME variants
    paths:
        boost@1.55.0%clang@8.1.0-apple+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave: /usr/local
```

It's something about because it's `buildable: False`.

There is one other thing going on here.  Now that you've made it `buildable: False`, you do still need to "install" it.  This is the only way that it gets registered in the database.  Once that's done, anything you're trying to compile with `boost` as a dependency should now show up as installed when you do `spack spec -I thing_depends_on_boost`.
