### ISSUE TITLE
better safeguards for module file generation (explicit stage printout, or pre-parse for validity)

### ISSUE THREAD

**Issue by svenevs** [spack/spack#5222]
**Edit**: suspected error in `openmpi` package was incorrect, it was `modules.yaml`.  See [comment below for details](https://github.com/LLNL/spack/issues/5222#issuecomment-325264940)

I can reliably get `OpenMPI` to completely build.  It never installs though.  I've never experienced anything like this with `spack` before...if it compiles...

```ruby
==> Error: TypeError: 'NoneType' object is not iterable                                       
/share/apps/spack/spack_all/lib/spack/spack/package.py:1350, in build_process:
```

In `lib/spack/spack/package.py`:

```py
1349                 # Run post install hooks before build stage is removed.
1350                 spack.hooks.post_install(self.spec) 
```

This is calling (?) this one in `openmpi` yes?

```py
367     @run_after('install')
368     def filter_compilers(self):
```

Relevant section of `compilers.yaml`:

```yaml
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
        cc: /share/apps/spack/spack_compilers/opt/spack/linux-rhel6-x86_64/gcc-4.9.2/gcc-7.2.0-j74oaigj3p5ikuneldzgxzqg42m3s3op/bin/gcc
        cxx: /share/apps/spack/spack_compilers/opt/spack/linux-rhel6-x86_64/gcc-4.9.2/gcc-7.2.0-j74oaigj3p5ikuneldzgxzqg42m3s3op/bin/g++
        f77: /share/apps/spack/spack_compilers/opt/spack/linux-rhel6-x86_64/gcc-4.9.2/gcc-7.2.0-j74oaigj3p5ikuneldzgxzqg42m3s3op/bin/gfortran
        fc: /share/apps/spack/spack_compilers/opt/spack/linux-rhel6-x86_64/gcc-4.9.2/gcc-7.2.0-j74oaigj3p5ikuneldzgxzqg42m3s3op/bin/gfortran
    spec: gcc@7.2.0
    target: x86_64
```

Any guidance greatly appreciated!

Admonition: yes, I fell into the misleading trap detailed in the docs.  I don't see how that would cause this though, and it's way too late to do anything else.

Note: nothing relevant in `spack-build.out`.  It compiles everything, and then says it's executing the `install` phase and then dies.
