### ISSUE TITLE
Spec/package reference error when compiler entry is added

### ISSUE THREAD

**Issue by scheibelp** [spack/spack#5505]
See: https://github.com/LLNL/spack/pull/4832

If I check out develop and add the following compiler entry to lib/spack/spack/test/data/compilers.yaml:

```
- compiler:
    spec: gcc@4.7.2
    operating_system: debian6
    paths:
      cc: /path/to/gcc-5
      cxx: /path/to/g++-5
      f77: None
      fc: None
    flags:
      cflags: -O3
      cxxflags: -O3
    modules: 'None'
```

Then “spack test store” fails with the following error:

```
==> Error: AttributeError: 'Spec' object has no attribute 'link_arg'
AttributeError: AttributeError: 'Spec' object has no attribute 'link_arg'

/g/g17/scheibel/repos/destdir/spack/var/spack/repos/builtin.mock/packages/cmake-client/package.py:70, in setup_environment:
     2             check(from_cmake == "from_cmake",
     3                   "setup_environment couldn't read global set by cmake.")
     4     
  >> 5             check(self.spec['cmake'].link_arg == "test link arg",
     6                   "link arg on dependency spec not readable from "
     7                   "setup_environment.")

See build log for details:
  /g/g17/scheibel/repos/destdir/spack/var/spack/stage/cmake-client-1.0-f3gg7u6ko74m6mzb5rjy2to4ni2ukhxr/mock-archive-repo/spack-build.out
```

No idea why this is happening at the moment, I need to look into it.
