### ISSUE TITLE
OpenMPI: Fortran compiler detection is wrong?

### ISSUE THREAD

**Issue by woodard** [spack/spack#5590]
==> Staging archive: /home/ben/Work/spack/var/spack/stage/openmpi-3.0.0-txgf5bbweja2eybc2bnl5zrcaxlsonvp/openmpi-3.0.0.tar.bz2
==> Created stage in /home/ben/Work/spack/var/spack/stage/openmpi-3.0.0-txgf5bbweja2eybc2bnl5zrcaxlsonvp
==> No patches needed for openmpi
==> Building openmpi [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Error: InstallError: OpenMPI requires both C and Fortran compilers!
InstallError: InstallError: OpenMPI requires both C and Fortran compilers!

/home/ben/Work/spack/var/spack/repos/builtin/packages/openmpi/package.py:286, in die_without_fortran:
     4             # avoid delayed build errors in dependents.
     5             if (self.compiler.f77 is None) or (self.compiler.fc is None):
     6                 raise InstallError(
  >> 7                     'OpenMPI requires both C and Fortran compilers!'
     8                 )

See build log for details:
  /home/ben/Work/spack/var/spack/stage/openmpi-3.0.0-txgf5bbweja2eybc2bnl5zrcaxlsonvp/openmpi-3.0.0/spack-build.out

Shouldn't that be: 
            if (self.compiler.f77 is None) and (self.compiler.fc is None):

when I changed the script, it built just fine.

**Comment by pramodskumbhar** [comment]
@woodard : the OpenMPI documentation [says](https://www.open-mpi.org/faq/?category=building):

> If you are building Open MPI from a tarball, you need a C compiler, a C++ compiler, and make. If you are building the Fortran 77 and/or Fortran 90 MPI bindings,

Which compilers are you using? For example, with gnu toolchain we just use gfortran and my `compilers.yaml` looks like:

```
    paths:
      cc: /path/gcc-4.9.0/install/bin/gcc
      cxx: /path/gcc-4.9.0/install/bin/g++
      f77: /path/gcc-4.9.0/install/bin/gfortran
      fc: /path/gcc-4.9.0/install/bin/gfortran
    spec: gcc@4.9.0
```

Could you check this?
