### ISSUE TITLE
Should `spack fetch` ignore or obey `buildable: false`?

### ISSUE THREAD

**Issue by svenevs** [spack/spack#5814]
Suppose the following `packages.yaml`:

```yaml
packages:
    qt:
        buildable: false
        variants: +gtk+opengl+webkit+phonon
        version: [5.7.1]
        paths:
            qt@5.7.1+gtk+opengl+webkit+phonon: /usr
    opencv:
        variants: +core~cuda+eigen+gtk+highgui+imgproc+ipp+jasper+java+jpeg+openmp+png+python+qt+shared+tiff~vtk+zlib
```

Then `spack fetch -D opencv+python ^python@3.6.2+tk` will download all of that, **including** `qt`.  Qt is the root of all evil, and so I just installed everything with `dnf`.

Is this the expected behaviour, or should the `buildable: False` be preventing `spack fetch -D` from downloading it?

I could see the argument for either, but for large packages such as `qt`, it seems more appropriate to not fetch it if `buildable: false` is set.  On the other hand, my use case for `spack fetch` is probably atypical.  I am about to sync Dropbox so I wanted to download all of the things I need to let `spack` do its thing while syncing Dropbox.  Given that `packages.yaml` can easily change, and the presumed purpose of `spack fetch` is for gathering things for e.g., an air-gapped cluster, it makes sense to download it all.

It's more just that `spack fetch` considers everything else in the `packages.yaml`, except for `buildable: false`.  AKA in order for it to even know to download `qt`, it saw I was asking for `opencv+qt` in `packages.yaml` (I think).
