### ISSUE TITLE
Special considerations for spack installed clang

### ISSUE THREAD

**Issue by svenevs** [spack/spack#5817]
I would like to submit a PR to add some docs, or else discuss a way to enable this by default.

### Problem

A `spack` installed `llvm` can be used as a compiler with the following steps

```console
$ spack install llvm
$ spack load llvm
$ spack compiler find
```

This results in an almost valid compiler.  There are two problems:

1. Many packages require a fortran compiler, which `llvm` still lacks.  I believe that will be changing in the nearish future, but for now, users should be encouraged to add a fortran compiler manually.  Typically the system `gfortran` is compatible, so this means they should edit `~/.spack/linux/compilers.yaml` to be

    ```yaml
    - compiler:
        environment: {}
        extra_rpaths: []
        flags: {}
        modules: []
        operating_system: fedora25
        paths:
          cc: /opt/spack/opt/spack/linux-fedora25-x86_64/gcc-6.4.1/llvm-5.0.0-id4ljxr45ihmyys2qr76ce7o7ungrtag/bin/clang
          cxx: /opt/spack/opt/spack/linux-fedora25-x86_64/gcc-6.4.1/llvm-5.0.0-id4ljxr45ihmyys2qr76ce7o7ungrtag/bin/clang++
        # ADD THESE TWO LINES!
          f77: /usr/bin/gfortran
          fc: /usr/bin/gfortran
        spec: clang@5.0.0
        target: x86_64
    ```

2. As I have now learned, this is not sufficient.  The `llvm` module most be loaded, else you run into e.g., `libiomp.so` not found.  This could also be supported by `extra_rpaths`, but the module created by `spack` seems to be the most logical choice:

    ```console
    $ cd $SPACK_ROOT/share/modules/linux-fedora25-x86_64
    $ ls llvm-*
    llvm-3.9.1-gcc-6.4.1-pusyhzj  llvm-5.0.0-gcc-6.4.1-id4ljxr
    ```

    Meaning that the `modules` list in the `compilers.yaml` should become `modules: [llvm-5.0.0-gcc-6.4.1-id4ljxr]`, which `spack` is able to find regardless of whether or not this is in `MODULEPATH`.

### Question

Are there already simple enough mechanisms in existence that `spack` would be able to detect (e.g., by examining the path for `cc` or `cxx`) this and auto-load this module?  Is there a reason not to do this?

### Proposed Solution

If there is even a faint possibility this could cause logistical problems (e.g., dual-spack :tm:), I would like to add a docs PR with a new section just after [Compilers Requiring Modules](http://spack.readthedocs.io/en/latest/getting_started.html#compilers-requiring-modules).  It would include an example of `3.9.1` and `5.0.0` together to make it clear how the `modules` part differs.

1. If desired, the proposed title would be `Special Considerations for Spack Installed LLVM`.
2. Any particular wisdom on choice of fortran compiler?  For example, instead encourage `flang`?  TBH from the looks of it, it's not exactly stable.  Definitely a major step in the right direction, but not exactly production ready in my naive opinion.

### Tangent

I'd like to add something on the page explaining exactly what the use of `environment` is and how to use it.  It seems useful, but it also seems like nonstandard YAML and I don't know what it's all about...
