### ISSUE TITLE
Unable to use cray compilers on ANL/theta(XC40)

### ISSUE THREAD

**Issue by balay** [spack/spack#6107]
I'm attempting spack/xsdk build on ANL/theta(XC40) - and having trouble with the 'module syntax in ~/.spack/packages.yaml

The softenv I'm using is:

```
balay@thetalogin6:~/spack> module list |& egrep \(PrgEnv\|mpich\|intel\)
  3) intel/18.0.0.128
 19) PrgEnv-intel/6.0.4
 21) cray-mpich/7.6.3
```

Using Instructions from http://spack.readthedocs.io/en/latest/getting_started.html?highlight=intel-mpi#spack-on-cray  - I have the following in my package.py

```
packages:
  mpich:
    modules:
      mpich@7.6.3%intel@18.0.0.128 arch=cray-CNL-mic_knl: cray-mpich
    buildable: False
  all:
    providers:
      mpi: [mpich]
    compiler: [intel@18.0.0.128]
```

With this - I get:

```
balay@thetalogin6:~/spack> spack spec parmetis
Input spec
--------------------------------
parmetis

Normalized
--------------------------------
parmetis
    ^cmake@2.8:
    ^metis@5:
    ^mpi

Concretized
--------------------------------
==> Error: invalid syntax (<string>, line 525)
```

And here is the bizzare part.
```
Could you help me with correctly configuring and using cray? And How do I debug this error?

**Comment by KineticTheory** [comment]
@balay FWIW - my `packages.yaml` entry for cray-mpich looks like this:

```
  mpich:
    version: [7.6.2]
    modules:
      mpich@7.6.2: cray-mpich/7.6.2
      mpich@7.5.2: cray-mpich/7.5.2
      mpich@7.4.2: cray-mpich/7.4.2
    buildable: False
```

I haven't tried to target KNL yet, so I'm not sure if you need the `arch` portion of the identifier.
