### ISSUE TITLE
intel-parallel-studio + intel-mpi 2018.0: ld: cannot find -lmpigi

### ISSUE THREAD

**Issue by baip** [spack/spack#6144]
I used Spack to install `intel-parallel-studio@professional.2018.0` and `intel-mpi@2018.0.128` (and `intel-mkl@2018.0.128`) on Rocks cluster 6.2/CentOS 6.6, and added the snippet below to `compilers.yaml`. Then when I tried to do `spack install elpa %intel@2018.0.128.6.4.0 ^intel-mkl@2018.0.128 ^intel-mpi@2018.0.128`, it gave an error: 

> 19    configure: error: in `/tmp/soft/spack-stage/spack-stage-UdeA2T/elpa-2016.05.004/spack-build':
   20    configure: error: C compiler cannot create executables

In `spack-build.out`, the relevant line says `ld: cannot find -lmpigi`. When I tested by building elpa manually with the Intel MPI compiler wrappers ( `mpiicc`), I had to `module add intel-mpi` **after** `intel-parallel-studio`, the reverse direction will give `ld: cannot find -lmpigi` error. How am I supposed to set up Spack to achieve similar behavior?

> - compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O3 -xHost -fPIC
      cxxflags: -O3 -xHost -fPIC
      cppflags: -O3 -xHost -fPIC
      fflags: -O3 -xHost -fPIC
      f90flags: -O3 -xHost -fPIC
    modules: [linux-centos6-x86_64/binutils-2.28-gcc-4.4.7-oh67qvy, linux-centos6-x86_64/gcc-6.4.0-gcc-4.4.7-bx5dbff, linux-centos6-x86_64/intel-parallel-studio-professional.2018.0-gcc-6.4.0-cuv5nrw]
    operating_system: centos6
    paths:
      cc: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-6.4.0/intel-parallel-studio-professional.2018.0-cuv5nrwzbxbrcuo5bid5akumubnbwp3p/compilers_and_libraries_2018.0.128/linux/bin/intel64/icc
      cxx: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-6.4.0/intel-parallel-studio-professional.2018.0-cuv5nrwzbxbrcuo5bid5akumubnbwp3p/compilers_and_libraries_2018.0.128/linux/bin/intel64/icpc
      f77: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-6.4.0/intel-parallel-studio-professional.2018.0-cuv5nrwzbxbrcuo5bid5akumubnbwp3p/compilers_and_libraries_2018.0.128/linux/bin/intel64/ifort
      fc: /share/apps/spack/opt/spack/linux-centos6-x86_64/gcc-6.4.0/intel-parallel-studio-professional.2018.0-cuv5nrwzbxbrcuo5bid5akumubnbwp3p/compilers_and_libraries_2018.0.128/linux/bin/intel64/ifort
    spec: intel@2018.0.128.6.4.0
    target: x86_64

**Comment by baip** [comment]
Furthermore, if I load the modulefiles in the correct order and try a dirty install: `spack install --dirty elpa %intel@2018.0.128 ^intel-mkl@2018.0.128 ^intel-mpi@2018.0.128`, it'd still give an error `cpp: error: language Host not recognized`. The cause of this seems to be that the `configure` script of elpa sets up the `CPP` variable to be `$(CC) -E` and in the case when `CC=mpiicc`, this `CPP` will be used to process Fortran files. I can get around this problem manually by calling `../configure  CPP='mpigcc -E'`, but I'm not yet familiar enough with Spack to know how to achieve the same thing.

**Comment by svenevs** [comment]
You may want to look at the [Compilers Requiring Modules](http://spack.readthedocs.io/en/latest/getting_started.html#compilers-requiring-modules) section, Intel is definitely one of those.  If `lmod` or `modules.yaml` do not mean anything to you, then you are likely using TCL modules with spack.  They should be in `$SPACK_ROOT/share/spack/modules/your-operating-system`.  Though they may also be in the actual intel installation directory (`$SPACK_ROOT/opt/spack`).

Assuming you followed the [Add Spack to the Shell](http://spack.readthedocs.io/en/latest/getting_started.html#add-spack-to-the-shell) part, you can just write the name of the module (the environment setup script adds this to your `$MODULEPATH`):

```yaml
- compiler:
    environment: {}
    extra_rpaths: []
    # ...
    modules:
    # I guessed what the name is, make sure this actually exists
    - intel-parallel-studio-professional.2018.0-cuv5nrw
```

You can load more than one module by adding another bullet below.  This should be the same as your `--dirty` installation, but possibly not.

There is another gotcha with Intel compilers specifically, which is that the MPI being used might not be the Intel one when compiling other packages.  To enforce this, you need to set the "provider" for MPI to be `intel-mpi`.  An example:

```yaml
packages:
    # any specific ones you have here
    # ...
    # For *ALL* packages
    all:
        compiler: [intel@2018.0.128]
        providers:
            ipp:       [intel-parallel-studio]
            mpi:       [intel-parallel-studio]
            mkl:       [intel-parallel-studio]
            lapack:    [intel-parallel-studio]
            scalapack: [intel-parallel-studio]
            blas:      [intel-parallel-studio]
            tbb:       [intel-parallel-studio]
            # I do not know whether this was included
            # daal:      [intel-parallel-studio]
```

Those configs may or may not be exactly correct, it depends on how you installed what.  This is one of the main problems with the Intel package right now.  If you want to start compiling things with say GCC, you need to comment all of that out :/
