### ISSUE TITLE
sanity checks or feedback to avoid surprises using packages.yaml

### ISSUE THREAD

**Issue by cyrush** [spack/spack#6557]
In my ``packages.yaml``, I provided:
```
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
     ....
       `mpi: [mvapich]`
   ...
  mvapich:
    paths:
      mvapich@2: /usr/local/tools/mvapich2-gnu-2.0/
    buildable: False
```
After building for quite some time, I noticed that `intel-mpi` was being built to satisfy `mpi`. 

Turns out  spack has an `mvapich2` package, but no `mvapich` package.  Replacing my `mvapich` entries with `mvapich2` resolved my problem. 

I am new to external packages, so I am not quite sure what the behavior should be for a package name that spack doesn't provide. But it was quite surprising that `intel-mpi` came into the mix due to my typos.
