### ISSUE TITLE
NetCDF : Flags being ignored

### ISSUE THREAD

**Issue by junkudo** [spack/spack#6749]
My command line optimization flag are being ignored(?) by the NetCDF build.
Spack command:
```
spack -d install -v netcdf@4.4.1.1%intel@16.0.3 cflags="-g -O0" cppflags="-g -O0" cxxflags="-g -O0" fflags="-g -O0" ~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-rhel7-x86_64
```

Spack debug output snippet:
```
[cc] /usr/tce/packages/intel/intel-16.0.3/bin/icc -I/usr/tce/packages/mvapich2/mvapich2-2.3-intel-16.0.3/include -I/g/g14/kudo4/spack/opt/spack/linux-rhel7-x86_64/intel-16.0.3/zlib-1.2.11-hhe7xrd6rlf7afevulaptctrum3673we/include -I/g/g1\
4/kudo4/spack/opt/spack/linux-rhel7-x86_64/intel-16.0.3/hdf5-1.10.1-soxcwgh2bnzzqmq5bvhvplysjxtizrfx/include -g -DHAVE_CONFIG_H -I. -I/g/g14/kudo4/spack/var/spack/stage/netcdf-4.4.1.1-6h45mookfhf7u5grqknfb5uc7dz2h5pz/netcdf-4.4.1.1/libd\
ispatch -I.. -I/g/g14/kudo4/spack/var/spack/stage/netcdf-4.4.1.1-6h45mookfhf7u5grqknfb5uc7dz2h5pz/netcdf-4.4.1.1/include -I/g/g14/kudo4/spack/opt/spack/linux-rhel7-x86_64/intel-16.0.3/hdf5-1.10.1-soxcwgh2bnzzqmq5bvhvplysjxtizrfx/include\
 -MT libdispatch_la-dcopy.lo -MD -MP -MF .deps/libdispatch_la-dcopy.Tpo -c dcopy.c -fPIC -DPIC -o .libs/libdispatch_la-dcopy.o -I/usr/tce/packages/mvapich2/mvapich2-2.3-intel-16.0.3/include
```
For some reason, I don't see any optimization flags.

### Information on your system
Platform : TOSS3/TOSS (Tri-Lab Operating System Stack)

Relevant configuration details:
compilers.yaml
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/intel/intel-16.0.3/bin/icc
      cxx: /usr/tce/packages/intel/intel-16.0.3/bin/icpc
      f77: /usr/tce/packages/intel/intel-16.0.3/bin/ifort
      fc: /usr/tce/packages/intel/intel-16.0.3/bin/ifort
    flags: {}
    spec: intel@16.0.3
    target: x86_64
```

packages.yaml:
```
packages:
  all:
    compiler: [intel, gcc, pgi, clang, xl, nag]
    providers:
      mpi: [mvapich2]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
  metis:
    version: [4.0.3]
  netlib-lapack:
    paths:
      netlib-lapack@3.4.2: /usr/lib64/
    buildable: False
  mvapich2:
    paths:
      mvapich2@2.3: /usr/tce/packages/mvapich2/mvapich2-2.3-intel-16.0.3/
    buildable: False
  mpich:
    buildable: False
  openmpi:
    buildable: False
  intel-mpi:
    buildable: False
  spectrum-mpi:
    buildable: False
  intel-parallel-studio:
    buildable: False
  cmake:
    paths:
      cmake@3.5.2 arch=linux-rhel7-x86_64: /usr/tce/packages/cmake/cmake-3.5.2/
    buildable: False
  pkg-config:
    paths:
      pkg-config@0.27.1 arch=linux-rhel7-x86_64: /usr/bin/
    buildable: False
  m4:
    paths:
      m4@1.4.16 arch=linux-rhe17-x86_64: /usr/bin/
    buildable: False
```
