### ISSUE TITLE
Binary-installed gfortran for macOS

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7143]
[I believe the information in here should be somehow added to the manual, on discussions of macOS.  These kinds of problems can crop up when you use a pre-built `gfortran` binary.  Installing it from source, aka `spack install gcc +fortran` or `brew install gcc`, does not seem to encounter these problems.]

I'm running macOS High Sierra, brand new installation.  Installed XCode, then GFortran.  Since I'm lazy, I installed a pre-built GFortran macOS binary (I used the gfortran 6.3 build, which is said to also work with High Sierra):
   https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

This gfortran worked OK on its own.  But when I ran from Spack, I got an error:
```
     4813  ld: library not found for -lcrt1.10.6.o
```
This problem is known.  Basically, the `gfortran` I was using did not know to look inside the Xcode I was using; probably because it was originally built on a different version of Xcode.  I fixed the problem by adding to the `flags:` section of `compilers.yaml`, which now looks lie this:
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
        ldflags: -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
    modules: []
    operating_system: highsierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
        ldflags: -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
    modules: []
    operating_system: highsierra
    paths:
      cc: null
      cxx: null
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@6.3.0
    target: x86_64
```
