### ISSUE TITLE
boost does not build with clang 9.0

### ISSUE THREAD

**Issue by jarrah42** [spack/spack#7170]
I'm not able to build boost with clang 9.0. This is on Mac OS X High Sierra.

```console
$ spack install boost
==> bzip2 is already installed in .../Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks
==> zlib is already installed in .../Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/zlib-1.2.11-t74siw3tvuz3vfb3rje5mkbiwneuzfb5
==> Installing boost
==> Using cached archive: .../.spack/cached_archives/boost/boost-1.60.0.tar.bz2
==> Staging archive: .../gw6/Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5/boost_1_60_0.tar.bz2
==> Created stage in .../Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Error: TypeError: a bytes-like object is required, not 'str'
TypeError: TypeError: a bytes-like object is required, not 'str'

.../Work/git/spack/var/spack/repos/builtin/packages/boost/package.py:385, in install:
     73            # The shared libraries are not installed correctly
     74            # on Darwin; correct this
     75            if (sys.platform == 'darwin') and ('+shared' in spec):
  >> 76                fix_darwin_install_name(prefix.lib)

See build log for details:
 .../Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5/boost_1_60_0/spack-build.out
```

**Comment by jrood-nrel** [comment]
Ah, I have not tried High Sierra, but for reference I use boost 1.60.0 consistently on multiple Sierra machines with Apple Clang 9.0.0:

```
machine:~ user$ spack find boost %clang
==> 1 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
boost@1.60.0
```

**Comment by ziolai** [comment]
@jarrah42 and @jrood-nrel: have same problem installing boost 1.60.0 on Mac OS X Sierra (as part of installing OpenFoam). Tried both gcc and Apple Clang 9.0.0. 

@jarrah42: did you resolve the issue? If so, how? 

@jrood-nrel: could you share your .spack/darwin/compilers.yaml ? 

Thank you so much! Domenico

**Comment by ziolai** [comment]
Update: 

I managed to edit my ./spack/darwin/compilers.yaml to include path to 
      cc: /Applications/Xcode.app/.../usr/bin/clang
      cxx: /Applications/Xcode.app/.../usr/bin/clang++
I found that difficulties persist, that is, I get the same error as reported by jarrah42. I also verified that spack install boost@1.60.0 -shared does fine, see below. 

Difficulties seems to reside with shared libraries. I see that an extra_rpath entry for the compiler.yaml does exist. I am not sure how to use it. Any thoughts? 

Thanks, Domenico. 

Domenicos-MBP:clang-9.0.0-apple ziolai$ spack install boost@1.60.0 %clang -shared 
==> bzip2 is already installed in /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/bzip2-1.0.6-dspzezlf3hhea4busq6pqyqkpba67vzg
==> zlib is already installed in /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/zlib-1.2.11-cpdvq4e7otjepbwdtxmgk5bzszze27fj
==> Installing boost
==> Using cached archive: /Users/ziolai/spack/var/spack/cache/boost/boost-1.60.0.tar.bz2
==> Staging archive: /Users/ziolai/spack/var/spack/stage/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa/boost_1_60_0.tar.bz2
==> Created stage in /Users/ziolai/spack/var/spack/stage/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Successfully installed boost
  Fetch: 0.20s.  Build: 7m 42.38s.  Total: 7m 42.58s.
[+] /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa

**Comment by jarrah42** [comment]
I haven't been able to get it to work.

**Comment by ziolai** [comment]
Thx. Good to know.

**Comment by jrood-nrel** [comment]
I'm worried about how old the Spack clone is for @jarrah42 since a version of boost isn't specified and it's using 1.60.0 when I would expect 1.66.0 unless a version was specified.

@ziolai I'm not sure `compilers.yaml` is going to help with the error @jarrah42 is seeing because it looks like a Python error.

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-7
      cxx: /usr/local/bin/g++-7
      f77: /usr/local/bin/gfortran-7
      fc: /usr/local/bin/gfortran-7
    spec: gcc@7.2.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-5
      cxx: /usr/local/bin/g++-5
      f77: /usr/local/bin/gfortran-5
      fc: /usr/local/bin/gfortran-5
    spec: gcc@5.4.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-6
      cxx: /usr/local/bin/g++-6
      f77: /usr/local/bin/gfortran-6
      fc: /usr/local/bin/gfortran-6
    spec: gcc@6.4.0
    target: x86_64
```

```
machine:~ user$ spack find -vd boost
==> 2 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
    boost@1.60.0+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave
        ^bzip2@1.0.6+shared
        ^zlib@1.2.11+optimize+pic+shared


-- darwin-sierra-x86_64 / gcc@7.2.0 -----------------------------
    boost@1.60.0+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave
        ^bzip2@1.0.6+shared
        ^zlib@1.2.11+optimize+pic+shared
```
