### ISSUE TITLE
Package julia build fails on CentOS 7

### ISSUE THREAD

**Issue by phxyz12** [spack/spack#7198]
Dear all
Here I'd like to file a build error for the julia package on CentOS 7 x86_64. Many thanks in advance for your support.
Kind regards
Pascal

---

Summary

### Expected Result

Package julia (current version offered in package: 0.5.2) builds successfully on CentOS 7 on x86_64.

### Actual Result

Package build attempt fails with three errors:
```4 errors found in build log:
     396      checking for ld used by gcc -m64 ... Making all in src
     397      -- Found Perl: /usr/bin/perl (found version "5.16.3")
  >> 398      Can't open perl script "scripts/config.pl": No such file or directory
     399      yes
     ...
     38405    a - SuiteSparse_config.o
  >> 38406    /bin/sh: line 0: cd: metis-4.0: No such file or directory
     38407    yes
     38408    checking for Fortran 77 compiler default output file name... a.out
     ...
     40115    # Copy system image
     40116    /tmp/swadm/spack-stage/spack-stage-eM1cm5/julia-0.5.2/contrib/install.sh 644 /tmp/swadm/spack-stage/spack-stage-
              eM1cm5/julia-0.5.2/usr/lib/julia/sys.ji /cfs/software/spack/linux-centos7-x86_64/gcc-7.2.0/julia-0.5.2-xbgtifss5
              fm4wfuxelr3ktiwe2ltn2mq/lib/julia
  >> 40117    cp: cannot stat ‘/tmp/swadm/spack-stage/spack-stage-eM1cm5/julia-0.5.2/usr/lib/julia/sys.ji’: No such file o
              r directory
```

### Steps to reproduce the issue

```console
$ spack install julia %gcc@7.2.0
```

### Information on your system

This includes:

 1. which platform you are using: **CentOS 7 on x86_64**
 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)
**modules.yaml:**
```
modules:
  enable:
    - lmod
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  lmod:
    hash_length: 0
    whitelist:
      - gcc
    core_compilers:
      - 'gcc@4.8.5'
```
### Additional information
I tried to add metis as a build dependency, but this does not have any effect on the metis error.
