### ISSUE TITLE
Question: how to inject binutils dependency

### ISSUE THREAD

**Issue by rrdrake** [spack/spack#7341]
I am trying to build openmpi with a clang compiler, but the `libsigsegv` library fails due to an ld failure.  I would like to try using a binutils already built with spack.

What is the best way to make it use a specific binutils?  Inject a dependency?  Add a PATH?

I tried adding this in the compiler
```
compiler:
    environment: {PATH=.../spack/opt/spack/linux-rhel6-x86_64/gcc-4.9.2/binutils.../bin}
    extra_rpaths: [/projects/alegra/gcc492/lib64]
    flags: {}
```
But that didn't seem to work.

I am running on RHEL6.

Thanks!
