### ISSUE TITLE
Installation of intel-mkl under macOS

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7396]
Installing intel-mkl under macOS gives the issue described here: #3730. I had some time to investigate it in detail. This is not an Intel issue. Intel provides different packages for Linux and macOS. Both contain the same ``install.sh``, but the rest of the packages are different. The macOS package is a ``*.dmg`` archive.

I can not see any way to get it to work under macOS. A workaround is as follows:
1. Download intel-mkl from Intel's homepage
2. Install intel-mkl manually
3. Add the following to your ``~/.spack/packages.yaml``:
```
all:
  intel-mkl:
    paths:
      intel-mkl@2018.1.126 arch=<your-system>: /opt/intel
```
