### ISSUE TITLE
Installation of suite-sparse fails due to cmake not found

### ISSUE THREAD

**Issue by cpraveen** [spack/spack#7537]
-----

Summary

Unable to install suite-sparse

### Expected Result

To install dealii@develop and dependencies

### Actual Result

Fails at suite-sparse

```
     20    make[1]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/SuiteSparse_config'
     21    ( cd GraphBLAS && make CMAKE_OPTIONS='-DCMAKE_INSTALL_PREFIX=/home/praveen/Applications/spack/opt/spack/linux-opensuse20180316-x86_64/gcc-7.3
           .1/suite-sparse-5.2.0-f6bv4u5efrw5kw74h7jrpwkmabeysmc3' install )
     22    make[1]: Entering directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS'
     23    ( cd build ; cmake -DCMAKE_INSTALL_PREFIX=/home/praveen/Applications/spack/opt/spack/linux-opensuse20180316-x86_64/gcc-7.3.1/suite-sparse-5.2
           .0-f6bv4u5efrw5kw74h7jrpwkmabeysmc3 .. ; make ; make install )
     24    /bin/sh: cmake: command not found
     25    make[2]: Entering directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS/build'
  >> 26    make[2]: *** No targets specified and no makefile found.  Stop.
     27    make[2]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS/build'
     28    make[2]: Entering directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS/build'
  >> 29    make[2]: *** No rule to make target 'install'.  Stop.
     30    make[2]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS/build'
     31    make[1]: *** [Makefile:27: install] Error 2
     32    make[1]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-Nzej3V/SuiteSparse/GraphBLAS'
     33    make: *** [Makefile:40: install] Error 2
```

But spack has already installed cmake at this stage !!!

### Steps to reproduce the issue

```console
spack install -j6 --only dependencies dealii@develop ^cmake@3.9.4
```

I get same problem even when I don't force the cmake version.

### Information on your system

I am on OpenSuse tumbleweed

My compilers.yaml file

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: opensuse20180316
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77: /usr/bin/gfortran-7
      fc: /usr/bin/gfortran-7
    spec: gcc@7.3.1
    target: x86_64
```

My packages.yaml file

```
packages:
   hdf5:
      variants: +fortran
   petsc:
      variants: +mumps
   dealii:
      variants: ~python
   all:
      providers:
         mpi: [mpich]
```

Detailed log

[spack-build.out.txt](https://github.com/spack/spack/files/1831959/spack-build.out.txt)
