### ISSUE TITLE
cray: spack tries to install to a system directory when using cmake module

### ISSUE THREAD

**Issue by cwsmith** [spack/spack#7629]
### Summary

On Titan (Cray XK7) spack (`develop` branch, 70a8219f9) successfully builds metis, but fails during the install when it tries to write to a system directory.  Interestingly, the directory it is trying to install to is where cmake was installed by OLCF admins using spack.

Note, the above problem occurs when I use the cmake module in my `packages.yaml`. When the path is specified as follows:
```yaml
  cmake:
    paths:
      cmake@3.9.0: /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx
    buildable: False
```
the installation completes successfully.

### Expected Result

metis installed in my local spack directory.

### Actual Result

spack fails when trying to install metis to a system directory

### Steps to reproduce the issue

```console
$ ./bin/spack --debug --verbose install -v metis%pgi@17.9.0 target=interlagos &> usingModules.log 
```
[`usingModules.log`](https://github.com/spack/spack/files/1856865/usingModules.log)

### Information on your system

This includes:

 1. which platform you are using: 
Titan Cray XK7
```console
$ ./bin/spack arch                                                                                                                                   
cray-cnl5-interlagos
```

 2. any relevant configuration detail:

packages.yaml
```yaml
packages:
  mpich:
    modules:
      mpich@7.6.3%cce@8.6.4 arch=cray-CNL-interlagos: cray-mpich
      mpich@7.6.3%pgi@17.9.0 arch=cray-CNL-interlagos: cray-mpich
    buildable: False
  cmake:
    modules:
      cmake@3.9.0: cmake3/3.9.0
    buildable: False
  all:
    compiler: [cce/8.6.4,pgi/17.9.0]
    providers:
      mpi: [mpich]
```

**Comment by cwsmith** [comment]
A little digging...

There are spack files in the cmake system install dir:
```
$ lss /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/.spack/
total 756
-rw-r--r-- 1 uamntr ccsstaff   1650 Aug  8  2017 spec.yaml
drwxr-sr-x 6 uamntr ccsstaff   4096 Aug  8  2017 ..
-rw-r--r-- 1 uamntr ccsstaff 716977 Aug  8  2017 build.out
-rw-r--r-- 1 uamntr ccsstaff  27846 Aug  8  2017 build.env
drwxr-sr-x 3 uamntr ccsstaff   4096 Aug  8  2017 .
drwxr-sr-x 4 uamntr ccsstaff   4096 Aug  8  2017 repos
```

but, the log does not appear to show any obviously incorrect/problematic yaml reads.
```
$ grep -i 'yaml' log
==> Reading config file /autofs/nccs-svm1_home1/cwsmith/killme/spack/etc/spack/defaults/packages.yaml
==> Reading config file /ccs/home/cwsmith/.spack/packages.yaml
==> WRITE LOCK: /ccs/home/cwsmith/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> WRITE LOCK: /ccs/home/cwsmith/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> WRITE LOCK: /ccs/home/cwsmith/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /ccs/home/cwsmith/.spack/cray/compilers.yaml```

**Comment by mamelara** [comment]
I think your packages.yaml might be incorrect. 

For modules you need to provide the following:

```yaml
packages:
  cmake:
     modules:
       cmake@3.9.0: cmake3/3.9.0
     buildable: False
```

**Comment by cwsmith** [comment]
@mamelara Sorry about the typo.  I fixed the `packages.yaml` in the OP.

**Comment by cwsmith** [comment]
a little more digging...

Using the `cmake3/3.6.0` module to build metis results in a successful install.  Here are the relevant lines from my `packages.yaml`:

```yaml
  cmake:
    modules:
      cmake@3.6.0: cmake3/3.6.0
    buildable: False
```

The 3.9.0 and 3.6.0 modules set different environment variables.

```console
$ module show cmake3/3.6.0
-------------------------------------------------------------------
/sw/xk6/modulefiles/cmake3/3.6.0:

module-whatis    cmake @3.6.0 
prepend-path     --delim : PATH /autofs/nccs-svm1_sw/xk6/.spack/opt/spack/linux-SuSE11-x86_64/gcc-4.7/cmake-3.6.0-lqvzqvt7edyoklqzbk2lnt6mrtgyw5qv/bin 
prepend-path     --delim : CMAKE_PREFIX_PATH /autofs/nccs-svm1_sw/xk6/.spack/opt/spack/linux-SuSE11-x86_64/gcc-4.7/cmake-3.6.0-lqvzqvt7edyoklqzbk2lnt6mrtgyw5qv/ 
-------------------------------------------------------------------

$ module show cmake3/3.9.0
-------------------------------------------------------------------
/sw/xk6/modulefiles/cmake3/3.9.0:

module-whatis    cmake @3.9.0 
prepend-path     PATH /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/bin 
prepend-path     CMAKE_PREFIX_PATH /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/ 
prepend-path     ACLOCAL_PATH /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/share/aclocal 
setenv           OLCF_CMAKE_ROOT /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx 
-------------------------------------------------------------------
```
