### ISSUE TITLE
Cannot build "openmpi % clang"

### ISSUE THREAD

**Issue by KineticTheory** [spack/spack#7697]
### Summary

I'm trying to build openmpi@3.0.1 with clang@6.0.0, but the configure step fails with the following error

```
  configure: WARNING: Could not find functional C++ compiler, but
  configure: WARNING: support for the C++ MPI bindings was requested.
  configure: error: Cannot continue
```

The underlying error is `error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory`

Does anyone have advice for this recipe?  I'm guessing someone is building OpenMPI with Clang.  Is this error possibly related to #7115?

### Actual Result

When running `spack install openmpi % clang`, the build fails.  The relevant errors are here...

`spack-build.out` reports:

```
*** C++ compiler and preprocessor
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether /home/kt/spack.20180406/lib/spack/env/clang/clang++ accepts -g... (cached) yes
checking dependency style of /home/kt/spack.20180406/lib/spack/env/clang/clang++... (cached) gcc3
checking how to run the C++ preprocessor... /home/kt/spack.20180406/lib/spack/env/clang/clang++ -E
checking if C++ compiler works... no
**********************************************************************
* It appears that your C++ compiler is unable to produce working
* executables.  A simple test application failed to properly
* execute.  Note that this is likely not a problem with Open MPI,
* but a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compiler and what error resulted when the command was executed) is
* available in the config.log file in the Open MPI build directory.
**********************************************************************
configure: WARNING: Could not find functional C++ compiler, but
configure: WARNING: support for the C++ MPI bindings was requested.
configure: error: Cannot continue
```

`config.log` reports:

```
configure:23539: checking if C++ compiler works
configure:23583: /home/kt/spack.20180406/lib/spack/env/clang/clang++ -o conftest -O3 -DNDEBUG -finline-functions   -I/home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0/zlib-1.2.11-5qffmms6gwykcikh6aag4h3z4scrfdla/include   -L/home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/clang-6.0.0/zlib-1.2.11-5qffmms6gwykcikh6aag4h3z4scrfdla/lib conftest.cpp  -lz >&5
configure:23583: $? = 0
configure:23583: ./conftest
./conftest: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
configure:23583: $? = 127
configure: program exited with status 127
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Open MPI"
| #define PACKAGE_TARNAME "openmpi"
| #define PACKAGE_VERSION "3.0.1"
| #define PACKAGE_STRING "Open MPI 3.0.1"

<snip>

| #define OPAL_ALIGNMENT_DOUBLE_COMPLEX 8
| #define OPAL_ALIGNMENT_LONG_DOUBLE_COMPLEX 16
| #define OPAL_ALIGNMENT_VOID_P 8
| #define OPAL_ALIGNMENT_SIZE_T 8
| #define OPAL_CXX "/home/kt/spack.20180406/lib/spack/env/clang/clang++"
| #define SIZEOF_BOOL 0
| #define OPAL_ALIGNMENT_CXX_BOOL 1
| #define OMPI_CXX "/home/kt/spack.20180406/lib/spack/env/clang/clang++"
| /* end confdefs.h.  */
| #include <string>
| 
| int
| main ()
| {
| std::string foo = "Hello, world"
|   ;
|   return 0;
| }
configure:23599: result: no
configure:24458: WARNING: Could not find functional C++ compiler, but
configure:24460: WARNING: support for the C++ MPI bindings was requested.
configure:24462: error: Cannot continue
```

### Steps to reproduce the issue

```console
$ spack install llvm
# register clang@6.0.0 in compilers.yaml
$ spack install openmpi % clang
```

### Information on your system

 1. I see this error on two systems.  Once is RHEL7 the other is Ubuntu 18.04 under Windows 10 WLS.
 2. I'm using the `develop` branch of spack (updated 2018-04-07).
 3. configuration details:

```
# compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/llvm-6.0.0-shkmxxrtlpnrhqbbgksl67arwx3ig5jb/bin/clang
      cxx: /home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/llvm-6.0.0-shkmxxrtlpnrhqbbgksl67arwx3ig5jb/bin/clang++
      f77: gfortran
      fc: gfortran
    spec: clang@6.0.0
    target: x86_64
```

* In `packages.yaml` I register cmake as an external to avoid the `spack install cmake @ clang` issue (#6844).

```
# packages.yaml
packages:
  cmake:
    buildable: False
    modules:
      cmake: cmake
```

**Comment by scheibelp** [comment]
Is this an RPATH problem? i.e. if you set `extra_rpaths` to include the Spack-built clang lib directory/ies is the issue resolved?

FWIW if this does fix it: we are working on automatically updating compiler definitions to rpath compiler lib directories at https://github.com/spack/spack/pull/7153

**Comment by KineticTheory** [comment]
@scheibelp I haven't tried setting `extra_rpaths` yet.  However, I did find a configuration that worked for me.  

1. Modify `compilers.yaml` for `clang@6.0.0` by specifying `LD_LIBRARY_PATH` (setting `extra_rpaths` might have the same effect - I'll try that later today.):

```
- compiler:
    environment:
      set:
        LD_LIBRARY_PATH: /home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/llvm-6.0.0-shkmxxrtlpnrhqbbgksl67arwx3ig5jb/lib
    extra_rpaths: []
    flags:
      cxxflags: -std=c++11 -stdlib=libc++
    modules: []
    operating_system: ubuntu18.04
    paths:
      cc: /home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/llvm-6.0.0-shkmxxrtlpnrhqbbgksl67arwx3ig5jb/bin/clang
      cxx: /home/kt/spack.20180406/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/llvm-6.0.0-shkmxxrtlpnrhqbbgksl67arwx3ig5jb/bin/clang++
      f77: gfortran
      fc: gfortran
    spec: clang@6.0.0
    target: x86_64
```

2. Tweak the `openmpi/package.py` recipe:

```diff
@@ -186,10 +186,19 @@ class Openmpi(AutotoolsPackage):
         multi=True
     )
 
+    # Note: loadleveler is not a configure option (at least for 3.0.1).
+    # Trying to use @when('@3:') doesn't work here:
     variant(
         'schedulers',
         description='List of schedulers for which support is enabled',
-        values=('alps', 'lsf', 'tm', 'slurm', 'sge', 'loadleveler'),
+        values=('alps', 'lsf', 'tm', 'slurm', 'sge'),
         multi=True
     )
 
@@ -265,6 +274,15 @@ class Openmpi(AutotoolsPackage):
             libraries, root=self.prefix, shared=True, recursive=True
         )
 
+    # This hack was needed to successfully link to libz.so produced by spack.
+    @when('@3:')
+    def setup_environment(self, spack_env, run_env):
+        spack_env.append_flags('CFLAGS', '-fPIC')
+        spack_env.append_flags('FCFLAGS', '-fPIC')
+
     def setup_dependent_environment(self, spack_env, run_env, dependent_spec):
         spack_env.set('MPICC',  join_path(self.prefix.bin, 'mpicc'))
         spack_env.set('MPICXX', join_path(self.prefix.bin, 'mpic++'))
@@ -382,7 +400,7 @@ class Openmpi(AutotoolsPackage):
                 config_args.append('--enable-contrib-no-build=vt')
 
         # Multithreading support
+        # This option doesn't seem to be valid for version 3.0.1.
-        if spec.satisfies('@1.5.4:'):
+        if spec.satisfies('@1.5.4:@3.0.0'):
             if '+thread_multiple' in spec:
                 config_args.append('--enable-mpi-thread-multiple')
             else:
```

Adding `-fPIC` to the compiler options and setting `LD_LIBRARY_PATH` in `compilers.yaml` were sufficient to build `openmpi@3.0.1%clang@6.0.0`.  The other changes silence configure warnings. I still need to verify this hack on my RHEL7 machine.
