### ISSUE TITLE
spack install hypre fails for Mac OS

### ISSUE THREAD

**Issue by JohnWGrove** [spack/spack#7803]
Summary

The installation for hypre fails for spack on Mac OS 10.13.4. The failure occurs when openblas 0.2.20 installation is attempted. This failure occurs for both gcc7.3 and intel 18.0.2. The problem is not spack directly but really openblas-0.2.20 which tries to use assembler commands that do not exist for this system. I don't give a hoot about openblas since I really want to use the system versions of blas and lapack. The problem is that the spack default configuration for hypre tries to build openblas. When I build hypre by hand, the configure options --with-blas and --with-lapack  will use the system files in /usr/lib, which works. I cannot for the life of me figure out from the spack documentation how to tell it to use these options, much less how to write a package.yaml specialization to tell all packages to use the system versions of blas and lapack. I tried using blas : [system] and lapack : [system] in my user packages.yaml and this didn't help. I also tried removing these lines entires. In either case spack still tries to build openblas.

### Expected Result

spack install hypre %gcc@7.3.0
and
spack install hypre %intel@18.0.2

work

### Actual Result

The command spack install hypre %gcc7.3.0 fails with the error message
==> Installing openblas
==> Using cached archive: /Users/jgrove/spack/var/spack/cache/openblas/openblas-0.2.20.tar.gz
==> Staging archive: /Users/jgrove/spack/var/spack/stage/openblas-0.2.20-cqu36bmxblsej2t4vro52tvfxhhmwbg5/v0.2.20.tar.gz
==> Created stage in /Users/jgrove/spack/var/spack/stage/openblas-0.2.20-cqu36bmxblsej2t4vro52tvfxhhmwbg5
==> Applied patch make.patch
==> Building openblas [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' 'CC=/Users/jgrove/spack/lib/spack/env/gcc/gcc' 'FC=/Users/jgrove/spack/lib/spack/env/gcc/gfortran' 'MAKE_NO_J=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'

1 error found in build log:
     2337    ../kernel/x86_64/saxpy_microk_sandy-2.c:82:no such instruction: `vaddps %ymm11, %ymm7,%ymm15'
     2338    ../kernel/x86_64/saxpy_microk_sandy-2.c:83:no such instruction: `vmovups %ymm12, -128(%rdx,%rax,4)'
     2339    ../kernel/x86_64/saxpy_microk_sandy-2.c:84:no such instruction: `vmovups %ymm13, -96(%rdx,%rax,4)'
     2340    ../kernel/x86_64/saxpy_microk_sandy-2.c:85:no such instruction: `vmovups %ymm14, -64(%rdx,%rax,4)'
     2341    ../kernel/x86_64/saxpy_microk_sandy-2.c:86:no such instruction: `vmovups %ymm15, -32(%rdx,%rax,4)'
     2342    ../kernel/x86_64/saxpy_microk_sandy-2.c:87:no such instruction: `vzeroupper'
  >> 2343    make[1]: *** [Makefile.L1:640: saxpy_k.o] Error 1
     2344    make[1]: Leaving directory '/private/var/folders/jl/9jpdtxpj67v2z2kn9x6bh0d8000c82/T/jgrove/spack-stage/sp
             ack-stage-8O8TWh/OpenBLAS-0.2.20/kernel'
     2345    make: *** [Makefile:139: libs] Error 1

See build log for details:
  /Users/jgrove/spack/var/spack/stage/openblas-0.2.20-cqu36bmxblsej2t4vro52tvfxhhmwbg5/OpenBLAS-0.2.20/spack-build.out

This is really a problem with OpenBLAS-0.2.20 which apparently does not properly support Macs. I don't want to use OpenBLAS anyway, just to tell hypre to use the system versions of blas and lapack. I expect this issue occurs for all packages that try to use blas or lapack, directly or indirectly and the correct configuration in my opinion is that for Mac darwin, use the system provided versions of these libraries.

### Steps to reproduce the issue

On a Mac running OS 10.13.4 run

```console
$ spack install hypre %gcc@7.3.0
and/or
$ spack install hypre %intel@18.0.2
...
```

### Information on your system

This includes:

 1. Late 2013 MacPro running OS 10.13.4
 2. I tried modifying packages.yaml as follow but this had no effect

packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [system]
      daal: [intel-daal]
      elf: [elfutils]
      gl: [mesa, opengl]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [system]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]

**Comment by adamjstewart** [comment]
Can you try building with Clang? I haven't had any problems building `openblas` on macOS 10.13.4 with Clang 9.0.0. I haven't had a lot of luck building most packages on macOS with GCC.

As for using the system BLAS/LAPACK, you need to specify which package to use (it has to be a Spack package name), where it lives (the installation directory), and what version it is. I believe the system BLAS/LAPACK on macOS is called `veclibfort`? So you would want something like:
```yaml
packages:
    all:
        providers:
            blas: [veclibfort]
            lapack: [veclibfort]
    veclibfort:
        paths:
            veclibfort@0.4.2: /usr
        buildable: False
```
The chunk under `providers:` tells Spack to use `veclibfort` as the default BLAS/LAPACK provider. The chunk under `veclibfort:` tells Spack that you already have it installed, not to try to build it again, and where it can be found.

For more info, see http://spack.readthedocs.io/en/latest/build_settings.html#external-packages

**Comment by JohnWGrove** [comment]
Thanks Adam. I eventually stumbled on this feature and got hypre to build using the changes you suggest to package.yaml, except I used netlib-lapack@3.6.1<mailto:netlib-lapack@3.6.1> as shown in your getting started guide. I am not sure the degree to which the name of the library actually matters, since ultimate it looks for the location of libblas.dylib and liblapack.dylib, or more precisely that -lblas and -llapack find the library during a build. I did the install for openblas with clang and that seemed to work (spack install openblas %clang@9.1.0-apple). I noticed a related issue when I tried to build fftw. That build fails for gcc for what seems to be a similar reason for the problem with openblas, but when I did a manual download of fftw-3.3.7 and configured it to use GNU it compiled normally.  Looking at the compile logs for the two builds it appears that spack wants to build dft/simd/avx, while the default configuration for fftw is to not build this library. I tried configuring fftw the same way spack did using

./configure –-prefix=$HOME/junk/TOGO --enable-shared --enable-threads --enable-mpi --disable-sse --enable-sse2 --enable-avx --enable-avx2 --disable-avx512 --disable-avx-128-fma --disable-kcvi --disable-altivec --disable-vsx --disable-neon --disable-generic-simd128 --disable-generic-simd256 --disable-fma

and this now failed for the same reason as spack. This relates to my question below about how to customize a package specification to provide the desired configuration specifications. I redid the configuration using

./configure --prefix=$HOME/junk/TOGO --enable-shared --enable-threads --enable-mpi --disable-sse --enable-sse2 --disable-avx --disable-avx2 --disable-avx512 --disable-avx-128-fma --disable-kcvi --disable-altivec --disable-vsx --disable-neon --disable-generic-simd128 --disable-generic-simd256 --disable-fma

(which seems to be close to the defaults) and that worked. So the issue seems to be that the AVX optimizations don’t work for GNU. I also installed fftw for intel (spack install fftw %intel@18.0.2<mailto:%25intel@18.0.2>) and this did work.

The problem with clang is that our Eulerian Applications project at Los Alamos uses a lot of Fortran (the codes are mostly Fortran), so clang isn’t enough and flang is too immature for our use at this time. This is the main reason I use GNU and Intel for the compilers for Mac, which is actually a very good development platform.  I use both because GNU is often better at catching bugs in the way I can understand and Intel is the same compiler we use on our production HPC machines.

I wonder if you could point me to some more detailed information about package customization. I want to specify things like optimization flags (I realize these flags can be added for all packages in compilers.yaml but I would like to be able to specify them individually for packages). Other flags would be configure or cmake options (for example to turn off AVX optimization for GNU when installing fftw), and even better would be able to give a single prefix for all of the packages I install so that they all sit together where I can easily find them. This might also be done using symbolic links to the installed packages and I wonder if spack already has this ability. The load option for spack of course enables using a package, but I dislike having really long environment variables like LD_LIBRARY_FLAGS and it simplifies our Makefile to only have to give one -L command for the location of the external packages.

Thanks for your help.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by davydden** [comment]
>  I believe the system BLAS/LAPACK on macOS is called veclibfort? 

that's not entirely correct. `veclibfort` fixes some fortran-related things in macOS blas/lapack:

> vecLibFort is lightweight but flexible "shim" designed to rectify the incompatibilities between the Accelerate/vecLib BLAS and LAPACK libraries shipped with Mac OS X and FORTRAN code compiled with modern compilers such as GNU Fortran.

But yes, the only thing you need to do is
```
packages:
    all:
        providers:
            blas: [veclibfort]
            lapack: [veclibfort]
```
You **don't** need to tell Spack that `veclibfort` is a system-provided package (it is not!).

**Comment by davydden** [comment]
p.s. otherwise, I also have no issue using Apple's `clang` and `gfortran` to build `openblas`.

**Comment by JohnWGrove** [comment]
Thanks for the note. I was using the macports installed version of gcc. I am in the process of building the spack version to see if this issue is somehow related to differences in the way the compilers are built. Openblas for clang builds correctly with spack for me too. The spack build for gcc is ongoing and will probably take a while. I am taking vacation the rest of the week and will try out your suggestions on Monday. Thanks for the info on veclibfort. I will use that for blas. It turns out that my project wants to use openblas for other reasons, so getting that working will be very helpful. I am sort of the Guinea pig  for spack on macs in my project. So getting things working for me will help many others who want to use macs for desktop development. Since our HPC systems regularly go down for all day maintenance, being able to work on a desktop system is very helpful.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by davydden** [comment]
@JohnWGrove 

> otherwise, I also have no issue using Apple's clang and gfortran to build openblas.

I would actually suggest this route. Last time I tried using GCC for both C/C++ and Fortran on macOS I always had some issues with other packages like CMake. Whereas Apple's Clang + GCC gfortran works fine for me on dependency-reach packages like [deal.II](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py#L108-L150). But it could be that for the packages you will be building pure GCC is fine on macOS, hard to say.

**Comment by citibeth** [comment]
Increasingly, things just don't build on Mac with GCC.  I had Spack build a GCC for me, and then set up my `compilers.yaml` with it, but JUST FOR FORTRAN:
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/gfortran
      fc: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/gfortran
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/gcc
      cxx: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/g++
      f77: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/gfortran
      fc: /Users/rpfische/spack/gcc/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/gcc-6.4.0-ph64x3ujobquzhno56opmg3ig7mnntku/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64
```
