### ISSUE TITLE
Is it possible to extend the module template with comment lines ?

### ISSUE THREAD

**Issue by samfux84** [spack/spack#7821]
I am currently using the following "modules.yaml" for creation of lmod modules:

```
modules:
  enable:
    - lmod
    - tcl
  lmod:
    hash_length: 0
    core_copmilers: ['gcc@4.8.5']
    all:
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH
```
This way I have added a variable ${PACKAGE}_ROOT to the standard template.

Now I would like to ask if also other things different from environment variables can be added to the template (for instance comment lines) ? I would like to add additional tags (in the form of comments) to module files, which I can afterwards parse with some scripts. To give an example, I would like to add a tag "category" to classify software. The Matlab or R modules would then contain a tag

-- #category: mathematics

This would allow me to parse the module files and create some documentation for our wiki (for instance to show what version of a software are available on the cluster). My final goal is, that after installing an new application or library I would just run a script and the wiki would be automatically updated.

In combination with the Semantic MediaWiki package, these additional tags would allow me to create sublists of all installed software (like a list of all CFD packages, or all chemistry packages)

I have the scripts and the setup on the wiki in place already, but now I would like to use spack to automatically add the tags to the module files, when they are created.
