### ISSUE TITLE
libx11 installation with intel 18.0.1 fails during configure stage

### ISSUE THREAD

**Issue by samfux84** [spack/spack#8049]
Summary:

`spack install libx11@1.6.3 ^inputproto@2.3.2 ^kbproto@1.0.7  ^libxcb@1.12 ^pkg-config@0.29.2 ^util-macros@1.19.1 ^xextproto@7.3.0 ^xproto@7.0.29 ^xtrans@1.3.5 ^libpthread-stubs@0.3 %intel@18.0.1 arch=linux-centos7-x86_64`

fails in configure stage due to a conflict between the configure script of libx11 and the cpp wrapper from SPACK

### Expected Result

That libx11 compiles with intel@18.0.1

### Actual Result

```
==> Executing phase : 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/cluster/apps/spack/var/spack/stage/libx11-1.6.3-fnpagv4reyxraalvu7iie5goqftxnr25/libX11-1.6.3/configure' '--prefix=/cluster/spack/apps/linux-centos7-x86_64/intel-18.0.1/libx11-1.6.3-fnpagv4reyxraalvu7iie5goqftxnr25'
/cluster/apps/spack/lib/spack/spack/build_systems/autotools.py:266, in configure:
     258      def configure(self, spec, prefix):
     259          """Runs configure with the arguments specified in
     260          :py:meth:`~.AutotoolsPackage.configure_args`
     261          and an appropriately set prefix.
     262          """
     263          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     264  
     265          with working_dir(self.build_directory, create=True):
  >> 266              inspect.getmodule(self).configure(*options)

See build log for details:
  /scratch/spackapps/spack-stage/spack-stage-vT5yhC/libX11-1.6.3/spack-build.out
```

The spack-build.out contains the following logs:

```
checking for cpp... /cluster/apps/spack/lib/spack/env/cpp
checking if /cluster/apps/spack/lib/spack/env/cpp requires -undef... cpp: error: language core-avx2 not recognized
cpp: error: language core-avx2 not recognized
cpp: error: language core-avx2 not recognized
cpp: error: language core-avx2 not recognized
cpp: error: language core-avx2 not recognized
cpp: error: language core-avx2 not recognized
configure: error: /cluster/apps/spack/lib/spack/env/cpp defines unix with or without -undef.  I don't know what to do.
```

compiler.yaml:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O2 -xcore-avx2 -march=core-avx2
      cppflags: -O2 -xcore-avx2 -march=core-avx2
      cxxflags: -O2 -xcore-avx2 -march=core-avx2
    modules: []
    operating_system: centos7
    paths:
      cc: /cluster/apps/intel/parallel_studio_xe_2018_r1/compilers_and_libraries_2018.1.163/linux/bin/intel64/icc
      cxx: /cluster/apps/intel/parallel_studio_xe_2018_r1/compilers_and_libraries_2018.1.163/linux/bin/intel64/icpc
      f77: /cluster/apps/intel/parallel_studio_xe_2018_r1/compilers_and_libraries_2018.1.163/linux/bin/intel64/ifort
      fc: /cluster/apps/intel/parallel_studio_xe_2018_r1/compilers_and_libraries_2018.1.163/linux/bin/intel64/ifort
    spec: intel@18.0.1
    target: x86_64
```

config.log:

```
configure:18727: checking for cpp
configure:18746: found /cluster/apps/spack/lib/spack/env/cpp
configure:18758: result: /cluster/apps/spack/lib/spack/env/cpp
configure:18774: checking if /cluster/apps/spack/lib/spack/env/cpp requires -undef
configure:18794: error: /cluster/apps/spack/lib/spack/env/cpp defines unix with or without -undef.  I don't know what to do.

```

Lines 18774 to 18794 from the configure script:

```
# Check for flag to avoid builtin definitions - assumes unix is predefined,
# which is not the best choice for supporting other OS'es, but covers most
# of the ones we need for now.
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if $RAWCPP requires -undef" >&5
$as_echo_n "checking if $RAWCPP requires -undef... " >&6; }
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */
Does cpp redefine unix ?
_ACEOF
if test `${RAWCPP} < conftest.$ac_ext | grep -c 'unix'` -eq 1 ; then
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
else
        if test `${RAWCPP} -undef < conftest.$ac_ext | grep -c 'unix'` -eq 1 ; then
                RAWCPPFLAGS=-undef
                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
        # under Cygwin unix is still defined even with -undef
        elif test `${RAWCPP} -undef -ansi < conftest.$ac_ext | grep -c 'unix'` -eq 1 ; then
                RAWCPPFLAGS="-undef -ansi"
                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes, with -ansi" >&5
$as_echo "yes, with -ansi" >&6; }
        else
                as_fn_error $? "${RAWCPP} defines unix with or without -undef.  I don't know what to do." "$LINENO" 5
        fi
fi
rm -f conftest.$ac_ext
```

### Information on your system

This includes:

 1. which platform you are using: CentOS Linux release 7.4.1708 (Core)
