### ISSUE TITLE
Buggy Config Precedence for `packages.yaml` with `all:`

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8150]
@tgamblin 
In `packages.yaml`,  variants added to `all:` to not take effect for packages with their own variants listed.  For example, consider `spack spec py-matplotlib` with the following `packages.yaml`:

```
   python:
        variants: [~pythoncmd]
        version: [3.5.2]
    py-matplotlib:
        variants: [+gui,+ipython,+python3]
 
    # --------- Compiler & Virtual Dependencies
    all:
        variants: [+python3]
        compiler: [gcc@4.9.3]
        providers:
            mpi: [openmpi]
            blas: [openblas]
            lapack: [openblas]
 ```

### Expected Result

`py-matplotlib` should concretize with `+python3` variant.

### Actual Result

I get `py-matplotlib~python3`

### Steps to reproduce the issue

1. Use the above `packages.yaml` file.
2. Try `spack spec py-matplotlib`

To show that the bug is related to the repeat, try:
1. Remove the `py-matplotlib:` entry from `packages.yaml`
2. Try `spack spec py-matplotlib` again.  Now, you should get the correct `py-matplotlib+python3`.
