### ISSUE TITLE
Unable to specify cflags, cxxflags, or fflags in a spec

### ISSUE THREAD

**Issue by djfitzgerald** [spack/spack#8258]
If you want to report a build error for some package, or a bug in core please use the following template as a guideline:

-----

Whenever I attempt to specify `fflags`, `cflags`, or `cxxflags` in a spec, I get the following error message from Python: `Error: 'module' object has no attribute 'compiler'`

### Expected Result

Specifying `fflags`, 'cflags', or `cxxflags` as part of a spec would be accepted by Spack and passed onto individual package build scripts.

### Actual Result

Received error message `Error: 'module' object has no attribute 'compiler'` and Spack processing terminated.

### Steps to reproduce the issue

```console
$ spack install --test=root boost%xl_r cflags="gnu++11"
$ spack spec boost%xl_r cflags="gnu++11"
```

### Information on your system

 1. RHEL 7.4 on POWER9
 2. Spack cloned from upstream `develop`
 3. Custom `compilers.yaml`, `packages.yaml`

`compilers.yaml`:
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -qzerosize
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/bin/xlc
      cxx: /usr/bin/xlC
      f77: /usr/bin/xlf
      fc: /usr/bin/xlf95
    spec: xl@16.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      fflags: -qzerosize
    modules: []
    operating_system: rhel7
    paths:
      cc: /usr/bin/xlc_r
      cxx: /usr/bin/xlc++_r
      f77: /usr/bin/xlf_r
      fc: /usr/bin/xlf90_r
    spec: xl_r@16.1
    target: ppc64le
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /pgi/linuxpower/17.10/bin/pgcc
      cxx: /pgi/linuxpower/17.10/bin/pgc++
      f77: /pgi/linuxpower/17.10/bin/pgfortran
      fc: /pgi/linuxpower/17.10/bin/pgfortran
    spec: pgi@17.10
    target: ppc64le
- compiler:
   environment: {}
   extra_rpaths: []
   flags: {}
   modules: []
   operating_system: rhel7
   paths:
     cc: /opt/clang-coral/bin/clang
     cxx: /opt/clang-coral/bin/clang++
     f77: xlf_r
     fc: xlf_r
   spec: clang@3.8.0
   target: ppc64le
```
`packages.yaml`:
```
packages:
  spectrum-mpi:
    paths: 
        spectrum-mpi@10.02.00 arch=linux-rhel7-ppc64le: /opt/ibm/spectrum_mpi
    version: [10.02.00]
    buildable: false
  essl:
    paths:
        essl@6.1 arch=linux-rhel7-ppc64le: /opt/ibmmath/essl/6.1
    version: [6.1]
    buildable: false
  all:
    providers:
      mpi: [spectrum-mpi]
```
