### ISSUE TITLE
blindly adding prefix.include in compiler wrappers can break Spack

### ISSUE THREAD

**Issue by davydden** [spack/spack#8324]
EDIT: see [below](https://github.com/spack/spack/issues/8324#issuecomment-393418311)

-----

Yet another strange compiler error with with `Intel@17.0.5`, externally provided.

### Expected Result

`suite-sparse` builds

### Actual Result

A few very weird compilation errors:

```
  >> 7269    ../Include/spqr.hpp(939): error: namespace "std" has no member "conj"
     7270          return (std::conj (x)) ;
     7271                       ^

     7495    In file included from ../Source/spqr_panel.cpp(31):
     7496    In file included from ../Source/spqr_tol.cpp(7):
  >> 7497    ../Include/spqr.hpp(23): error: qualified name is not allowed
     7498      typedef std::complex<double> Complex ;
     7499              ^

  >> 7506    ../Include/spqr.hpp(23): error: expected a ";"
     7507      typedef std::complex<double> Complex ;
     7508                          ^
```

This part of the header looks reasonable to me:
```
#include <complex>
typedef std::complex<double> Complex ;
```

This is being compiled with
```
/spack/lib/spack/env/intel/icpc -O3 -fPIC -fno-common -fexceptions   -O3 -fexceptions -fPIC     -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_tol.cpp
```

### Steps to reproduce the issue

```console
$ spack install spack spec suite-sparse@5.1.0
```

Using compiler outside of Spack I can compile `icpc test.cpp` a simple example without issues
```
#include <iostream>
#include <complex>
typedef std::complex<double> Complex ;

int main()
{
  Complex v;
  v.real(1.);
  v.imag(2.);
  Complex u = std::conj(v);
  std::cout << (v*u) << std::endl;

  return 0;
}
```

That's so weird...

### Information on your system

centos7

```
- compiler:
    environment:
      set:
        INTEL_LICENSE_FILE: 1713@license4
    extra_rpaths:
     - /apps/intel/ComposerXE2017/compilers_and_libraries_2017.5.239/linux/compiler/lib/intel64_lin
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /apps/intel/ComposerXE2017/compilers_and_libraries_2017.5.239/linux/bin/intel64/icc
      cxx: /apps/intel/ComposerXE2017/compilers_and_libraries_2017.5.239/linux/bin/intel64/icpc
      f77: /apps/intel/ComposerXE2017/compilers_and_libraries_2017.5.239/linux/bin/intel64/ifort
      fc: /apps/intel/ComposerXE2017/compilers_and_libraries_2017.5.239/linux/bin/intel64/ifort
    spec: intel@17.0.5
    target: x86_64
```
