### ISSUE TITLE
Bad Combination of Virtual Packages and buildable:False

### ISSUE THREAD

**Issue by citibeth** [spack/spack#834]
Consider the following packages.yaml file:

```
packages:
    all:
        compiler: [gcc@5.3.0]
        providers:
            mpi: [openmpi]
            blas: [openblas]
            lapack: [openblas]
```

`spack spec nccmp` gives the correct answer (nccmp depends_on('netcdf') only):

```
Concretized
------------------------------
  nccmp@1.8.2.0%gcc@5.3.0=linux-x86_64
      ^netcdf@4.4.0%gcc@5.3.0~hdf4+mpi=linux-x86_64
          ^curl@7.47.1%gcc@5.3.0=linux-x86_64
              ^openssl@1.0.2g%gcc@5.3.0=linux-x86_64
                  ^zlib@1.2.8%gcc@5.3.0=linux-x86_64
          ^hdf5@1.8.16%gcc@5.3.0~cxx~debug+fortran+mpi+shared~szip~threadsafe=linux-x86_64
              ^openmpi@1.10.2%gcc@5.3.0~psm~tm~verbs=linux-x86_64
                  ^hwloc@1.11.2%gcc@5.3.0=linux-x86_64
                      ^libpciaccess@0.13.4%gcc@5.3.0=linux-x86_64
                          ^libtool@2.4.6%gcc@5.3.0=linux-x86_64
```

Suppose I want to use a system-installed MPI.  I change `packages.yaml` to:

```
packages:
    openmpi:
        paths:
            openmpi@system: /usr/local/other/SLES11.3/openmpi/1.10.1/gcc-5.3
        buildable: False
    all:
        compiler: [gcc@5.3.0]
        providers:
            mpi: [openmpi]
            blas: [openblas]
            lapack: [openblas]
```

Now, `spack spec nccmp` tries to (wrongly) load `mvapich2` instead of `openmpi`:

```
Concretized
------------------------------
  nccmp@1.8.2.0%gcc@5.3.0=linux-x86_64
      ^netcdf@4.4.0%gcc@5.3.0~hdf4+mpi=linux-x86_64
          ^curl@7.47.1%gcc@5.3.0=linux-x86_64
              ^openssl@1.0.2g%gcc@5.3.0=linux-x86_64
                  ^zlib@1.2.8%gcc@5.3.0=linux-x86_64
          ^hdf5@1.8.16%gcc@5.3.0~cxx~debug+fortran+mpi+shared~szip~threadsafe=linux-x86_64
              ^mvapich2@2.2b%gcc@5.3.0~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp~psm~remshell~slurm~sock=linux-x86_64
```

**Comment by citibeth** [comment]
@tgamblin I'm wondering what carats really mean when you say `spack install`?  We've all encountered the issue where you say `spack install x ^y~variant`, and Spack tells you that x does not depend on y.  This is particularly vexing when x *does* depend on y, but transitively through a virtual package.

I'd like to suggest that the semantics of carats in `spack install` be changed somewhat, to be a "suggestion."  It should be equivalent to putting the same item `packages.yaml` (which also needs to be upgraded).  The idea is that if, while concretizing, Spack comes across a need for package y, THEN it will use the version and parameters in suggestion you mentioned.  At the end of concretization, Spack could give a warning/error for any suggestions it didn't use.

I think this would solve a lot of problems and make Spack's concretization more intuitive.  Any thoughts?

**Comment by adamjstewart** [comment]
> We've all encountered the issue where you say spack install x ^y~variant, and Spack tells you that x does not depend on y. This is particularly vexing when x does depend on y, but transitively through a virtual package.

The reason for this is that Spack doesn't take into account variants which are on by default. For example, if a package has an mpi variant on by default, and you say:
```
spack install package ^mvapich2
```
it will raise an error. But if you run:
```
spack install package +mpi ^mvapich2
```
it will succeed. This is a bug, but that's the workaround for now. I would love it if someone fixed it, but I'm swamped at the moment.

**Comment by tgamblin** [comment]
@adamjstewart: I agree.  It *is* annoying.  Unfortunately I'm swamped at the moment but this is high on my list too.  

@citibeth: for the `x does not depend on y` issue, the issue is that Spack doesn't look quite that far ahead when it's concretizing.  In particular it won't look past a conditional and keep around speculative constraints -- it prematurely decides the constrained package is not in the spec.  That check is vestigial from before we had optional dependencies.  We *could* solve this by keeping around constraints for longer.  I think that's actually a good idea and wouldn't be so hard to implement.  I can take a stab at this once we get #360 and #378 merged -- they both deal with concretization and I think the fix for this particular case is small.  If you feel adventurous you could look at `Spec.concretize` and `Spec.normalize`.  There is a very clear spot where Spack looks to see if any superfluous constraints are left over... we could hoist that out so that the check is done later to make this work.

@citibeth: Your first example looks like a bug.  The `openmpi` setting should get taken up by `ncmp` in your example.  I can take a look ta that.

**Comment by alalazo** [comment]
Seems to be fixed at 3cf21e6edc14e8431a0a65867a45df35aef1911e. Tested using this:
```yaml
spack:
  specs:
  - nccmp
  packages:
    openmpi:
      paths:
        openmpi@system: /usr/local/other/SLES11.3/openmpi/1.10.1/gcc-5.3
      buildable: false
    all:
      compiler: [gcc@5.3.0]
      providers:
        mpi: [openmpi]
        blas: [openblas]
        lapack: [openblas]
```
environment and this command:
```console
$ spack concretize
==> Concretized nccmp
 -   xi3hefc  nccmp@1.8.2.0%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   fd6v3mf      ^netcdf-c@4.7.2%gcc@9.0.1~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-ubuntu18.04-broadwell
 -   mqeptmg          ^hdf5@1.10.5%gcc@9.0.1~cxx~debug~fortran+hl+mpi patches=b61e2f058964ad85be6ee5ecea10080bf79e73f83ff88d1fa4b602d00209da9c +pic+shared~szip~threadsafe arch=linux-ubuntu18.04-broadwell
 -   2imjwtm              ^openmpi@system%gcc@9.0.1~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-ubuntu18.04-broadwell
[+]  os3djb5              ^zlib@1.2.11%gcc@9.0.1+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
[+]  b6pswuo          ^m4@1.4.18%gcc@9.0.1 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-broadwell
[+]  5omotir              ^libsigsegv@2.12%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell

```
