### ISSUE TITLE
CC, CXX etc. might be overridden by external modules loaded by compilers

### ISSUE THREAD

**Issue by alalazo** [spack/spack#8345]
When a compiler configuration is set to load a module, that module might contain modifications to the environment that should not be taken into account when building a package from Spack (for instance to `CC`, `CXX`, `FC` and `F77`). This can lead to weird errors during the build.

Stumbled on this while using a module for Intel compilers that set variables like `ICCCFG` (needed during the build) and also variables like `CC` (breaking the build, and in the module because it was meant to be used outside of Spack).

### Expected Result

`CC` and similar variables always point to Spack compiler wrappers when building a package in Spack.

### Actual Result

Environment modifications done loading modules happen last, so `CC` could be modified by module files. Note that according to comments in `build_environment` they happen last for good reasons, so changing the order of applications of the various environment modifications might not be an option.

### Steps to reproduce the issue

To reproduce the issue it should suffice to have an entry in `compilers.yaml` like:
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: ['intel/18.0.2']
    operating_system: rhel7
    paths:
      cc: /ssoft/spack/external/intel/2018.2/compilers_and_libraries_2018.2.199/linux/bin/intel64/icc
      cxx: /ssoft/spack/external/intel/2018.2/compilers_and_libraries_2018.2.199/linux/bin/intel64/icpc
      f77: /ssoft/spack/external/intel/2018.2/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
      fc: /ssoft/spack/external/intel/2018.2/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
    spec: intel@18.0.2
    target: x86_E5v4_Mellanox
```
where the module loaded sets `CC`, `CXX`, etc.
