### ISSUE TITLE
module refresh will not generate lmod files despite config

### ISSUE THREAD

**Issue by SteVwonder** [spack/spack#8646]
`module refresh` only generates tcl modules despite the following being in my `~/.spack/modules.yaml`:

```yaml
enable::
    -lmod
```
(Full config pasted further down)

I was able to temporarily work around this issue by running `spack module refresh --module-type lmod --delete-tree` but based on the [modules tutorial](https://spack.readthedocs.io/en/latest/tutorial_modules.html?highlight=lmod#core-compiler-mpi), this does not seem like it should be necessary.

### Expected Result

```console
→ spack module refresh
==> You are about to regenerate lmod module files for:
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
mfi7l5m autoconf@2.69    oyomxdk gettext@0.19.8.1  ffzbok4 libxml2@2.9.8            qfrwdna openssl@1.0.2o  5nqkfcn tcl@8.6.8
yk6ievw automake@1.16.1  r4e6p7x git@2.17.1        w5itwt6 lmod@7.7.29              vwvgnbn pcre@8.42       ecjbujt tmux@2.7
qrd3gzl bzip2@1.0.6      5ugdsox libbsd@0.8.6      ltnggmf lua@5.3.4                py2bqlz pcre@8.42       rh7gav6 xz@5.2.4
4wxypys curl@7.60.0      yprcni4 libevent@2.0.21   7nr5d5a lua-luafilesystem@1_6_3  ka6syh2 perl@5.26.2     vhzh5cf zlib@1.2.11
6idl5st emacs@26.1       vlje6ju libiconv@1.15     tp6kijo lua-luaposix@33.4.0      7yuszxv pkgconf@1.4.2
om6ee3r expat@2.2.5      3byxblk libsigsegv@2.11   ffrwz2d m4@1.4.18                sfsamtu readline@7.0
bfjm7it gdbm@1.14.1      hnkxexo libtool@2.4.6     wkyck36 ncurses@6.1              ucx2vrv tar@1.30
==> Do you want to proceed? [y/n]
```
Note the generation of `lmod modules`
### Actual Result

```console
→ spack module refresh
==> You are about to regenerate tcl module files for:
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
mfi7l5m autoconf@2.69    oyomxdk gettext@0.19.8.1  ffzbok4 libxml2@2.9.8            qfrwdna openssl@1.0.2o  5nqkfcn tcl@8.6.8
yk6ievw automake@1.16.1  r4e6p7x git@2.17.1        w5itwt6 lmod@7.7.29              vwvgnbn pcre@8.42       ecjbujt tmux@2.7
qrd3gzl bzip2@1.0.6      5ugdsox libbsd@0.8.6      ltnggmf lua@5.3.4                py2bqlz pcre@8.42       rh7gav6 xz@5.2.4
4wxypys curl@7.60.0      yprcni4 libevent@2.0.21   7nr5d5a lua-luafilesystem@1_6_3  ka6syh2 perl@5.26.2     vhzh5cf zlib@1.2.11
6idl5st emacs@26.1       vlje6ju libiconv@1.15     tp6kijo lua-luaposix@33.4.0      7yuszxv pkgconf@1.4.2
om6ee3r expat@2.2.5      3byxblk libsigsegv@2.11   ffrwz2d m4@1.4.18                sfsamtu readline@7.0
bfjm7it gdbm@1.14.1      hnkxexo libtool@2.4.6     wkyck36 ncurses@6.1              ucx2vrv tar@1.30
==> Do you want to proceed? [y/n]
```
Note the generation of `tcl modules`

### Steps to reproduce the issue

```console
# Clean clone of spack
# Edit ~/.spack/modules.yaml (see exact config further down)
$ spack install lmod emacs tmux # these are the packages that I happened to install first. I believe only lmod is necessary
$ spack module refresh
```

### Information on your system

This includes:

 1. which platform you are using

`Red Hat 7.5 (LLNL-managed desktop)`

 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

My modules.yaml:
```yaml
modules:
  enable::
    - lmod
  lmod:
    core_compilers:
      - 'gcc@4.8.5'
    hierarchy:
      - mpi
```
Output of `spack config get modules`:
```yaml
modules:
  enable:
  - lmod
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    lib:
    - LIBRARY_PATH
    - LD_LIBRARY_PATH
    lib64:
    - LIBRARY_PATH
    - LD_LIBRARY_PATH
    include:
    - CPATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    ? ''
    : - CMAKE_PREFIX_PATH
  lmod:
    hierarchy:
    - mpi
    hash_length: 7
    verbose: false
    core_compilers:
    - gcc@4.8.5
```
