### ISSUE TITLE
Intel fortran libraries aren't linked properly

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#8767]
### Expected Result

Spack installs packages using ifort correctly. 

Affects : https://github.com/spack/spack/issues/8616, https://github.com/spack/spack/issues/3204, https://github.com/spack/spack/issues/8326

### Actual Result

Builds are broken due to broken links to intel fortran libraries even though these libraries are present at the location specified by ```extra_rpaths```. I tried [implicit linking](https://github.com/spack/spack/pull/7153) but that didn't help either. Examples of runtime failure for various packages are given below.

Openblas: 
```
ImportError: /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/openblas-0.3.0-vhf45ztydok656i4lsuqhmlv2hehrbiz/lib/libopenblas.so.0: undefined symbol: for_cpystr
``` 
scipy: 
```
ImportError: /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-x86_64-linux-gnu.so: undefined symbol: d_int_val
```

### Attempts to fix
I modified compilers.yaml for the intel compiler to add ```-lifcore``` to ensure linking but to no avail: 
```
- compiler:                                                                                 
    environment: {}                                                                         
    extra_rpaths:                                                                           
    - /opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin          
    flags:                                                                                  
      cflags:   -xcore-avx2                                                                 
      cxxflags: -xcore-avx2                                                                 
      fcflags: -lifcore -fPIC                                                               
    modules:                                                                                
    - intel18                                                                               
    operating_system: centos7                                                               
    paths:                                                                                  
      cc: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc               
      cxx: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc             
      f77: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort            
      fc: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort             
    spec: intel@18.0.3                                                                      
    target: x86_64                                                                          
```
