### ISSUE TITLE
Permit a finer selection of autoloaded module files

### ISSUE THREAD

**Issue by alalazo** [spack/spack#8815]
As a user I want to be able to configure autoloading of module files with a finer grained selection mechanism so that I can select which type of dependencies should be loaded automatically.

fixes #8639

### Description
This is a proposal on how to solve #8639 and provide a better default for module generation. The `autoload` keyword in `modules.yaml`, explained [here](https://spack.readthedocs.io/en/latest/tutorial_modules.html#autoload-dependencies), currently supports only the two values `direct` (to load direct dependencies) and `all` (to transitively load all dependencies). As it was introduced before dependency types, it does not distinguish among `build`, `link`, `test` and `run` dependencies.

Following the suggestion of @adamjstewart (load `run` dependencies in module files by default) we could extend this keyword to support, in addition to the current, also the following syntax:
```yaml
autoload:
  - type: run # or any of the supported types
    depth: direct # or 'all'
```
Once the feature is there we should ship a default `modules.yaml` that, for `tcl`, does:
```yaml
modules:
  tcl:
    all:
      autoload:
        - type: run
          depth: direct
```
Similarly for `lmod`.

Waiting for thumbs up from @adamjstewart @matthiasdiener @tgamblin @hartzell before proceeding with the implementation.
