### ISSUE TITLE
Spack choosing virtual dependencies based on external installations

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#8899]
Spack completely disregards the default virtual providers if another virtual provider is present as an external installation. With the following `packages.yaml`:
```yaml
packages:
    all:
        providers:
            mpi: [openmpi]
            blas: [openblas]
```
I get what I would expect:
```console
$ spack spec mpi
Input spec
--------------------------------
mpi

Concretized
--------------------------------
openmpi@3.1.1%clang@9.0.0-apple~cuda+cxx_exceptions fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=darwin-highsierra-x86_64 
    ^hwloc@1.11.9%clang@9.0.0-apple~cairo~cuda+libxml2~pci+shared arch=darwin-highsierra-x86_64 
        ^libxml2@2.9.8%clang@9.0.0-apple~python arch=darwin-highsierra-x86_64 
            ^pkgconf@1.4.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^xz@5.2.4%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^zlib@1.2.11%clang@9.0.0-apple+optimize+pic+shared arch=darwin-highsierra-x86_64 

$ spack spec blas
Input spec
--------------------------------
blas

Concretized
--------------------------------
openblas@0.3.2%clang@9.0.0-apple cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=darwin-highsierra-x86_64 
```
However, as soon as I add external installations:
```yaml
packages:
    all:
        providers:
            mpi: [openmpi]
            blas: [openblas]
    mvapich2:
        paths:
            mvapich2@2.2: /usr
    intel-mkl:
        paths:
            intel-mkl@2018.2.199: /usr
```
I get something unexpected:
```console
$ spack spec mpi
Input spec
--------------------------------
mpi

Concretized
--------------------------------
mvapich2@2.2%clang@9.0.0-apple~alloca ch3_rank_bits=32 ~cuda~debug fabrics=psm file_systems= process_managers= +regcache threads=multiple arch=darwin-highsierra-x86_64 

$ spack spec blas
Input spec
--------------------------------
blas

Concretized
--------------------------------
intel-mkl@2018.2.199%clang@9.0.0-apple~ilp64+shared threads=none arch=darwin-highsierra-x86_64 
```
Note that `buildable: False` is not required. But it must be an external installation, it can't be a version or compiler constraint:
```yaml
packages:
    all:
        providers:
            mpi: [openmpi]
            blas: [openblas]
    mvapich2:
        version: [2.2]
    intel-mkl:
        compiler: [gcc]
```
```console
$ spack spec mpi
Input spec
--------------------------------
mpi

Concretized
--------------------------------
openmpi@3.1.1%clang@9.0.0-apple~cuda+cxx_exceptions fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=darwin-highsierra-x86_64 
    ^hwloc@1.11.9%clang@9.0.0-apple~cairo~cuda+libxml2~pci+shared arch=darwin-highsierra-x86_64 
        ^libxml2@2.9.8%clang@9.0.0-apple~python arch=darwin-highsierra-x86_64 
            ^pkgconf@1.4.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^xz@5.2.4%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^zlib@1.2.11%clang@9.0.0-apple+optimize+pic+shared arch=darwin-highsierra-x86_64 

$ spack spec blas
Input spec
--------------------------------
blas

Concretized
--------------------------------
openblas@0.3.2%clang@9.0.0-apple cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=darwin-highsierra-x86_64 
```
@scheibelp @tgamblin @alalazo
