### ISSUE TITLE
how to ask spack to use existing module? 

### ISSUE THREAD

**Issue by python152** [spack/spack#9353]
I am still not clear on how to make spack play nice with existing modules, and need some help.

Say my environment already have "cmake/3.9.2" available as a module compiled with gcc@4.8.5
and I want to install `protobuf` at the latest version. My compiler setting is 6.4.0 by default. The "concretization" shows that `protobuf` want to run with `cmake/3.12.2` with `gcc@6.4.0`. 

I want to instruct spack to use existing cmake module by:
```
spack install protobuf%gcc@6.4.0 cmake@3.9.2%gcc@4.8.5
```

This doesn't seem work - spack insists on installing a new cmake.  Any help?

**Comment by mwkrentel** [comment]
You're lucky it didn't rebuild gcc for you.   :-)

This is handled by a spack external package.  See spack readthedocs
Build customization --> External Packages.

You want to add an entry for cmake in your packages.yaml file in some
config scope directory.

For example, on one machine, I use a module 'CMake/3.8.2' for cmake
and I put in packages.yaml:

```
  cmake:
    modules:
      cmake@3.8.2:  CMake/3.8.2
    buildable: False
```

On another machine, /usr/bin/cmake is 3.11.0 and there I use this.
(Note that with 'paths:', you specify the directory one up from bin,
so in this case /usr, not /usr/bin.)

```
  cmake:
    paths:
      cmake@3.11.0:  /usr
    buildable: False
```

That's how you tell spack to use an pre-existing install instead of
building it itself.
