### ISSUE TITLE
Intel Parallel Studio writes user environment to module

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#9639]
When I install Intel Parallel Studio cluster.2018.3 I see it write my entire user environment to the module file. This includes `/usr/bin` for example so when I load and then unload the module, it removes `/usr/bin` from my path. I don't see this behavior with 2017.7 or 2019.0. I am not listing Parallel Studio as an external. I was hoping I could reproduce this with `spack install --fake`, but it doesn't. The command I am using is `spack install intel-parallel-studio@cluster.2018.3` and it installs fine, it just writes the module file wrong. I also didn't see this behavior in cluster.2018.1 before https://github.com/spack/spack/pull/7469 but have not tried cluster.2018.1 at present time.

### Information on your system

OS: CentOS 7

packages.yaml:
```
packages:
  binutils:
    version: [2.29.1]
  libxml2:
    version: [2.9.8]
    variants: +python
  glib:
    version: [2.55.1]
  m4:
    version: [1.4.18]
  boost:
    version: [1.68.0]
  cmake:
    version: [3.12.3]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.3]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.2]
    variants: fabrics=verbs schedulers=tm
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.3.222]
  intel-mkl:
    version: [2018.3.222]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  all:
    compiler: [gcc@6.2.0]
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.2]
      blas: [netlib-lapack@3.8.0]
      lapack: [netlib-lapack@3.8.0]
```
compilers.yaml:
```
compilers:
- compiler:
    extra_rpaths:
     - /nopt/apps/gcc/6.2.0/lib64 
     - /nopt/apps/gcc/6.2.0/libexec/gcc/x86_64-linux-gnu/6.2.0 
     - /nopt/apps/gcc/6.2.0/lib/gcc/x86_64-linux-gnu/6.2.0 
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /nopt/apps/gcc/6.2.0/bin/gcc
      cxx: /nopt/apps/gcc/6.2.0/bin/g++
      f77: /nopt/apps/gcc/6.2.0/bin/gfortran
      fc: /nopt/apps/gcc/6.2.0/bin/gfortran
    spec: gcc@6.2.0
    target: x86_64
```
