### ISSUE TITLE
Installation issue: mount-point-attributes

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [spack/spack#9652]
### Steps to reproduce the issue

```console
$ spack install mount-point-attributes 
... 
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'

5 errors found in build log:
     163    make  all-recursive
     164    make[1]: Entering directory '/tmp/pollinta/spack-stage/spack-stage-ANDknP/mountpointattr-1.1'
     165    Making all in src
     166    make[2]: Entering directory '/tmp/pollinta/spack-stage/spack-stage-ANDknP/mountpointattr-1.1/src'
     167    /bin/bash ../libtool  --tag=CXX   --mode=compile /home/pollinta/Desktop/spack/lib/spack/env/gcc/g++ -DHAVE_CONF
            IG_H -I. -I/home/pollinta/Desktop/spack/var/spack/stage/mount-point-attributes-1.1-7t6hx43bgjxzdhadsyxe7lgwx2tj
            dml3/mountpointattr-1.1/src -I..  -I/home/pollinta/Desktop/spack/var/spack/stage/mount-point-attributes-1.1-7t6
            hx43bgjxzdhadsyxe7lgwx2tjdml3/mountpointattr-1.1    -g -O2 -MT libmpattr_la-MountPointAttr.lo -MD -MP -MF .deps
            /libmpattr_la-MountPointAttr.Tpo -c -o libmpattr_la-MountPointAttr.lo `test -f 'MountPointAttr.C' || echo '/hom
            e/pollinta/Desktop/spack/var/spack/stage/mount-point-attributes-1.1-7t6hx43bgjxzdhadsyxe7lgwx2tjdml3/mountpoint
            attr-1.1/src/'`MountPointAttr.C
     168    libtool: compile:  /home/pollinta/Desktop/spack/lib/spack/env/gcc/g++ -DHAVE_CONFIG_H -I. -I/home/pollinta/Desk
            top/spack/var/spack/stage/mount-point-attributes-1.1-7t6hx43bgjxzdhadsyxe7lgwx2tjdml3/mountpointattr-1.1/src -I
            .. -I/home/pollinta/Desktop/spack/var/spack/stage/mount-point-attributes-1.1-7t6hx43bgjxzdhadsyxe7lgwx2tjdml3/m
            ountpointattr-1.1 -g -O2 -MT libmpattr_la-MountPointAttr.lo -MD -MP -MF .deps/libmpattr_la-MountPointAttr.Tpo -
            c MountPointAttr.C  -fPIC -DPIC -o .libs/libmpattr_la-MountPointAttr.o
  >> 169    MountPointAttr.C:132:1: error: narrowing conversion of '-1' from 'int' to 'short unsigned int' inside { } [-Wna
            rrowing]
     170     };
     171     ^
  >> 172    MountPointAttr.C:132:1: error: narrowing conversion of '-1' from 'int' to 'short unsigned int' inside { } [-Wna
            rrowing]
     173    Makefile:438: recipe for target 'libmpattr_la-MountPointAttr.lo' failed
  >> 174    make[2]: *** [libmpattr_la-MountPointAttr.lo] Error 1
     175    make[2]: Leaving directory '/tmp/pollinta/spack-stage/spack-stage-ANDknP/mountpointattr-1.1/src'
     176    Makefile:400: recipe for target 'all-recursive' failed
  >> 177    make[1]: *** [all-recursive] Error 1
     178    make[1]: Leaving directory '/tmp/pollinta/spack-stage/spack-stage-ANDknP/mountpointattr-1.1'
     179    Makefile:331: recipe for target 'all' failed
  >> 180    make: *** [all] Error 2
```

### Platform and user environment
```commandline
$ uname -a 
Linux lap15 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
``` 

not sure if relevant, so:
`packages.yaml`:
```
    autoconf:
        paths:
            autoconf@2.69: /usr
            buildable: False
    cmake:
        paths:
            cmake@3.10.2: /usr
            buildable: False
    curl:
        paths:
            curl@7.58.0: /usr
            buildable: False
    git:
        paths:
            git@2.17.1: /usr
            buildable: False
    libtool:
        paths:
            libtool@2.4.6: /usr
            buildable: False
    openssl:
        paths:
            openssl@1.1.0g: /usr
            buildable: False
    perl:
        paths:
            perl@5.26.1: /usr
            buildable: False
```
### Additional information

```console
$ spack spec --install-status mount-point-attributes
Input spec
--------------------------------
     mount-point-attributes

Concretized
--------------------------------
     mount-point-attributes@1.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]      ^autoconf@2.69%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]      ^automake@1.16.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]          ^perl@5.26.1%gcc@7.3.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64 
[+]      ^libtool@2.4.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
```
